// GENERATED by desktop/electron/scripts/vendor-lucide.mjs from
// lucide-static 1.47.0. Do not edit by hand; add a name there and rerun.
//
// ISC License
//
// Copyright (c) 2026 Lucide Icons and Contributors
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//
// ---
//
// The following Lucide icons are derived from the Feather project:
//
// airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out
//
// The MIT License (MIT) (for the icons listed above)
//
// Copyright (c) 2013-present Cole Bemis
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/// The vendored Lucide icons, each as its SVG child elements on a 24 x 24
/// grid: a tag and its attributes.
enum LucideIcon {
  appWindow('app-window', [
    (
      'rect',
      <String, String>{
        'x': '2',
        'y': '4',
        'width': '20',
        'height': '16',
        'rx': '2',
      },
    ),
    ('path', <String, String>{'d': 'M10 4v4'}),
    ('path', <String, String>{'d': 'M2 8h20'}),
    ('path', <String, String>{'d': 'M6 4v4'}),
  ]),
  archive('archive', [
    (
      'rect',
      <String, String>{
        'width': '20',
        'height': '5',
        'x': '2',
        'y': '3',
        'rx': '1',
      },
    ),
    ('path', <String, String>{'d': 'M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8'}),
    ('path', <String, String>{'d': 'M10 12h4'}),
  ]),
  arrowDown('arrow-down', [
    ('path', <String, String>{'d': 'M12 5v14'}),
    ('path', <String, String>{'d': 'm19 12-7 7-7-7'}),
  ]),
  arrowLeft('arrow-left', [
    ('path', <String, String>{'d': 'm12 19-7-7 7-7'}),
    ('path', <String, String>{'d': 'M19 12H5'}),
  ]),
  arrowRight('arrow-right', [
    ('path', <String, String>{'d': 'M5 12h14'}),
    ('path', <String, String>{'d': 'm12 5 7 7-7 7'}),
  ]),
  arrowUp('arrow-up', [
    ('path', <String, String>{'d': 'm5 12 7-7 7 7'}),
    ('path', <String, String>{'d': 'M12 19V5'}),
  ]),
  arrowUpRight('arrow-up-right', [
    ('path', <String, String>{'d': 'M7 7h10v10'}),
    ('path', <String, String>{'d': 'M7 17 17 7'}),
  ]),
  audioLines('audio-lines', [
    ('path', <String, String>{'d': 'M2 10v3'}),
    ('path', <String, String>{'d': 'M6 6v11'}),
    ('path', <String, String>{'d': 'M10 3v18'}),
    ('path', <String, String>{'d': 'M14 8v7'}),
    ('path', <String, String>{'d': 'M18 5v13'}),
    ('path', <String, String>{'d': 'M22 10v3'}),
  ]),
  ban('ban', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    ('path', <String, String>{'d': 'M4.929 4.929 19.07 19.071'}),
  ]),
  bell('bell', [
    ('path', <String, String>{'d': 'M10.268 21a2 2 0 0 0 3.464 0'}),
    (
      'path',
      <String, String>{
        'd': 'M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326',
      },
    ),
  ]),
  bookOpen('book-open', [
    ('path', <String, String>{'d': 'M12 5v16'}),
    (
      'path',
      <String, String>{
        'd': 'M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z',
      },
    ),
  ]),
  bookmark('bookmark', [
    (
      'path',
      <String, String>{
        'd': 'M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z',
      },
    ),
  ]),
  bot('bot', [
    ('path', <String, String>{'d': 'M12 8V4H8'}),
    (
      'rect',
      <String, String>{
        'width': '16',
        'height': '12',
        'x': '4',
        'y': '8',
        'rx': '2',
      },
    ),
    ('path', <String, String>{'d': 'M2 14h2'}),
    ('path', <String, String>{'d': 'M20 14h2'}),
    ('path', <String, String>{'d': 'M15 13v2'}),
    ('path', <String, String>{'d': 'M9 13v2'}),
  ]),
  brain('brain', [
    ('path', <String, String>{'d': 'M12 18V5'}),
    (
      'path',
      <String, String>{'d': 'M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4'},
    ),
    (
      'path',
      <String, String>{'d': 'M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5'},
    ),
    ('path', <String, String>{'d': 'M17.997 5.125a4 4 0 0 1 2.526 5.77'}),
    ('path', <String, String>{'d': 'M18 18a4 4 0 0 0 2-7.464'}),
    (
      'path',
      <String, String>{
        'd': 'M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517',
      },
    ),
    ('path', <String, String>{'d': 'M6 18a4 4 0 0 1-2-7.464'}),
    ('path', <String, String>{'d': 'M6.003 5.125a4 4 0 0 0-2.526 5.77'}),
  ]),
  calendar('calendar', [
    ('path', <String, String>{'d': 'M8 2v3'}),
    ('path', <String, String>{'d': 'M16 2v3'}),
    (
      'rect',
      <String, String>{
        'x': '3',
        'y': '3',
        'width': '18',
        'height': '18',
        'rx': '2',
      },
    ),
    ('path', <String, String>{'d': 'M3 9h18'}),
  ]),
  check('check', [
    ('path', <String, String>{'d': 'M20 6 9 17l-5-5'}),
  ]),
  chevronDown('chevron-down', [
    ('path', <String, String>{'d': 'm6 9 6 6 6-6'}),
  ]),
  chevronLeft('chevron-left', [
    ('path', <String, String>{'d': 'm15 18-6-6 6-6'}),
  ]),
  chevronRight('chevron-right', [
    ('path', <String, String>{'d': 'm9 18 6-6-6-6'}),
  ]),
  chevronUp('chevron-up', [
    ('path', <String, String>{'d': 'm18 15-6-6-6 6'}),
  ]),
  circle('circle', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
  ]),
  circleAlert('circle-alert', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    ('line', <String, String>{'x1': '12', 'x2': '12', 'y1': '8', 'y2': '12'}),
    (
      'line',
      <String, String>{'x1': '12', 'x2': '12.01', 'y1': '16', 'y2': '16'},
    ),
  ]),
  circleCheck('circle-check', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    ('path', <String, String>{'d': 'm16 9-5.5 5.5L8 12'}),
  ]),
  circleDot('circle-dot', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '1'}),
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
  ]),
  circleQuestionMark('circle-question-mark', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    ('path', <String, String>{'d': 'M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3'}),
    ('path', <String, String>{'d': 'M12 17h.01'}),
  ]),
  circleX('circle-x', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    ('path', <String, String>{'d': 'm15 9-6 6'}),
    ('path', <String, String>{'d': 'm9 9 6 6'}),
  ]),
  clipboard('clipboard', [
    (
      'rect',
      <String, String>{
        'width': '8',
        'height': '4',
        'x': '8',
        'y': '2',
        'rx': '1',
        'ry': '1',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
      },
    ),
  ]),
  clock('clock', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    ('path', <String, String>{'d': 'M12 6v6l4 2'}),
  ]),
  cloud('cloud', [
    (
      'path',
      <String, String>{
        'd': 'M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z',
      },
    ),
  ]),
  code('code', [
    ('path', <String, String>{'d': 'm16 18 6-6-6-6'}),
    ('path', <String, String>{'d': 'm8 6-6 6 6 6'}),
  ]),
  columns2('columns-2', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
      },
    ),
    ('path', <String, String>{'d': 'M12 3v18'}),
  ]),
  command('command', [
    (
      'path',
      <String, String>{
        'd': 'M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3',
      },
    ),
  ]),
  copy('copy', [
    (
      'rect',
      <String, String>{
        'width': '14',
        'height': '14',
        'x': '8',
        'y': '8',
        'rx': '2',
        'ry': '2',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
      },
    ),
  ]),
  copyCheck('copy-check', [
    ('path', <String, String>{'d': 'm12 15 2 2 4-4'}),
    (
      'rect',
      <String, String>{
        'width': '14',
        'height': '14',
        'x': '8',
        'y': '8',
        'rx': '2',
        'ry': '2',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
      },
    ),
  ]),
  cornerDownLeft('corner-down-left', [
    ('path', <String, String>{'d': 'M20 4v7a4 4 0 0 1-4 4H4'}),
    ('path', <String, String>{'d': 'm9 10-5 5 5 5'}),
  ]),
  cpu('cpu', [
    ('path', <String, String>{'d': 'M12 20v2'}),
    ('path', <String, String>{'d': 'M12 2v2'}),
    ('path', <String, String>{'d': 'M17 20v2'}),
    ('path', <String, String>{'d': 'M17 2v2'}),
    ('path', <String, String>{'d': 'M2 12h2'}),
    ('path', <String, String>{'d': 'M2 17h2'}),
    ('path', <String, String>{'d': 'M2 7h2'}),
    ('path', <String, String>{'d': 'M20 12h2'}),
    ('path', <String, String>{'d': 'M20 17h2'}),
    ('path', <String, String>{'d': 'M20 7h2'}),
    ('path', <String, String>{'d': 'M7 20v2'}),
    ('path', <String, String>{'d': 'M7 2v2'}),
    (
      'rect',
      <String, String>{
        'x': '4',
        'y': '4',
        'width': '16',
        'height': '16',
        'rx': '2',
      },
    ),
    (
      'rect',
      <String, String>{
        'x': '8',
        'y': '8',
        'width': '8',
        'height': '8',
        'rx': '1',
      },
    ),
  ]),
  database('database', [
    ('ellipse', <String, String>{'cx': '12', 'cy': '5', 'rx': '9', 'ry': '3'}),
    ('path', <String, String>{'d': 'M3 5V19A9 3 0 0 0 21 19V5'}),
    ('path', <String, String>{'d': 'M3 12A9 3 0 0 0 21 12'}),
  ]),
  download('download', [
    ('path', <String, String>{'d': 'M12 15V3'}),
    (
      'path',
      <String, String>{'d': 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4'},
    ),
    ('path', <String, String>{'d': 'm7 10 5 5 5-5'}),
  ]),
  ellipsis('ellipsis', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '1'}),
    ('circle', <String, String>{'cx': '19', 'cy': '12', 'r': '1'}),
    ('circle', <String, String>{'cx': '5', 'cy': '12', 'r': '1'}),
  ]),
  ellipsisVertical('ellipsis-vertical', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '1'}),
    ('circle', <String, String>{'cx': '12', 'cy': '5', 'r': '1'}),
    ('circle', <String, String>{'cx': '12', 'cy': '19', 'r': '1'}),
  ]),
  externalLink('external-link', [
    ('path', <String, String>{'d': 'M15 3h6v6'}),
    ('path', <String, String>{'d': 'M10 14 21 3'}),
    (
      'path',
      <String, String>{
        'd': 'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6',
      },
    ),
  ]),
  eye('eye', [
    (
      'path',
      <String, String>{
        'd': 'M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0',
      },
    ),
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '3'}),
  ]),
  file('file', [
    (
      'path',
      <String, String>{
        'd': 'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      },
    ),
    ('path', <String, String>{'d': 'M14 2v5a1 1 0 0 0 1 1h5'}),
  ]),
  fileCode('file-code', [
    (
      'path',
      <String, String>{
        'd': 'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      },
    ),
    ('path', <String, String>{'d': 'M14 2v5a1 1 0 0 0 1 1h5'}),
    ('path', <String, String>{'d': 'M10 12.5 8 15l2 2.5'}),
    ('path', <String, String>{'d': 'm14 12.5 2 2.5-2 2.5'}),
  ]),
  fileImage('file-image', [
    (
      'path',
      <String, String>{
        'd': 'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      },
    ),
    ('path', <String, String>{'d': 'M14 2v5a1 1 0 0 0 1 1h5'}),
    ('circle', <String, String>{'cx': '10', 'cy': '12', 'r': '2'}),
    (
      'path',
      <String, String>{'d': 'm20 17-1.296-1.296a2.41 2.41 0 0 0-3.408 0L9 22'},
    ),
  ]),
  fileText('file-text', [
    (
      'path',
      <String, String>{
        'd': 'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      },
    ),
    ('path', <String, String>{'d': 'M14 2v5a1 1 0 0 0 1 1h5'}),
    ('path', <String, String>{'d': 'M10 9H8'}),
    ('path', <String, String>{'d': 'M16 13H8'}),
    ('path', <String, String>{'d': 'M16 17H8'}),
  ]),
  files('files', [
    (
      'path',
      <String, String>{
        'd': 'M15 2h-4a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M16.706 2.706A2.4 2.4 0 0 0 15 2v5a1 1 0 0 0 1 1h5a2.4 2.4 0 0 0-.706-1.706z',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M5 7a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 1.732-1',
      },
    ),
  ]),
  folder('folder', [
    (
      'path',
      <String, String>{
        'd': 'M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z',
      },
    ),
  ]),
  folderOpen('folder-open', [
    (
      'path',
      <String, String>{
        'd': 'm6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2',
      },
    ),
  ]),
  folderPlus('folder-plus', [
    ('path', <String, String>{'d': 'M12 10v6'}),
    ('path', <String, String>{'d': 'M9 13h6'}),
    (
      'path',
      <String, String>{
        'd': 'M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z',
      },
    ),
  ]),
  globe('globe', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    (
      'path',
      <String, String>{'d': 'M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20'},
    ),
    ('path', <String, String>{'d': 'M2 12h20'}),
  ]),
  gripVertical('grip-vertical', [
    ('circle', <String, String>{'cx': '9', 'cy': '12', 'r': '1'}),
    ('circle', <String, String>{'cx': '9', 'cy': '5', 'r': '1'}),
    ('circle', <String, String>{'cx': '9', 'cy': '19', 'r': '1'}),
    ('circle', <String, String>{'cx': '15', 'cy': '12', 'r': '1'}),
    ('circle', <String, String>{'cx': '15', 'cy': '5', 'r': '1'}),
    ('circle', <String, String>{'cx': '15', 'cy': '19', 'r': '1'}),
  ]),
  hash('hash', [
    ('line', <String, String>{'x1': '4', 'x2': '20', 'y1': '9', 'y2': '9'}),
    ('line', <String, String>{'x1': '4', 'x2': '20', 'y1': '15', 'y2': '15'}),
    ('line', <String, String>{'x1': '10', 'x2': '8', 'y1': '3', 'y2': '21'}),
    ('line', <String, String>{'x1': '16', 'x2': '14', 'y1': '3', 'y2': '21'}),
  ]),
  house('house', [
    (
      'path',
      <String, String>{'d': 'M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8'},
    ),
    (
      'path',
      <String, String>{
        'd': 'M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z',
      },
    ),
  ]),
  image('image', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
        'ry': '2',
      },
    ),
    ('circle', <String, String>{'cx': '9', 'cy': '9', 'r': '2'}),
    (
      'path',
      <String, String>{'d': 'm21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21'},
    ),
  ]),
  info('info', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '10'}),
    ('path', <String, String>{'d': 'M12 16v-4'}),
    ('path', <String, String>{'d': 'M12 8h.01'}),
  ]),
  keyRound('key-round', [
    (
      'path',
      <String, String>{
        'd': 'M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z',
      },
    ),
    (
      'circle',
      <String, String>{
        'cx': '16.5',
        'cy': '7.5',
        'r': '.5',
        'fill': 'currentColor',
      },
    ),
  ]),
  keyboard('keyboard', [
    ('path', <String, String>{'d': 'M10 8h.01'}),
    ('path', <String, String>{'d': 'M12 12h.01'}),
    ('path', <String, String>{'d': 'M14 8h.01'}),
    ('path', <String, String>{'d': 'M16 12h.01'}),
    ('path', <String, String>{'d': 'M18 8h.01'}),
    ('path', <String, String>{'d': 'M6 8h.01'}),
    ('path', <String, String>{'d': 'M7 16h10'}),
    ('path', <String, String>{'d': 'M8 12h.01'}),
    (
      'rect',
      <String, String>{
        'width': '20',
        'height': '16',
        'x': '2',
        'y': '4',
        'rx': '2',
      },
    ),
  ]),
  languages('languages', [
    ('path', <String, String>{'d': 'm5 8 6 6'}),
    ('path', <String, String>{'d': 'm4 14 6-6 2-3'}),
    ('path', <String, String>{'d': 'M2 5h12'}),
    ('path', <String, String>{'d': 'M7 2h1'}),
    ('path', <String, String>{'d': 'm22 22-5-10-5 10'}),
    ('path', <String, String>{'d': 'M14 18h6'}),
  ]),
  layers('layers', [
    (
      'path',
      <String, String>{
        'd': 'M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17',
      },
    ),
  ]),
  library('library', [
    ('path', <String, String>{'d': 'm16 6 4 14'}),
    ('path', <String, String>{'d': 'M12 6v14'}),
    ('path', <String, String>{'d': 'M8 8v12'}),
    ('path', <String, String>{'d': 'M4 4v16'}),
  ]),
  link('link', [
    (
      'path',
      <String, String>{
        'd': 'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71',
      },
    ),
  ]),
  list('list', [
    ('path', <String, String>{'d': 'M3 5h.01'}),
    ('path', <String, String>{'d': 'M3 12h.01'}),
    ('path', <String, String>{'d': 'M3 19h.01'}),
    ('path', <String, String>{'d': 'M8 5h13'}),
    ('path', <String, String>{'d': 'M8 12h13'}),
    ('path', <String, String>{'d': 'M8 19h13'}),
  ]),
  listChecks('list-checks', [
    ('path', <String, String>{'d': 'M13 5h8'}),
    ('path', <String, String>{'d': 'M13 12h8'}),
    ('path', <String, String>{'d': 'M13 19h8'}),
    ('path', <String, String>{'d': 'm3 17 2 2 4-4'}),
    ('path', <String, String>{'d': 'm3 7 2 2 4-4'}),
  ]),
  listFilter('list-filter', [
    ('path', <String, String>{'d': 'M2 5h20'}),
    ('path', <String, String>{'d': 'M6 12h12'}),
    ('path', <String, String>{'d': 'M9 19h6'}),
  ]),
  listTree('list-tree', [
    ('path', <String, String>{'d': 'M8 5h13'}),
    ('path', <String, String>{'d': 'M13 12h8'}),
    ('path', <String, String>{'d': 'M13 19h8'}),
    ('path', <String, String>{'d': 'M3 10a2 2 0 0 0 2 2h3'}),
    ('path', <String, String>{'d': 'M3 5v12a2 2 0 0 0 2 2h3'}),
  ]),
  loaderCircle('loader-circle', [
    ('path', <String, String>{'d': 'M21 12a9 9 0 1 1-6.219-8.56'}),
  ]),
  lock('lock', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '11',
        'x': '3',
        'y': '11',
        'rx': '2',
        'ry': '2',
      },
    ),
    ('path', <String, String>{'d': 'M7 11V7a5 5 0 0 1 10 0v4'}),
  ]),
  logOut('log-out', [
    ('path', <String, String>{'d': 'm16 17 5-5-5-5'}),
    ('path', <String, String>{'d': 'M21 12H9'}),
    ('path', <String, String>{'d': 'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4'}),
  ]),
  maximize2('maximize-2', [
    ('path', <String, String>{'d': 'M15 3h6v6'}),
    ('path', <String, String>{'d': 'm21 3-7 7'}),
    ('path', <String, String>{'d': 'm3 21 7-7'}),
    ('path', <String, String>{'d': 'M9 21H3v-6'}),
  ]),
  messageSquare('message-square', [
    (
      'path',
      <String, String>{
        'd': 'M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z',
      },
    ),
  ]),
  messageSquarePlus('message-square-plus', [
    (
      'path',
      <String, String>{
        'd': 'M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z',
      },
    ),
    ('path', <String, String>{'d': 'M12 8v6'}),
    ('path', <String, String>{'d': 'M9 11h6'}),
  ]),
  messagesSquare('messages-square', [
    (
      'path',
      <String, String>{
        'd': 'M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1',
      },
    ),
  ]),
  mic('mic', [
    ('path', <String, String>{'d': 'M12 19v3'}),
    ('path', <String, String>{'d': 'M19 10v2a7 7 0 0 1-14 0v-2'}),
    (
      'rect',
      <String, String>{
        'x': '9',
        'y': '2',
        'width': '6',
        'height': '13',
        'rx': '3',
      },
    ),
  ]),
  micOff('mic-off', [
    ('path', <String, String>{'d': 'M12 19v3'}),
    ('path', <String, String>{'d': 'M15 9.34V5a3 3 0 0 0-5.68-1.33'}),
    ('path', <String, String>{'d': 'M16.95 16.95A7 7 0 0 1 5 12v-2'}),
    ('path', <String, String>{'d': 'M18.89 13.23A7 7 0 0 0 19 12v-2'}),
    ('path', <String, String>{'d': 'm2 2 20 20'}),
    ('path', <String, String>{'d': 'M9 9v3a3 3 0 0 0 5.12 2.12'}),
  ]),
  minimize2('minimize-2', [
    ('path', <String, String>{'d': 'm14 10 7-7'}),
    ('path', <String, String>{'d': 'M20 10h-6V4'}),
    ('path', <String, String>{'d': 'm3 21 7-7'}),
    ('path', <String, String>{'d': 'M4 14h6v6'}),
  ]),
  minus('minus', [
    ('path', <String, String>{'d': 'M5 12h14'}),
  ]),
  monitor('monitor', [
    (
      'rect',
      <String, String>{
        'width': '20',
        'height': '14',
        'x': '2',
        'y': '3',
        'rx': '2',
      },
    ),
    ('line', <String, String>{'x1': '8', 'x2': '16', 'y1': '21', 'y2': '21'}),
    ('line', <String, String>{'x1': '12', 'x2': '12', 'y1': '17', 'y2': '21'}),
  ]),
  moon('moon', [
    (
      'path',
      <String, String>{
        'd': 'M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401',
      },
    ),
  ]),
  network('network', [
    (
      'rect',
      <String, String>{
        'x': '16',
        'y': '16',
        'width': '6',
        'height': '6',
        'rx': '1',
      },
    ),
    (
      'rect',
      <String, String>{
        'x': '2',
        'y': '16',
        'width': '6',
        'height': '6',
        'rx': '1',
      },
    ),
    (
      'rect',
      <String, String>{
        'x': '9',
        'y': '2',
        'width': '6',
        'height': '6',
        'rx': '1',
      },
    ),
    (
      'path',
      <String, String>{'d': 'M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3'},
    ),
    ('path', <String, String>{'d': 'M12 12V8'}),
  ]),
  notebookPen('notebook-pen', [
    (
      'path',
      <String, String>{
        'd': 'M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4',
      },
    ),
    ('path', <String, String>{'d': 'M2 6h4'}),
    ('path', <String, String>{'d': 'M2 10h4'}),
    ('path', <String, String>{'d': 'M2 14h4'}),
    ('path', <String, String>{'d': 'M2 18h4'}),
    (
      'path',
      <String, String>{
        'd': 'M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z',
      },
    ),
  ]),
  panelBottom('panel-bottom', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
      },
    ),
    ('path', <String, String>{'d': 'M3 15h18'}),
  ]),
  panelLeft('panel-left', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
      },
    ),
    ('path', <String, String>{'d': 'M9 3v18'}),
  ]),
  panelRight('panel-right', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
      },
    ),
    ('path', <String, String>{'d': 'M15 3v18'}),
  ]),
  paperclip('paperclip', [
    (
      'path',
      <String, String>{
        'd': 'm16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551',
      },
    ),
  ]),
  pause('pause', [
    (
      'rect',
      <String, String>{
        'x': '14',
        'y': '3',
        'width': '5',
        'height': '18',
        'rx': '1',
      },
    ),
    (
      'rect',
      <String, String>{
        'x': '5',
        'y': '3',
        'width': '5',
        'height': '18',
        'rx': '1',
      },
    ),
  ]),
  pencil('pencil', [
    (
      'path',
      <String, String>{
        'd': 'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
      },
    ),
    ('path', <String, String>{'d': 'm15 5 4 4'}),
  ]),
  phone('phone', [
    (
      'path',
      <String, String>{
        'd': 'M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384',
      },
    ),
  ]),
  phoneOff('phone-off', [
    (
      'path',
      <String, String>{
        'd': 'M10.1 13.9a14 14 0 0 0 3.732 2.668 1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2 18 18 0 0 1-12.728-5.272',
      },
    ),
    ('path', <String, String>{'d': 'M22 2 2 22'}),
    (
      'path',
      <String, String>{
        'd': 'M4.76 13.582A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 .244.473',
      },
    ),
  ]),
  pin('pin', [
    ('path', <String, String>{'d': 'M12 17v5'}),
    (
      'path',
      <String, String>{
        'd': 'M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z',
      },
    ),
  ]),
  pinOff('pin-off', [
    ('path', <String, String>{'d': 'M12 17v5'}),
    (
      'path',
      <String, String>{'d': 'M15 9.34V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H7.89'},
    ),
    ('path', <String, String>{'d': 'm2 2 20 20'}),
    (
      'path',
      <String, String>{
        'd': 'M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11',
      },
    ),
  ]),
  play('play', [
    (
      'path',
      <String, String>{
        'd': 'M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z',
      },
    ),
  ]),
  plug('plug', [
    ('path', <String, String>{'d': 'M12 22v-5'}),
    ('path', <String, String>{'d': 'M15 8V2'}),
    (
      'path',
      <String, String>{
        'd': 'M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z',
      },
    ),
    ('path', <String, String>{'d': 'M9 8V2'}),
  ]),
  plus('plus', [
    ('path', <String, String>{'d': 'M5 12h14'}),
    ('path', <String, String>{'d': 'M12 5v14'}),
  ]),
  power('power', [
    ('path', <String, String>{'d': 'M12 2v10'}),
    ('path', <String, String>{'d': 'M18.4 6.6a9 9 0 1 1-12.77.04'}),
  ]),
  quote('quote', [
    (
      'path',
      <String, String>{
        'd': 'M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z',
      },
    ),
  ]),
  radio('radio', [
    ('path', <String, String>{'d': 'M16.247 7.761a6 6 0 0 1 0 8.478'}),
    ('path', <String, String>{'d': 'M19.075 4.933a10 10 0 0 1 0 14.134'}),
    ('path', <String, String>{'d': 'M4.925 19.067a10 10 0 0 1 0-14.134'}),
    ('path', <String, String>{'d': 'M7.753 16.239a6 6 0 0 1 0-8.478'}),
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '2'}),
  ]),
  redo2('redo-2', [
    ('path', <String, String>{'d': 'm15 14 5-5-5-5'}),
    (
      'path',
      <String, String>{
        'd': 'M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13',
      },
    ),
  ]),
  refreshCw('refresh-cw', [
    (
      'path',
      <String, String>{
        'd': 'M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8',
      },
    ),
    ('path', <String, String>{'d': 'M21 3v5h-5'}),
    (
      'path',
      <String, String>{
        'd': 'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16',
      },
    ),
    ('path', <String, String>{'d': 'M8 16H3v5'}),
  ]),
  rotateCcw('rotate-ccw', [
    (
      'path',
      <String, String>{
        'd': 'M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8',
      },
    ),
    ('path', <String, String>{'d': 'M3 3v5h5'}),
  ]),
  rss('rss', [
    ('path', <String, String>{'d': 'M4 11a9 9 0 0 1 9 9'}),
    ('path', <String, String>{'d': 'M4 4a16 16 0 0 1 16 16'}),
    ('circle', <String, String>{'cx': '5', 'cy': '19', 'r': '1'}),
  ]),
  save('save', [
    (
      'path',
      <String, String>{
        'd': 'M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z',
      },
    ),
    (
      'path',
      <String, String>{'d': 'M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7'},
    ),
    ('path', <String, String>{'d': 'M7 3v4a1 1 0 0 0 1 1h7'}),
  ]),
  scrollText('scroll-text', [
    ('path', <String, String>{'d': 'M15 12h-5'}),
    ('path', <String, String>{'d': 'M15 8h-5'}),
    ('path', <String, String>{'d': 'M19 17V5a2 2 0 0 0-2-2H4'}),
    (
      'path',
      <String, String>{
        'd': 'M8 21h12a2 2 0 0 0 2-2v-1a1 1 0 0 0-1-1H11a1 1 0 0 0-1 1v1a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v2a1 1 0 0 0 1 1h3',
      },
    ),
  ]),
  search('search', [
    ('path', <String, String>{'d': 'm21 21-4.34-4.34'}),
    ('circle', <String, String>{'cx': '11', 'cy': '11', 'r': '8'}),
  ]),
  send('send', [
    (
      'path',
      <String, String>{
        'd': 'M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z',
      },
    ),
    ('path', <String, String>{'d': 'm21.854 2.147-10.94 10.939'}),
  ]),
  server('server', [
    (
      'rect',
      <String, String>{
        'width': '20',
        'height': '8',
        'x': '2',
        'y': '2',
        'rx': '2',
        'ry': '2',
      },
    ),
    (
      'rect',
      <String, String>{
        'width': '20',
        'height': '8',
        'x': '2',
        'y': '14',
        'rx': '2',
        'ry': '2',
      },
    ),
    ('line', <String, String>{'x1': '6', 'x2': '6.01', 'y1': '6', 'y2': '6'}),
    ('line', <String, String>{'x1': '6', 'x2': '6.01', 'y1': '18', 'y2': '18'}),
  ]),
  settings('settings', [
    (
      'path',
      <String, String>{
        'd': 'M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915',
      },
    ),
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '3'}),
  ]),
  share2('share-2', [
    ('circle', <String, String>{'cx': '18', 'cy': '5', 'r': '3'}),
    ('circle', <String, String>{'cx': '6', 'cy': '12', 'r': '3'}),
    ('circle', <String, String>{'cx': '18', 'cy': '19', 'r': '3'}),
    (
      'line',
      <String, String>{
        'x1': '8.59',
        'x2': '15.42',
        'y1': '13.51',
        'y2': '17.49',
      },
    ),
    (
      'line',
      <String, String>{
        'x1': '15.41',
        'x2': '8.59',
        'y1': '6.51',
        'y2': '10.49',
      },
    ),
  ]),
  shieldCheck('shield-check', [
    (
      'path',
      <String, String>{
        'd': 'M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z',
      },
    ),
    ('path', <String, String>{'d': 'm9 12 2 2 4-4'}),
  ]),
  slidersHorizontal('sliders-horizontal', [
    ('path', <String, String>{'d': 'M10 5H3'}),
    ('path', <String, String>{'d': 'M12 19H3'}),
    ('path', <String, String>{'d': 'M14 3v4'}),
    ('path', <String, String>{'d': 'M16 17v4'}),
    ('path', <String, String>{'d': 'M21 12h-9'}),
    ('path', <String, String>{'d': 'M21 19h-5'}),
    ('path', <String, String>{'d': 'M21 5h-7'}),
    ('path', <String, String>{'d': 'M8 10v4'}),
    ('path', <String, String>{'d': 'M8 12H3'}),
  ]),
  sparkles('sparkles', [
    (
      'path',
      <String, String>{
        'd': 'M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z',
      },
    ),
    ('path', <String, String>{'d': 'M20 2v4'}),
    ('path', <String, String>{'d': 'M22 4h-4'}),
    ('circle', <String, String>{'cx': '4', 'cy': '20', 'r': '2'}),
  ]),
  square('square', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
      },
    ),
  ]),
  squarePen('square-pen', [
    (
      'path',
      <String, String>{
        'd': 'M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7',
      },
    ),
    (
      'path',
      <String, String>{
        'd': 'M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z',
      },
    ),
  ]),
  squareStop('square-stop', [
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
      },
    ),
    (
      'rect',
      <String, String>{
        'x': '9',
        'y': '9',
        'width': '6',
        'height': '6',
        'rx': '1',
      },
    ),
  ]),
  squareTerminal('square-terminal', [
    ('path', <String, String>{'d': 'm7 11 2-2-2-2'}),
    ('path', <String, String>{'d': 'M11 13h4'}),
    (
      'rect',
      <String, String>{
        'width': '18',
        'height': '18',
        'x': '3',
        'y': '3',
        'rx': '2',
        'ry': '2',
      },
    ),
  ]),
  star('star', [
    (
      'path',
      <String, String>{
        'd': 'M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z',
      },
    ),
  ]),
  stickyNote('sticky-note', [
    (
      'path',
      <String, String>{
        'd': 'M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z',
      },
    ),
    ('path', <String, String>{'d': 'M15 3v5a1 1 0 0 0 1 1h5'}),
  ]),
  sun('sun', [
    ('circle', <String, String>{'cx': '12', 'cy': '12', 'r': '4'}),
    ('path', <String, String>{'d': 'M12 2v2'}),
    ('path', <String, String>{'d': 'M12 20v2'}),
    ('path', <String, String>{'d': 'm4.93 4.93 1.41 1.41'}),
    ('path', <String, String>{'d': 'm17.66 17.66 1.41 1.41'}),
    ('path', <String, String>{'d': 'M2 12h2'}),
    ('path', <String, String>{'d': 'M20 12h2'}),
    ('path', <String, String>{'d': 'm6.34 17.66-1.41 1.41'}),
    ('path', <String, String>{'d': 'm19.07 4.93-1.41 1.41'}),
  ]),
  tag('tag', [
    (
      'path',
      <String, String>{
        'd': 'M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z',
      },
    ),
    (
      'circle',
      <String, String>{
        'cx': '7.5',
        'cy': '7.5',
        'r': '.5',
        'fill': 'currentColor',
      },
    ),
  ]),
  terminal('terminal', [
    ('path', <String, String>{'d': 'M12 19h8'}),
    ('path', <String, String>{'d': 'm4 17 6-6-6-6'}),
  ]),
  thumbsDown('thumbs-down', [
    (
      'path',
      <String, String>{
        'd': 'M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z',
      },
    ),
    ('path', <String, String>{'d': 'M17 14V2'}),
  ]),
  thumbsUp('thumbs-up', [
    (
      'path',
      <String, String>{
        'd': 'M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z',
      },
    ),
    ('path', <String, String>{'d': 'M7 10v12'}),
  ]),
  trash('trash', [
    ('path', <String, String>{'d': 'M10 11v6'}),
    ('path', <String, String>{'d': 'M14 11v6'}),
    ('path', <String, String>{'d': 'M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6'}),
    ('path', <String, String>{'d': 'M3 6h18'}),
    ('path', <String, String>{'d': 'M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2'}),
  ]),
  triangleAlert('triangle-alert', [
    (
      'path',
      <String, String>{
        'd': 'm21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3',
      },
    ),
    ('path', <String, String>{'d': 'M12 9v4'}),
    ('path', <String, String>{'d': 'M12 17h.01'}),
  ]),
  undo2('undo-2', [
    ('path', <String, String>{'d': 'M9 14 4 9l5-5'}),
    (
      'path',
      <String, String>{
        'd': 'M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11',
      },
    ),
  ]),
  upload('upload', [
    ('path', <String, String>{'d': 'M12 3v12'}),
    ('path', <String, String>{'d': 'm17 8-5-5-5 5'}),
    (
      'path',
      <String, String>{'d': 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4'},
    ),
  ]),
  user('user', [
    (
      'path',
      <String, String>{'d': 'M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2'},
    ),
    ('circle', <String, String>{'cx': '12', 'cy': '7', 'r': '4'}),
  ]),
  users('users', [
    (
      'path',
      <String, String>{'d': 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2'},
    ),
    ('path', <String, String>{'d': 'M16 3.128a4 4 0 0 1 0 7.744'}),
    ('path', <String, String>{'d': 'M22 21v-2a4 4 0 0 0-3-3.87'}),
    ('circle', <String, String>{'cx': '9', 'cy': '7', 'r': '4'}),
  ]),
  volume2('volume-2', [
    (
      'path',
      <String, String>{
        'd': 'M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z',
      },
    ),
    ('path', <String, String>{'d': 'M16 9a5 5 0 0 1 0 6'}),
    ('path', <String, String>{'d': 'M19.364 18.364a9 9 0 0 0 0-12.728'}),
  ]),
  volumeX('volume-x', [
    (
      'path',
      <String, String>{
        'd': 'M11 4.702a.7.7 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.7.7 0 0 0 11 19.298z',
      },
    ),
    ('path', <String, String>{'d': 'm16.5 14.5 5-5'}),
    ('path', <String, String>{'d': 'm16.5 9.5 5 5'}),
  ]),
  wifiOff('wifi-off', [
    ('path', <String, String>{'d': 'M12 20h.01'}),
    ('path', <String, String>{'d': 'M8.5 16.429a5 5 0 0 1 7 0'}),
    ('path', <String, String>{'d': 'M5 12.859a10 10 0 0 1 5.17-2.69'}),
    ('path', <String, String>{'d': 'M19 12.859a10 10 0 0 0-2.007-1.523'}),
    ('path', <String, String>{'d': 'M2 8.82a15 15 0 0 1 4.177-2.643'}),
    ('path', <String, String>{'d': 'M22 8.82a15 15 0 0 0-11.288-3.764'}),
    ('path', <String, String>{'d': 'm2 2 20 20'}),
  ]),
  wrench('wrench', [
    (
      'path',
      <String, String>{
        'd': 'M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z',
      },
    ),
  ]),
  x('x', [
    ('path', <String, String>{'d': 'M18 6 6 18'}),
    ('path', <String, String>{'d': 'm6 6 12 12'}),
  ]),
  zap('zap', [
    (
      'path',
      <String, String>{
        'd': 'M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z',
      },
    ),
  ]);

  const LucideIcon(this.lucideName, this.nodes);

  /// The icon's name on lucide.dev.
  final String lucideName;

  final List<(String, Map<String, String>)> nodes;
}
