// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -415713412;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__runtime__ack_auth_mutation_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ack_auth_mutation",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_mutation_id = <String>::sse_decode(&mut deserializer);
            let api_persisted = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok =
                            crate::api::runtime::ack_auth_mutation(api_mutation_id, api_persisted)
                                .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__auth_state_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "auth_state",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::auth_state().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__begin_device_code_login_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "begin_device_code_login",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::begin_device_code_login().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__bridge_protocol_version_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "bridge_protocol_version",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::runtime::bridge_protocol_version())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__runtime__cancel_device_code_login_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_device_code_login",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::cancel_device_code_login().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__disconnect_account_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "disconnect_account",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::disconnect_account().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::runtime::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__runtime__initialize_runtime_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize_runtime",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_client_epoch = <u64>::sse_decode(&mut deserializer);
            let api_auth_snapshot = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::initialize_runtime(
                            api_client_epoch,
                            api_auth_snapshot,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__interrupt_turn_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "interrupt_turn",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_run_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::interrupt_turn(api_run_id).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__list_models_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_models",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::list_models().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__runtime_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "runtime_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_client_epoch = <u64>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::contract::RuntimeEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok =
                            crate::api::runtime::runtime_events(api_client_epoch, api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__shutdown_runtime_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "shutdown_runtime",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::shutdown_runtime().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__runtime__start_turn_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_turn",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::contract::TurnRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::contract::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::runtime::start_turn(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::contract::RuntimeEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::contract::AuthStateInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_authenticated = <bool>::sse_decode(deserializer);
        let mut var_email = <Option<String>>::sse_decode(deserializer);
        let mut var_planType = <Option<String>>::sse_decode(deserializer);
        let mut var_accountId = <Option<String>>::sse_decode(deserializer);
        let mut var_accountFingerprint = <Option<String>>::sse_decode(deserializer);
        return crate::api::contract::AuthStateInfo {
            authenticated: var_authenticated,
            email: var_email,
            plan_type: var_planType,
            account_id: var_accountId,
            account_fingerprint: var_accountFingerprint,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::contract::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::contract::BridgeErrorKind>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_retryAfterSeconds = <Option<u32>>::sse_decode(deserializer);
        return crate::api::contract::BridgeError {
            kind: var_kind,
            message: var_message,
            retry_after_seconds: var_retryAfterSeconds,
        };
    }
}

impl SseDecode for crate::api::contract::BridgeErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::contract::BridgeErrorKind::InvalidInput,
            1 => crate::api::contract::BridgeErrorKind::Authentication,
            2 => crate::api::contract::BridgeErrorKind::Network,
            3 => crate::api::contract::BridgeErrorKind::RateLimit,
            4 => crate::api::contract::BridgeErrorKind::Unsupported,
            5 => crate::api::contract::BridgeErrorKind::Cancellation,
            6 => crate::api::contract::BridgeErrorKind::ProtocolMismatch,
            7 => crate::api::contract::BridgeErrorKind::Internal,
            _ => unreachable!("Invalid variant for BridgeErrorKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::contract::DeviceCodeChallenge {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_loginId = <String>::sse_decode(deserializer);
        let mut var_verificationUrl = <String>::sse_decode(deserializer);
        let mut var_userCode = <String>::sse_decode(deserializer);
        return crate::api::contract::DeviceCodeChallenge {
            login_id: var_loginId,
            verification_url: var_verificationUrl,
            user_code: var_userCode,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::contract::ModelInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::contract::ModelInfo>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::contract::TurnInputPart> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::contract::TurnInputPart>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::contract::TurnMessage> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::contract::TurnMessage>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::contract::ModelInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_supportsImages = <bool>::sse_decode(deserializer);
        let mut var_supportsAudio = <bool>::sse_decode(deserializer);
        let mut var_supportedReasoningEfforts = <Vec<String>>::sse_decode(deserializer);
        let mut var_defaultReasoningEffort = <Option<String>>::sse_decode(deserializer);
        return crate::api::contract::ModelInfo {
            id: var_id,
            display_name: var_displayName,
            description: var_description,
            supports_images: var_supportsImages,
            supports_audio: var_supportsAudio,
            supported_reasoning_efforts: var_supportedReasoningEfforts,
            default_reasoning_effort: var_defaultReasoningEffort,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::contract::RunInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_runId = <String>::sse_decode(deserializer);
        let mut var_sessionId = <String>::sse_decode(deserializer);
        return crate::api::contract::RunInfo {
            run_id: var_runId,
            session_id: var_sessionId,
        };
    }
}

impl SseDecode for crate::api::contract::RuntimeEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_clientEpoch = <u64>::sse_decode(deserializer);
        let mut var_sequence = <u64>::sse_decode(deserializer);
        let mut var_kind = <crate::api::contract::RuntimeEventKind>::sse_decode(deserializer);
        let mut var_runId = <Option<String>>::sse_decode(deserializer);
        let mut var_sessionId = <Option<String>>::sse_decode(deserializer);
        let mut var_itemId = <Option<String>>::sse_decode(deserializer);
        let mut var_text = <Option<String>>::sse_decode(deserializer);
        let mut var_jsonData = <Option<String>>::sse_decode(deserializer);
        let mut var_binaryData = <Option<Vec<u8>>>::sse_decode(deserializer);
        return crate::api::contract::RuntimeEvent {
            client_epoch: var_clientEpoch,
            sequence: var_sequence,
            kind: var_kind,
            run_id: var_runId,
            session_id: var_sessionId,
            item_id: var_itemId,
            text: var_text,
            json_data: var_jsonData,
            binary_data: var_binaryData,
        };
    }
}

impl SseDecode for crate::api::contract::RuntimeEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::contract::RuntimeEventKind::AuthState,
            1 => crate::api::contract::RuntimeEventKind::AuthMutationRequired,
            2 => crate::api::contract::RuntimeEventKind::LoginCompleted,
            3 => crate::api::contract::RuntimeEventKind::TurnStarted,
            4 => crate::api::contract::RuntimeEventKind::TextDelta,
            5 => crate::api::contract::RuntimeEventKind::ReasoningDelta,
            6 => crate::api::contract::RuntimeEventKind::Source,
            7 => crate::api::contract::RuntimeEventKind::GeneratedImage,
            8 => crate::api::contract::RuntimeEventKind::Usage,
            9 => crate::api::contract::RuntimeEventKind::CheckpointUpdated,
            10 => crate::api::contract::RuntimeEventKind::Cancelled,
            11 => crate::api::contract::RuntimeEventKind::Completed,
            12 => crate::api::contract::RuntimeEventKind::Failure,
            13 => crate::api::contract::RuntimeEventKind::Diagnostic,
            _ => unreachable!("Invalid variant for RuntimeEventKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::contract::TurnInputPart {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_text = <Option<String>>::sse_decode(deserializer);
        let mut var_filename = <Option<String>>::sse_decode(deserializer);
        let mut var_mimeType = <Option<String>>::sse_decode(deserializer);
        let mut var_bytes = <Option<Vec<u8>>>::sse_decode(deserializer);
        return crate::api::contract::TurnInputPart {
            kind: var_kind,
            text: var_text,
            filename: var_filename,
            mime_type: var_mimeType,
            bytes: var_bytes,
        };
    }
}

impl SseDecode for crate::api::contract::TurnMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_role = <crate::api::contract::TurnMessageRole>::sse_decode(deserializer);
        let mut var_messageId = <Option<String>>::sse_decode(deserializer);
        let mut var_parts = <Vec<crate::api::contract::TurnInputPart>>::sse_decode(deserializer);
        return crate::api::contract::TurnMessage {
            role: var_role,
            message_id: var_messageId,
            parts: var_parts,
        };
    }
}

impl SseDecode for crate::api::contract::TurnMessageRole {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::contract::TurnMessageRole::System,
            1 => crate::api::contract::TurnMessageRole::User,
            2 => crate::api::contract::TurnMessageRole::Assistant,
            _ => unreachable!("Invalid variant for TurnMessageRole: {}", inner),
        };
    }
}

impl SseDecode for crate::api::contract::TurnRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_modelId = <String>::sse_decode(deserializer);
        let mut var_reasoningEffort = <Option<String>>::sse_decode(deserializer);
        let mut var_enableWebSearch = <bool>::sse_decode(deserializer);
        let mut var_enableImageGeneration = <bool>::sse_decode(deserializer);
        let mut var_messages = <Vec<crate::api::contract::TurnMessage>>::sse_decode(deserializer);
        let mut var_checkpoint = <Option<Vec<u8>>>::sse_decode(deserializer);
        let mut var_previousInputTokens = <Option<u64>>::sse_decode(deserializer);
        return crate::api::contract::TurnRequest {
            session_id: var_sessionId,
            model_id: var_modelId,
            reasoning_effort: var_reasoningEffort,
            enable_web_search: var_enableWebSearch,
            enable_image_generation: var_enableImageGeneration,
            messages: var_messages,
            checkpoint: var_checkpoint,
            previous_input_tokens: var_previousInputTokens,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__runtime__ack_auth_mutation_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__runtime__auth_state_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__runtime__begin_device_code_login_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__runtime__bridge_protocol_version_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__runtime__cancel_device_code_login_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__runtime__disconnect_account_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__runtime__init_app_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__runtime__initialize_runtime_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__runtime__interrupt_turn_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__runtime__list_models_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__runtime__runtime_events_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__runtime__shutdown_runtime_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__runtime__start_turn_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::AuthStateInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.authenticated.into_into_dart().into_dart(),
            self.email.into_into_dart().into_dart(),
            self.plan_type.into_into_dart().into_dart(),
            self.account_id.into_into_dart().into_dart(),
            self.account_fingerprint.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::AuthStateInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::AuthStateInfo>
    for crate::api::contract::AuthStateInfo
{
    fn into_into_dart(self) -> crate::api::contract::AuthStateInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::BridgeError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.retry_after_seconds.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::BridgeError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::BridgeError>
    for crate::api::contract::BridgeError
{
    fn into_into_dart(self) -> crate::api::contract::BridgeError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::BridgeErrorKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidInput => 0.into_dart(),
            Self::Authentication => 1.into_dart(),
            Self::Network => 2.into_dart(),
            Self::RateLimit => 3.into_dart(),
            Self::Unsupported => 4.into_dart(),
            Self::Cancellation => 5.into_dart(),
            Self::ProtocolMismatch => 6.into_dart(),
            Self::Internal => 7.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::BridgeErrorKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::BridgeErrorKind>
    for crate::api::contract::BridgeErrorKind
{
    fn into_into_dart(self) -> crate::api::contract::BridgeErrorKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::DeviceCodeChallenge {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.login_id.into_into_dart().into_dart(),
            self.verification_url.into_into_dart().into_dart(),
            self.user_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::DeviceCodeChallenge
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::DeviceCodeChallenge>
    for crate::api::contract::DeviceCodeChallenge
{
    fn into_into_dart(self) -> crate::api::contract::DeviceCodeChallenge {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::ModelInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.supports_images.into_into_dart().into_dart(),
            self.supports_audio.into_into_dart().into_dart(),
            self.supported_reasoning_efforts
                .into_into_dart()
                .into_dart(),
            self.default_reasoning_effort.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::ModelInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::ModelInfo>
    for crate::api::contract::ModelInfo
{
    fn into_into_dart(self) -> crate::api::contract::ModelInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::RunInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.run_id.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::contract::RunInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::RunInfo>
    for crate::api::contract::RunInfo
{
    fn into_into_dart(self) -> crate::api::contract::RunInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::RuntimeEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.client_epoch.into_into_dart().into_dart(),
            self.sequence.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.run_id.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
            self.item_id.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.json_data.into_into_dart().into_dart(),
            self.binary_data.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::RuntimeEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::RuntimeEvent>
    for crate::api::contract::RuntimeEvent
{
    fn into_into_dart(self) -> crate::api::contract::RuntimeEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::RuntimeEventKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::AuthState => 0.into_dart(),
            Self::AuthMutationRequired => 1.into_dart(),
            Self::LoginCompleted => 2.into_dart(),
            Self::TurnStarted => 3.into_dart(),
            Self::TextDelta => 4.into_dart(),
            Self::ReasoningDelta => 5.into_dart(),
            Self::Source => 6.into_dart(),
            Self::GeneratedImage => 7.into_dart(),
            Self::Usage => 8.into_dart(),
            Self::CheckpointUpdated => 9.into_dart(),
            Self::Cancelled => 10.into_dart(),
            Self::Completed => 11.into_dart(),
            Self::Failure => 12.into_dart(),
            Self::Diagnostic => 13.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::RuntimeEventKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::RuntimeEventKind>
    for crate::api::contract::RuntimeEventKind
{
    fn into_into_dart(self) -> crate::api::contract::RuntimeEventKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::TurnInputPart {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.filename.into_into_dart().into_dart(),
            self.mime_type.into_into_dart().into_dart(),
            self.bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::TurnInputPart
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::TurnInputPart>
    for crate::api::contract::TurnInputPart
{
    fn into_into_dart(self) -> crate::api::contract::TurnInputPart {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::TurnMessage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.role.into_into_dart().into_dart(),
            self.message_id.into_into_dart().into_dart(),
            self.parts.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::TurnMessage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::TurnMessage>
    for crate::api::contract::TurnMessage
{
    fn into_into_dart(self) -> crate::api::contract::TurnMessage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::TurnMessageRole {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::System => 0.into_dart(),
            Self::User => 1.into_dart(),
            Self::Assistant => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::TurnMessageRole
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::TurnMessageRole>
    for crate::api::contract::TurnMessageRole
{
    fn into_into_dart(self) -> crate::api::contract::TurnMessageRole {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contract::TurnRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.model_id.into_into_dart().into_dart(),
            self.reasoning_effort.into_into_dart().into_dart(),
            self.enable_web_search.into_into_dart().into_dart(),
            self.enable_image_generation.into_into_dart().into_dart(),
            self.messages.into_into_dart().into_dart(),
            self.checkpoint.into_into_dart().into_dart(),
            self.previous_input_tokens.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contract::TurnRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contract::TurnRequest>
    for crate::api::contract::TurnRequest
{
    fn into_into_dart(self) -> crate::api::contract::TurnRequest {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::contract::RuntimeEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::contract::AuthStateInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.authenticated, serializer);
        <Option<String>>::sse_encode(self.email, serializer);
        <Option<String>>::sse_encode(self.plan_type, serializer);
        <Option<String>>::sse_encode(self.account_id, serializer);
        <Option<String>>::sse_encode(self.account_fingerprint, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::contract::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::contract::BridgeErrorKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.message, serializer);
        <Option<u32>>::sse_encode(self.retry_after_seconds, serializer);
    }
}

impl SseEncode for crate::api::contract::BridgeErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::contract::BridgeErrorKind::InvalidInput => 0,
                crate::api::contract::BridgeErrorKind::Authentication => 1,
                crate::api::contract::BridgeErrorKind::Network => 2,
                crate::api::contract::BridgeErrorKind::RateLimit => 3,
                crate::api::contract::BridgeErrorKind::Unsupported => 4,
                crate::api::contract::BridgeErrorKind::Cancellation => 5,
                crate::api::contract::BridgeErrorKind::ProtocolMismatch => 6,
                crate::api::contract::BridgeErrorKind::Internal => 7,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::contract::DeviceCodeChallenge {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.login_id, serializer);
        <String>::sse_encode(self.verification_url, serializer);
        <String>::sse_encode(self.user_code, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::contract::ModelInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::contract::ModelInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::contract::TurnInputPart> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::contract::TurnInputPart>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::contract::TurnMessage> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::contract::TurnMessage>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::contract::ModelInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <String>::sse_encode(self.description, serializer);
        <bool>::sse_encode(self.supports_images, serializer);
        <bool>::sse_encode(self.supports_audio, serializer);
        <Vec<String>>::sse_encode(self.supported_reasoning_efforts, serializer);
        <Option<String>>::sse_encode(self.default_reasoning_effort, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::contract::RunInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.run_id, serializer);
        <String>::sse_encode(self.session_id, serializer);
    }
}

impl SseEncode for crate::api::contract::RuntimeEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.client_epoch, serializer);
        <u64>::sse_encode(self.sequence, serializer);
        <crate::api::contract::RuntimeEventKind>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.run_id, serializer);
        <Option<String>>::sse_encode(self.session_id, serializer);
        <Option<String>>::sse_encode(self.item_id, serializer);
        <Option<String>>::sse_encode(self.text, serializer);
        <Option<String>>::sse_encode(self.json_data, serializer);
        <Option<Vec<u8>>>::sse_encode(self.binary_data, serializer);
    }
}

impl SseEncode for crate::api::contract::RuntimeEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::contract::RuntimeEventKind::AuthState => 0,
                crate::api::contract::RuntimeEventKind::AuthMutationRequired => 1,
                crate::api::contract::RuntimeEventKind::LoginCompleted => 2,
                crate::api::contract::RuntimeEventKind::TurnStarted => 3,
                crate::api::contract::RuntimeEventKind::TextDelta => 4,
                crate::api::contract::RuntimeEventKind::ReasoningDelta => 5,
                crate::api::contract::RuntimeEventKind::Source => 6,
                crate::api::contract::RuntimeEventKind::GeneratedImage => 7,
                crate::api::contract::RuntimeEventKind::Usage => 8,
                crate::api::contract::RuntimeEventKind::CheckpointUpdated => 9,
                crate::api::contract::RuntimeEventKind::Cancelled => 10,
                crate::api::contract::RuntimeEventKind::Completed => 11,
                crate::api::contract::RuntimeEventKind::Failure => 12,
                crate::api::contract::RuntimeEventKind::Diagnostic => 13,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::contract::TurnInputPart {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.text, serializer);
        <Option<String>>::sse_encode(self.filename, serializer);
        <Option<String>>::sse_encode(self.mime_type, serializer);
        <Option<Vec<u8>>>::sse_encode(self.bytes, serializer);
    }
}

impl SseEncode for crate::api::contract::TurnMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::contract::TurnMessageRole>::sse_encode(self.role, serializer);
        <Option<String>>::sse_encode(self.message_id, serializer);
        <Vec<crate::api::contract::TurnInputPart>>::sse_encode(self.parts, serializer);
    }
}

impl SseEncode for crate::api::contract::TurnMessageRole {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::contract::TurnMessageRole::System => 0,
                crate::api::contract::TurnMessageRole::User => 1,
                crate::api::contract::TurnMessageRole::Assistant => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::contract::TurnRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.model_id, serializer);
        <Option<String>>::sse_encode(self.reasoning_effort, serializer);
        <bool>::sse_encode(self.enable_web_search, serializer);
        <bool>::sse_encode(self.enable_image_generation, serializer);
        <Vec<crate::api::contract::TurnMessage>>::sse_encode(self.messages, serializer);
        <Option<Vec<u8>>>::sse_encode(self.checkpoint, serializer);
        <Option<u64>>::sse_encode(self.previous_input_tokens, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
