#!/usr/bin/env python3
"""Builds the single-file Open WebUI "Conduit Push" function.

Open WebUI imports a function as one Python file, so the shared Web Push
library (server-plugins/common/conduit_webpush) is inlined into the template,
verbatim, as source strings that the function loads into private modules.

    python server-plugins/openwebui/build.py          # write both outputs
    python server-plugins/openwebui/build.py --check  # exit 1 if either is stale
"""

import argparse
import ast
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
TEMPLATE = HERE / "conduit_push.template.py"
LIBRARY = ROOT / "server-plugins" / "common" / "conduit_webpush"
MODULES = ("webpush", "payload")
OUTPUTS = (
    HERE / "conduit_push.py",
    # Bundled by the app for one-tap install.
    ROOT / "assets" / "server_plugins" / "openwebui_conduit_push.py",
)
BEGIN = "# >>> conduit_webpush"
END = "# <<< conduit_webpush"
SOURCES_NAME = "_CONDUIT_WEBPUSH_SOURCES"
# Open WebUI's replace_imports() rewrites these substrings anywhere in a
# function's source, comments and strings included, so none may appear.
REWRITTEN_BY_OPEN_WEBUI = ("from utils", "from apps", "from main", "from config")
REQUIRED_FRONTMATTER = ("title", "version", "required_open_webui_version", "conduit_protocol")


class BuildError(Exception):
    pass


def frontmatter(source):
    """Mirrors open_webui.utils.plugin.extract_frontmatter."""
    lines = source.splitlines()
    if not lines or lines[0].strip() != '"""':
        return {}
    pattern = re.compile(r"^\s*([a-z_]+):\s*(.*)\s*$", re.IGNORECASE)
    found = {}
    for line in lines[1:]:
        if '"""' in line:
            break
        match = pattern.match(line)
        if match:
            found[match.group(1).strip()] = match.group(2).strip()
    return found


def inlined_sources(source):
    """The library sources embedded in a built function, as a dict."""
    for node in ast.parse(source).body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == SOURCES_NAME for target in node.targets
        ):
            return ast.literal_eval(node.value)
    raise BuildError(SOURCES_NAME + " not found")


def library_sources():
    return {name: (LIBRARY / (name + ".py")).read_text(encoding="utf-8") for name in MODULES}


def render():
    template = TEMPLATE.read_text(encoding="utf-8")
    lines = template.split("\n")
    begins = [i for i, line in enumerate(lines) if line.startswith(BEGIN)]
    ends = [i for i, line in enumerate(lines) if line.startswith(END)]
    if len(begins) != 1 or len(ends) != 1 or begins[0] > ends[0]:
        raise BuildError("the template needs exactly one %r ... %r region" % (BEGIN, END))

    sources = library_sources()
    block = [
        BEGIN + " (generated by server-plugins/openwebui/build.py; do not edit)",
        "# Verbatim copies of server-plugins/common/conduit_webpush/{%s}.py." % ",".join(MODULES),
        SOURCES_NAME + " = {",
    ]
    for name, source in sources.items():
        if "'''" in source or source.endswith("\\"):
            raise BuildError(name + ".py can't be embedded in a raw ''' string")
        block.append("    %r: r'''%s'''," % (name, source))
    block.append("}")
    block.append(END)
    built = "\n".join(lines[: begins[0]] + block + lines[ends[0] + 1 :])

    if not built.startswith('"""\n'):
        raise BuildError("the function must start with its frontmatter docstring")
    for needle in REWRITTEN_BY_OPEN_WEBUI:
        if needle in built:
            raise BuildError("the function contains %r, which Open WebUI rewrites" % needle)
    manifest = frontmatter(built)
    missing = [key for key in REQUIRED_FRONTMATTER if key not in manifest]
    if missing or "requirements" in manifest:
        raise BuildError("bad frontmatter: missing %s" % missing if missing else "requirements: is not allowed")
    compile(built, "conduit_push.py", "exec")
    if inlined_sources(built) != sources:
        raise BuildError("the inlined library does not match its source")
    return built


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if an output is out of date")
    args = parser.parse_args(argv)
    try:
        built = render()
    except BuildError as error:
        print("build.py: " + str(error), file=sys.stderr)
        return 2

    stale = []
    for output in OUTPUTS:
        current = output.read_text(encoding="utf-8") if output.exists() else None
        if current == built:
            continue
        if args.check:
            stale.append(output)
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            with output.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(built)
            print("wrote " + str(output.relative_to(ROOT)))
    if stale:
        for output in stale:
            print("stale: " + str(output.relative_to(ROOT)), file=sys.stderr)
        print("run: python server-plugins/openwebui/build.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
