"""
title: Conduit Push
author: cogwheel0
author_url: https://github.com/cogwheel0/conduit
version: 1.0.0
required_open_webui_version: 0.10.0
license: GPL-3.0
description: End-to-end encrypted push notifications for the Conduit app. Each notification is encrypted on this server to a key that only exists on the user's device.
conduit_protocol: 1
"""

# Conduit Push for Open WebUI
#
# Sends Conduit push notifications when a reply finishes or fails, and when
# someone posts in a channel. Every notification is encrypted here, on this
# server, to the receiving device's own P-256 key (Web Push, RFC 8291). It is
# then posted to that device's push endpoint: either the Conduit relay, which
# forwards the ciphertext to Apple or Google, or the user's own UnifiedPush
# distributor. Nothing between this server and the device can read it.
#
# Users register their devices from the Conduit app. Each device's
# subscription is stored in this function's user valves, which Conduit
# manages; nobody needs to edit them by hand.
#
# Protocol: docs/push/PROTOCOL.md in the Conduit repository.
# Admin guide: docs/push/ADMIN_SETUP.md in the same repository.
#
# The released conduit_push.py is generated by server-plugins/openwebui/build.py
# from conduit_push.template.py and the shared server-plugins/common/conduit_webpush
# library. Edit those two, then run the build.

import asyncio
import contextvars
import functools
import ipaddress
import json
import logging
import re
import socket
import sys
import time
import types
import urllib.parse
import weakref
from collections import OrderedDict
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

from cryptography.hazmat.primitives.asymmetric import ec
from pydantic import BaseModel, Field

# >>> conduit_webpush
_CONDUIT_WEBPUSH_SOURCES = {}  # build.py inlines the shared library here.
# <<< conduit_webpush


def _load_webpush_library():
    """Loads the inlined library as private modules, so its own relative imports work."""
    package_name = __name__ + "._conduit_webpush"
    package = types.ModuleType(package_name)
    package.__path__ = []
    package.__package__ = package_name
    sys.modules[package_name] = package
    for name in ("webpush", "payload"):
        module = types.ModuleType(package_name + "." + name)
        module.__package__ = package_name
        module.__file__ = "<conduit_webpush/" + name + ".py>"
        sys.modules[module.__name__] = module
        exec(compile(_CONDUIT_WEBPUSH_SOURCES[name], module.__file__, "exec"), module.__dict__)
        setattr(package, name, module)
    return package.webpush, package.payload


webpush, cp = _load_webpush_library()

log = logging.getLogger(__name__)

PROTOCOL = 1
SOURCE = "owui"
DEFAULT_EVENTS = ("reply", "reply_failed", "channel")
STALE_AFTER_S = 30 * 24 * 3600
TEST_MAX_AGE_S = 3600
SEND_CONCURRENCY = 16
MAX_PENDING_JOBS = 1000
NONCE_MEMORY = 4096
SSRF_CACHE_SIZE = 2048
SSRF_OK_TTL_S = 600
SSRF_BLOCKED_TTL_S = 60
# Open WebUI cuts every event string at 1000 characters and appends "...".
EVENT_TEXT_LIMIT = 1000

_B64U = re.compile(r"^[A-Za-z0-9_-]+={0,2}$")
_SID = re.compile(r"^[A-Za-z0-9_-]{22}$")
_NONCE = re.compile(r"^[A-Za-z0-9_-]{8,128}$")
# Channel mentions are stored as <@U:id|Label>; a preview shows @Label. Neither
# part may contain "<", so a run of unclosed "<@U:" takes linear time.
_MENTION = re.compile(r"<([@#])[A-Z]:([^|<>]+)(?:\|([^<>]+))?>")


class _Subscription(object):
    """One device subscription that passed validation."""

    __slots__ = (
        "sid", "did", "endpoint", "host", "p256dh", "auth", "auth_bytes",
        "events", "origin", "seen", "nonce", "test_at",
    )

    def __init__(self, **fields):
        for key, value in fields.items():
            setattr(self, key, value)


def _text(value: Any) -> str:
    return value if isinstance(value, str) else ""


def _int(value: Any) -> int:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return 0
    try:
        return int(value)
    except (ValueError, OverflowError):  # NaN or infinity, which json.loads accepts
        return 0


def _attr(obj: Any, name: str) -> Any:
    if obj is None:
        return None
    if isinstance(obj, dict):
        return obj.get(name)
    return getattr(obj, name, None)


def _dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _parse_list(value: Any) -> Optional[List[Any]]:
    """The stored subscription list, [] when unset, or None when it can't be read."""
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except ValueError:
            return None
        return parsed if isinstance(parsed, list) else None
    return None


def _parse_dict(value: Any) -> Dict[str, Any]:
    if isinstance(value, dict):
        return dict(value)
    if isinstance(value, str) and value:
        try:
            parsed = json.loads(value)
        except ValueError:
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _b64u_bytes(value: Any, size: int) -> Optional[bytes]:
    if not isinstance(value, str) or not _B64U.match(value):
        return None
    try:
        raw = webpush.b64u_decode(value)
    except ValueError:
        return None
    return raw if len(raw) == size else None


def _is_sid(value: Any) -> bool:
    return isinstance(value, str) and bool(_SID.match(value)) and _b64u_bytes(value, 16) is not None


def _is_p256_point(raw: Optional[bytes]) -> bool:
    if raw is None or raw[0] != 0x04:
        return False
    try:
        ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP256R1(), raw)
    except (ValueError, TypeError):
        return False
    return True


def _endpoint_host(value: Any) -> Optional[str]:
    """The host of a well-formed https endpoint, or None."""
    if not isinstance(value, str) or not 8 < len(value) <= 2048 or not value.isascii():
        return None
    if any(ch in value for ch in "\\ ") or any(ord(ch) < 0x21 or ord(ch) == 0x7F for ch in value):
        return None
    try:
        parts = urllib.parse.urlsplit(value)
        parts.port  # Raises on a malformed port.
    except ValueError:
        return None
    if parts.scheme != "https" or not parts.hostname or "@" in parts.netloc:
        return None
    return parts.hostname.lower()


def _parse_subscription(raw: Any) -> Tuple[str, Optional[_Subscription]]:
    """Returns ("ok", subscription), ("unsupported", None) or ("invalid", None).

    An entry for a newer protocol is unsupported: it is kept but not used.
    """
    if not isinstance(raw, dict):
        return "invalid", None
    proto = raw.get("proto", PROTOCOL)
    if isinstance(proto, bool) or not isinstance(proto, int) or proto < 1:
        return "invalid", None
    if proto > PROTOCOL:
        return "unsupported", None
    sid = raw.get("sid")
    host = _endpoint_host(raw.get("endpoint"))
    p256dh = _b64u_bytes(raw.get("p256dh"), 65)
    auth = _b64u_bytes(raw.get("auth"), 16)
    if not _is_sid(sid) or host is None or auth is None or not _is_p256_point(p256dh):
        return "invalid", None

    did = raw.get("did")
    if not isinstance(did, str) or not 0 < len(did) <= 128:
        did = sid
    events = raw.get("events")
    events = tuple(e for e in events if isinstance(e, str)) if isinstance(events, list) else DEFAULT_EVENTS
    test = raw.get("test") if isinstance(raw.get("test"), dict) else {}
    nonce = test.get("nonce")
    return "ok", _Subscription(
        sid=sid,
        did=did,
        endpoint=raw["endpoint"],
        host=host,
        p256dh=raw["p256dh"],
        auth=raw["auth"],
        auth_bytes=auth,
        events=events,
        origin="any" if raw.get("origin") == "any" else "conduit",
        seen=_int(raw.get("seen")),
        nonce=nonce if isinstance(nonce, str) and _NONCE.match(nonce) else None,
        test_at=_int(test.get("at")),
    )


def _select(
    raw_list: List[Any], now: int, cap: int, parse: Any = _parse_subscription
) -> Tuple[List[_Subscription], Set[int], List[str]]:
    """Normalizes a stored subscription list.

    Drops malformed entries and entries not seen for 30 days, keeps the newest
    entry per device (`did`) and per `sid`, and keeps at most `cap` entries,
    newest first. Returns the usable subscriptions in stored order, the indexes
    of the stored entries to keep, and the sids of malformed entries.
    """
    keep: Set[int] = set()
    invalid: List[str] = []
    fresh: List[Tuple[int, _Subscription]] = []
    for index, raw in enumerate(raw_list):
        state, sub = parse(raw)
        if state == "unsupported":
            keep.add(index)
        elif state == "invalid":
            sid = raw.get("sid") if isinstance(raw, dict) else None
            if _is_sid(sid):
                invalid.append(sid)
        elif now - sub.seen <= STALE_AFTER_S:
            fresh.append((index, sub))

    def newest(pairs, key):
        best: Dict[str, Tuple[int, _Subscription]] = {}
        for index, sub in pairs:
            current = best.get(key(sub))
            if current is None or (sub.seen, index) >= (current[1].seen, current[0]):
                best[key(sub)] = (index, sub)
        return list(best.values())

    chosen = newest(newest(fresh, lambda s: s.did), lambda s: s.sid)
    chosen.sort(key=lambda pair: (pair[1].seen, pair[0]), reverse=True)
    chosen = sorted(chosen[: max(int(cap), 1)], key=lambda pair: pair[0])
    keep.update(index for index, _ in chosen)
    return [sub for _, sub in chosen], keep, invalid


class _ParseCache(object):
    """_parse_subscription by stored entry, so a second pass over a fresh read
    of the same list only parses the entries that changed in between."""

    def __init__(self):
        self._parsed: Dict[str, Tuple[str, Optional[_Subscription]]] = {}

    def __call__(self, raw: Any) -> Tuple[str, Optional[_Subscription]]:
        key = json.dumps(raw, sort_keys=True, separators=(",", ":"), default=str)
        if key not in self._parsed:
            self._parsed[key] = _parse_subscription(raw)
        return self._parsed[key]


def _send_key(raw: Any) -> Optional[Tuple[str, str]]:
    """A stored entry's (sid, endpoint), or None when either isn't a string.

    Entries for a newer protocol are kept without being checked, so their
    fields may be lists or objects, which can't be looked up in a set.
    """
    sid, endpoint = _attr(raw, "sid"), _attr(raw, "endpoint")
    return (sid, endpoint) if isinstance(sid, str) and isinstance(endpoint, str) else None


def _merge_commit(
    stored: Dict[str, Any],
    now: int,
    cap: int,
    statuses: Dict[str, Dict[str, Any]],
    dead: Set[Tuple[str, str]],
    parse: Any,
) -> bool:
    """Applies delivery results to one read of a user's valves, in place.

    Drops the entries _select drops and those whose (sid, endpoint) answered
    404 or 410, forgets the status of devices that are gone, and records the
    new statuses. Returns whether anything changed.
    """
    raw_list = _parse_list(stored.get("subscriptions"))
    status = _parse_dict(stored.get("status"))
    changed = False
    if raw_list is not None:
        _, keep, _ = _select(raw_list, now, cap, parse)
        kept = [raw for index, raw in enumerate(raw_list) if index in keep and _send_key(raw) not in dead]
        if len(kept) != len(raw_list):
            stored["subscriptions"] = _dumps(kept)
            changed = True
        live = {sid for sid in (_attr(raw, "sid") for raw in kept) if isinstance(sid, str)} | set(statuses)
        for sid in [sid for sid in status if sid not in live]:
            del status[sid]
            changed = True
    for sid, entry in statuses.items():
        previous = status.get(sid) if isinstance(status.get(sid), dict) else {}
        entry = dict(entry)
        if "nonce" not in entry and isinstance(previous.get("nonce"), str):
            entry["nonce"] = previous["nonce"]
        if not previous or _status_key(previous) != _status_key(entry):
            status[sid] = entry
            changed = True
    if changed:
        stored["status"] = _dumps(status)
    return changed


def _preview(raw: Any) -> str:
    """Plain-text preview of an event's Markdown text.

    Reasoning and tool blocks never belong in a preview, so they are dropped,
    including one left open because the event text was cut short. A stored
    channel message can be any length, so only its first cp.CLEAN_INPUT_LIMIT
    characters reach the regexes below.
    """
    text = _text(raw)
    truncated = len(text) == EVENT_TEXT_LIMIT + 3 and text.endswith("...")
    if truncated:
        text = text[:EVENT_TEXT_LIMIT]
    elif len(text) > cp.CLEAN_INPUT_LIMIT:
        text, truncated = text[: cp.CLEAN_INPUT_LIMIT], True
    text = _MENTION.sub(lambda m: m.group(1) + (m.group(3) or m.group(2)), text)
    text = cp.clean_text(cp.strip_hidden(text))
    return text + cp.ELLIPSIS if truncated and text else text


def _classify(status: int) -> Optional[str]:
    if 200 <= status < 300:
        return None
    if status in (404, 410):
        return "gone"
    if status == 413:
        return "too_large"
    if status == 429:
        return "rate_limited"
    if status >= 500:
        return "server_error"
    return "rejected"


def _status_key(entry: Any) -> Tuple[Any, Any, Any]:
    entry = entry if isinstance(entry, dict) else {}
    return entry.get("code"), entry.get("err"), entry.get("nonce")


def _allowed_hosts(text: str) -> Set[str]:
    return {h.strip().lower().rstrip(".") for h in re.split(r"[,\s]+", text or "") if h.strip()}


def _from_conduit(request: Any) -> bool:
    """True when the completion request came from the Conduit app."""
    try:
        headers = getattr(request, "headers", None)
        agent = headers.get("user-agent") if headers is not None else None
    except Exception:
        return False
    if not isinstance(agent, str):
        return False
    # Conduit sends a bare "Conduit" until startup has read its own version.
    agent = agent.strip()
    return agent == "Conduit" or agent.startswith("Conduit/")


# SSRF. A push endpoint comes from a user, so unless the admin trusts its host,
# every address it resolves to must be public. Open WebUI's own checks skip that
# rule when ENABLE_LOCAL_WEB_FETCH is on, so this function enforces it itself:
# once before sending, and again on the addresses each connection really uses,
# which defeats DNS rebinding.


class _BlockedAddress(ValueError):
    """A push endpoint resolved to an address that isn't public."""


def _is_public_address(value: Any) -> bool:
    """True for a globally routable address. An IPv6 address must also not carry
    a non-public IPv4 one (mapped, compatible, 6to4, Teredo or NAT64)."""
    try:
        address = ipaddress.ip_address(str(value).split("%")[0])
    except ValueError:
        return False
    candidates = [address]
    if address.version == 6:
        packed = address.packed
        candidates += [v4 for v4 in (address.ipv4_mapped, address.sixtofour) if v4 is not None]
        candidates += list(address.teredo or ())
        if packed[:12] in (b"\x00" * 12, b"\x00\x64\xff\x9b" + b"\x00" * 8):
            candidates.append(ipaddress.IPv4Address(packed[12:]))
        elif packed[:6] == b"\x00\x64\xff\x9b\x00\x01":
            candidates.append(ipaddress.IPv4Address(bytes((packed[6], packed[7], packed[9], packed[10]))))
    return all(candidate.is_global for candidate in candidates)


def _literal_address(host: Any) -> Any:
    """The address an IP-literal host names, including legacy forms such as
    127.1 that the system resolver maps onto an address, or None for a name."""
    host = str(host or "").strip("[]").split("%")[0]
    try:
        return ipaddress.ip_address(host)
    except ValueError:
        pass
    try:
        return ipaddress.IPv4Address(socket.inet_aton(host))
    except (OSError, ValueError):
        return None


def _check_public_endpoint(url: str) -> bool:
    """Whether an endpoint passes Open WebUI's URL check (which also applies its
    filter list) and every address its host resolves to is public.

    It resolves DNS, so it runs in a worker thread. A host that doesn't resolve
    is blocked.
    """
    try:
        from open_webui.retrieval.web.utils import validate_url
    except Exception:
        validate_url = None
    try:
        if validate_url is not None and not validate_url(url):
            return False
        host = urllib.parse.urlsplit(url).hostname
        literal = _literal_address(host)
        if literal is not None:
            return _is_public_address(literal)
        addresses = {info[4][0] for info in socket.getaddrinfo(host, 443, 0, socket.SOCK_STREAM)}
        return bool(addresses) and all(_is_public_address(a) for a in addresses)
    except Exception:
        return False


# The proxy host of the request being connected, which the admin configured.
_PROXY_HOST: "contextvars.ContextVar[Optional[str]]" = contextvars.ContextVar("conduit_push_proxy", default=None)


def _host_key(host: Any) -> str:
    return str(host or "").rstrip(".").lower()


@functools.lru_cache(maxsize=None)
def _public_classes() -> Tuple[Any, Any]:
    """The aiohttp connector and resolver behind the public-only session.

    The resolver rejects any answer that isn't public, so the addresses the
    connector dials are the ones it checked. IP-literal hosts never reach a
    resolver, so the connector checks those itself. Through a proxy, only the
    proxy is dialled here; the proxy resolves the endpoint.
    """
    import aiohttp
    from aiohttp.abc import AbstractResolver

    class PublicResolver(AbstractResolver):
        def __init__(self):
            self._inner = aiohttp.ThreadedResolver()

        async def resolve(self, host, port=0, family=socket.AF_INET):
            results = await self._inner.resolve(host, port, family=family)
            if _host_key(host) != _PROXY_HOST.get():
                if not results or not all(_is_public_address(entry["host"]) for entry in results):
                    raise _BlockedAddress("not a public address")
            return results

        async def close(self):
            await self._inner.close()

    class PublicConnector(aiohttp.TCPConnector):
        async def connect(self, req, traces, timeout):
            proxy = getattr(req, "proxy", None)
            if proxy is None:
                literal = _literal_address(req.url.raw_host)
                if literal is not None and not _is_public_address(literal):
                    raise _BlockedAddress("not a public address")
            token = _PROXY_HOST.set(_host_key(proxy.raw_host) if proxy is not None else None)
            try:
                return await super().connect(req, traces, timeout)
            finally:
                _PROXY_HOST.reset(token)

    return PublicConnector, PublicResolver


def _public_connector() -> Any:
    connector, resolver = _public_classes()
    return connector(resolver=resolver(), use_dns_cache=False)


def _session_ssl() -> Any:
    try:
        from open_webui.env import AIOHTTP_CLIENT_SESSION_SSL
    except Exception:
        return None
    return AIOHTTP_CLIENT_SESSION_SSL


async def _post(session: Any, url: str, body: bytes, headers: Dict[str, str], timeout_s: float) -> int:
    import aiohttp

    options: Dict[str, Any] = {
        "data": body,
        "headers": headers,
        "timeout": aiohttp.ClientTimeout(total=float(timeout_s)),
        "allow_redirects": False,
    }
    ssl = _session_ssl()
    if ssl is not None:
        options["ssl"] = ssl
    async with session.post(url, **options) as response:
        return int(response.status)


class _Sessions(object):
    """HTTP sessions for one batch of sends, closed when the batch ends.

    Endpoints the admin doesn't trust go through the public-only connector,
    on every Open WebUI version and whatever ENABLE_LOCAL_WEB_FETCH says.
    Hosts the admin trusts use a plain session.
    """

    def __init__(self):
        self._safe = None
        self._plain = None

    def get(self, trusted: bool) -> Any:
        import aiohttp

        if trusted:
            if self._plain is None:
                self._plain = aiohttp.ClientSession(trust_env=True)
            return self._plain
        if self._safe is None:
            self._safe = aiohttp.ClientSession(connector=_public_connector(), trust_env=True)
        return self._safe

    async def close(self) -> None:
        for session in (self._safe, self._plain):
            if session is not None:
                try:
                    await session.close()
                except Exception:
                    pass


async def _read_user_valves(function_id: str, user_id: str) -> Optional[Dict[str, Any]]:
    from open_webui.models.functions import Functions

    stored = await Functions.get_user_valves_by_id_and_user_id(function_id, user_id)
    return dict(stored) if isinstance(stored, dict) else None


class Event:
    class Valves(BaseModel):
        allow_private_endpoints: bool = Field(
            default=False,
            description=(
                "Allow push endpoints on private, local or loopback addresses, such as a "
                "UnifiedPush distributor on your LAN. Leave off unless you need it."
            ),
        )
        extra_allowed_hosts: str = Field(
            default="",
            description="Comma-separated host names that skip the private-address check, e.g. ntfy.home.arpa.",
        )
        max_subscriptions_per_user: int = Field(
            default=10, ge=1, le=100, description="How many devices each user can register."
        )
        timeout_s: float = Field(default=5, gt=0, le=60, description="Seconds to wait for each push endpoint.")
        max_channel_recipients: int = Field(
            default=500,
            ge=0,
            le=10000,
            description="The most people one channel message notifies. 0 turns channel notifications off.",
        )

    class UserValves(BaseModel):
        subscriptions: str = Field(default="[]", description="Managed by Conduit. Do not edit.")
        status: str = Field(default="{}", description="Delivery status for Conduit. Do not edit.")

    def __init__(self):
        self.valves = self.Valves()
        self._tasks: Set[asyncio.Task] = set()
        self._loop: Any = None
        self._semaphore: Any = None
        self._locks: Any = weakref.WeakValueDictionary()
        self._nonces: "OrderedDict[str, bool]" = OrderedDict()
        self._ssrf_cache: "OrderedDict[str, Tuple[bool, float]]" = OrderedDict()
        self._warned: Set[str] = set()

    async def event(self, event, __event_name__=None, __request__=None, __id__=None, **kwargs):
        """Called by Open WebUI for every event. Returns at once; sends run in the background."""
        try:
            self._dispatch(event, __event_name__, __request__, __id__)
        except Exception as error:
            log.warning("conduit push: could not handle an event (%s)", type(error).__name__)

    def _dispatch(self, event: Any, name: Any, request: Any, function_id: Any) -> None:
        if not isinstance(event, dict):
            return
        name = name or event.get("event")
        if name not in ("chat.finished", "chat.failed", "message.created", "function.valves_updated"):
            return
        function_id = function_id or (__name__[len("function_"):] if __name__.startswith("function_") else "conduit_push")
        data = event.get("data") if isinstance(event.get("data"), dict) else {}
        actor = event.get("actor") if isinstance(event.get("actor"), dict) else {}
        subject = event.get("subject") if isinstance(event.get("subject"), dict) else {}
        valves = self.valves
        self._bind_loop()

        if name in ("chat.finished", "chat.failed"):
            self._spawn("reply", self._on_chat(function_id, name, data, _from_conduit(request), valves))
        elif name == "message.created":
            if data.get("channel_id") and _text(subject.get("id")):
                self._spawn("channel", self._on_channel(function_id, data, actor, subject["id"], valves))
        elif subject.get("id") == function_id and data.get("scope") == "user" and _text(actor.get("id")):
            self._spawn("subscribe", self._on_valves_updated(function_id, actor["id"], valves))

    def _bind_loop(self) -> None:
        loop = asyncio.get_running_loop()
        if self._loop is not loop:
            self._loop = loop
            self._semaphore = asyncio.Semaphore(SEND_CONCURRENCY)
            self._locks = weakref.WeakValueDictionary()

    def _spawn(self, label: str, job: Any) -> None:
        if len(self._tasks) >= MAX_PENDING_JOBS:
            job.close()
            log.warning("conduit push: too many notifications in flight, dropped one")
            return
        task = asyncio.ensure_future(self._guard(label, job))
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)

    async def _guard(self, label: str, job: Any) -> None:
        try:
            await job
        except asyncio.CancelledError:
            raise
        except Exception as error:
            log.warning("conduit push: %s failed (%s)", label, type(error).__name__)

    async def _wait_idle(self) -> None:
        """Waits for every notification in flight. Used by tests."""
        while self._tasks:
            await asyncio.gather(*list(self._tasks), return_exceptions=True)

    def _warn_once(self, key: str, message: str) -> None:
        if key not in self._warned:
            self._warned.add(key)
            log.warning(message)

    def _user_lock(self, user_id: str) -> asyncio.Lock:
        lock = self._locks.get(user_id)
        if lock is None:
            lock = asyncio.Lock()
            self._locks[user_id] = lock
        return lock

    def _claim_nonce(self, user_id: str, sid: str, nonce: str) -> bool:
        key = user_id + "|" + sid + "|" + nonce
        if key in self._nonces:
            return False
        self._nonces[key] = True
        while len(self._nonces) > NONCE_MEMORY:
            self._nonces.popitem(last=False)
        return True

    # Events

    async def _on_chat(self, function_id: str, name: str, data: Dict[str, Any], from_conduit: bool, valves: Any) -> None:
        user_id, chat_id, message_id = (_text(data.get(k)) for k in ("user_id", "chat_id", "message_id"))
        if not (user_id and chat_id and message_id):
            return
        kind = "reply" if name == "chat.finished" else "reply_failed"
        stored = await _read_user_valves(function_id, user_id)
        targets = [
            sub
            for sub in self._usable(stored, valves)
            if kind in sub.events and (sub.origin == "any" or from_conduit)
        ]
        if not targets:
            return
        if kind == "reply":
            title, body = _text(data.get("title")), _preview(data.get("message"))
        else:
            title, body = await self._chat_title(chat_id), ""
        note = cp.build(
            kind,
            SOURCE,
            ids={"chat": chat_id, "msg": message_id},
            title=title,
            body=body,
            dedup_key="chat:" + chat_id + ":" + message_id,
            group="chat:" + chat_id,
            clean=False,
        )
        await self._deliver(function_id, {user_id: [(sub, note) for sub in targets]}, valves)

    async def _on_channel(
        self, function_id: str, data: Dict[str, Any], actor: Dict[str, Any], message_id: str, valves: Any
    ) -> None:
        limit = int(valves.max_channel_recipients)
        if limit <= 0:
            return
        from open_webui.models.channels import Channels
        from open_webui.models.messages import Messages

        channel_id = _text(data.get("channel_id"))
        try:
            message = await Messages.get_message_by_id(message_id, include_thread_replies=False)
        except TypeError:
            message = await Messages.get_message_by_id(message_id)
        if message is None or _attr(message, "channel_id") != channel_id:
            return
        if _attr(message, "parent_id"):
            return  # Thread replies don't notify.
        channel = await Channels.get_channel_by_id(channel_id)
        if channel is None or _attr(channel, "deleted_at") or _attr(channel, "archived_at"):
            return

        members = await Channels.get_members_by_channel_id(channel_id) or []
        recipients = list(
            dict.fromkeys(
                _text(_attr(m, "user_id")) for m in members if not _attr(m, "is_channel_muted")
            )
        )
        kind = _attr(channel, "type")
        if kind not in ("dm", "group"):
            # Standard channels: members who still have read access, as Open WebUI's
            # own channel notifications do. Group and DM access is membership.
            allowed = await self._read_access(channel)
            if allowed is None:
                return  # Membership alone doesn't prove read access.
            recipients = [uid for uid in recipients if uid in allowed]
        sender_id = None if actor.get("type") == "webhook" else (_text(actor.get("id")) or _text(_attr(message, "user_id")))
        recipients = [uid for uid in recipients if uid and uid != sender_id][:limit]
        if not recipients:
            return

        sender = _text(actor.get("name")) or _text(_attr(_attr(message, "user"), "name"))
        channel_name = _text(_attr(channel, "name"))
        title = sender if kind == "dm" or not channel_name else "#" + channel_name
        note = cp.build(
            "channel",
            SOURCE,
            ids={"channel": channel_id, "msg": message_id},
            title=title,
            body=_preview(_attr(message, "content") or data.get("content_preview")),
            author=sender or None,
            dedup_key="channel:" + channel_id + ":" + message_id,
            group="channel:" + channel_id,
            clean=False,
        )
        stored = await self._read_many_user_valves(function_id, recipients)
        work = {}
        for uid in recipients:
            jobs = [(sub, note) for sub in self._usable(stored.get(uid), valves) if "channel" in sub.events]
            if jobs:
                work[uid] = jobs
        if work:
            await self._deliver(function_id, work, valves)

    async def _on_valves_updated(self, function_id: str, user_id: str, valves: Any) -> None:
        """A user saved this function's valves, normally Conduit subscribing a device."""
        stored = await _read_user_valves(function_id, user_id)
        if stored is None:
            return
        raw_list = _parse_list(stored.get("subscriptions"))
        if raw_list is None:
            return
        status = _parse_dict(stored.get("status"))
        now = int(time.time())
        subs, _, invalid = _select(raw_list, now, valves.max_subscriptions_per_user)
        notes = {sid: {"code": None, "at": now, "err": "invalid"} for sid in invalid}
        jobs = []
        for sub in subs:
            pending = sub.nonce and not (sub.test_at and now - sub.test_at > TEST_MAX_AGE_S)
            handled = _attr(status.get(sub.sid), "nonce") == sub.nonce
            if pending and not handled:
                if self._claim_nonce(user_id, sub.sid, sub.nonce):
                    test = cp.build(
                        "test", SOURCE, ids={}, title="", body="", dedup_key="test:" + sub.nonce, nonce=sub.nonce
                    )
                    jobs.append((sub, test))
            elif not self._trusted(sub, valves) and not await self._endpoint_is_public(sub.endpoint):
                notes[sub.sid] = {"code": None, "at": now, "err": "blocked"}
        await self._deliver(function_id, {user_id: jobs}, valves, notes={user_id: notes})

    # Loading

    def _usable(self, stored: Optional[Dict[str, Any]], valves: Any) -> List[_Subscription]:
        if not isinstance(stored, dict):
            return []
        raw_list = _parse_list(stored.get("subscriptions"))
        if not raw_list:
            return []
        return _select(raw_list, int(time.time()), valves.max_subscriptions_per_user)[0]

    async def _chat_title(self, chat_id: str) -> str:
        try:
            from open_webui.models.chats import Chats

            return _text(await Chats.get_chat_title_by_id(chat_id))
        except Exception:
            return ""

    async def _read_access(self, channel: Any) -> Optional[Set[str]]:
        """Ids of users with read access, or None when Open WebUI has no such helper."""
        try:
            from open_webui.routers.channels import get_channel_users_with_access
        except Exception:
            self._warn_once("access", "conduit push: channel access helper missing, standard channels won't notify")
            return None
        users = await get_channel_users_with_access(channel, "read")
        return {_text(_attr(user, "id")) for user in users or []}

    async def _read_many_user_valves(self, function_id: str, user_ids: List[str]) -> Dict[str, Dict[str, Any]]:
        """Every recipient's valves for this function, in one query when possible."""
        try:
            from open_webui.models.users import Users

            users = await Users.get_users_by_user_ids(list(user_ids))
        except Exception:
            users = None
        try:
            from open_webui.utils.valves import decrypt_valves
        except Exception:
            decrypt_valves = None

        found: Dict[str, Dict[str, Any]] = {}
        slow: List[str] = list(user_ids) if users is None else []
        for user in users or []:
            settings = _attr(user, "settings")
            if hasattr(settings, "model_dump"):
                settings = settings.model_dump()
            functions = settings.get("functions") if isinstance(settings, dict) else None
            valve_map = functions.get("valves") if isinstance(functions, dict) else None
            stored = valve_map.get(function_id) if isinstance(valve_map, dict) else None
            if isinstance(stored, str) and stored:
                if decrypt_valves is None:
                    slow.append(_text(_attr(user, "id")))
                    continue
                stored = decrypt_valves(stored)
            if isinstance(stored, dict) and stored:
                found[_text(_attr(user, "id"))] = stored
        for user_id in slow:
            stored = await _read_user_valves(function_id, user_id)
            if stored:
                found[user_id] = stored
        return found

    # Sending

    def _trusted(self, sub: _Subscription, valves: Any) -> bool:
        return bool(valves.allow_private_endpoints) or sub.host in _allowed_hosts(valves.extra_allowed_hosts)

    async def _endpoint_is_public(self, url: str) -> bool:
        now = time.monotonic()
        cached = self._ssrf_cache.get(url)
        if cached is not None and cached[1] > now:
            return cached[0]
        allowed = await asyncio.to_thread(_check_public_endpoint, url)
        self._ssrf_cache[url] = (allowed, now + (SSRF_OK_TTL_S if allowed else SSRF_BLOCKED_TTL_S))
        self._ssrf_cache.move_to_end(url)
        while len(self._ssrf_cache) > SSRF_CACHE_SIZE:
            self._ssrf_cache.popitem(last=False)
        return allowed

    async def _deliver(
        self,
        function_id: str,
        work: Dict[str, List[Tuple[_Subscription, Dict[str, Any]]]],
        valves: Any,
        notes: Optional[Dict[str, Dict[str, Dict[str, Any]]]] = None,
    ) -> None:
        sessions = _Sessions()
        try:
            results = await asyncio.gather(
                *(
                    self._deliver_user(function_id, user_id, jobs, valves, sessions, (notes or {}).get(user_id))
                    for user_id, jobs in work.items()
                ),
                return_exceptions=True,
            )
        finally:
            await sessions.close()
        for result in results:
            if isinstance(result, Exception):
                log.warning("conduit push: delivery failed (%s)", type(result).__name__)

    async def _deliver_user(
        self,
        function_id: str,
        user_id: str,
        jobs: List[Tuple[_Subscription, Dict[str, Any]]],
        valves: Any,
        sessions: _Sessions,
        notes: Optional[Dict[str, Dict[str, Any]]],
    ) -> None:
        results = await asyncio.gather(*(self._send(sessions, sub, note, valves) for sub, note in jobs))
        now = int(time.time())
        statuses = dict(notes or {})
        dead: Set[Tuple[str, str]] = set()
        for (sub, note), (code, err) in zip(jobs, results):
            entry = {"code": code, "at": now, "err": err}
            if note.get("k") == "test":
                entry["nonce"] = note.get("n")
            statuses[sub.sid] = entry
            if err == "gone":
                dead.add((sub.sid, sub.endpoint))
        failed = sum(1 for _, err in results if err)
        if failed:
            log.info("conduit push: %d of %d sends failed", failed, len(results))
        await self._commit(function_id, user_id, valves, statuses, dead)

    async def _send(
        self, sessions: _Sessions, sub: _Subscription, note: Dict[str, Any], valves: Any
    ) -> Tuple[Optional[int], Optional[str]]:
        """Encrypts and posts one notification. Returns (HTTP status, error category)."""
        async with self._semaphore:
            try:
                trusted = self._trusted(sub, valves)
                if not trusted and not await self._endpoint_is_public(sub.endpoint):
                    return None, "blocked"
                try:
                    body = cp.seal(note, {"p256dh": sub.p256dh, "auth": sub.auth})
                except Exception:
                    return None, "encrypt"
                headers = webpush.headers(note["k"], sub.auth_bytes, note["dk"])
                status = await _post(sessions.get(trusted), sub.endpoint, body, headers, valves.timeout_s)
            except asyncio.CancelledError:
                raise
            except asyncio.TimeoutError:
                return None, "timeout"
            except ValueError:
                return None, "blocked"  # The connector refused an address that isn't public.
            except Exception:
                return None, "network"
            return status, _classify(status)

    async def _commit(
        self,
        function_id: str,
        user_id: str,
        valves: Any,
        statuses: Dict[str, Dict[str, Any]],
        dead: Set[Tuple[str, str]],
    ) -> None:
        """Records delivery status and prunes dead or stale subscriptions.

        Under a per-user lock it works the change out on one read of the
        valves. If anything changes, it reads them again just before writing
        and applies the change to that fresh copy, reusing the first pass's
        parsing, so a device that subscribed meanwhile is kept and the gap
        between the read that is written back and the write is as short as it
        can be.

        It can't close that gap. The lock only orders this worker's commits,
        and Open WebUI has no compare-and-set, so a write that lands inside it
        is overwritten: from another worker, or from the app saving the valves
        over REST, for example a device subscribing.

        Writes go through the model method, which doesn't publish an event, so
        nothing loops.
        """
        from open_webui.models.functions import Functions

        now = int(time.time())
        cap = valves.max_subscriptions_per_user
        parse = _ParseCache()
        async with self._user_lock(user_id):
            stored = await _read_user_valves(function_id, user_id)
            if stored is None or not _merge_commit(stored, now, cap, statuses, dead, parse):
                return
            fresh = await _read_user_valves(function_id, user_id)
            if fresh is None or not _merge_commit(fresh, now, cap, statuses, dead, parse):
                return
            await Functions.update_user_valves_by_id_and_user_id(function_id, user_id, fresh)
