"""
title: Conduit Push
author: cogwheel0
author_url: https://github.com/cogwheel0/conduit
version: 1.0.0
required_open_webui_version: 0.10.0
license: GPL-3.0
description: End-to-end encrypted push notifications for the Conduit app. Each notification is encrypted on this server to a key that only exists on the user's device.
conduit_protocol: 1
"""

# Conduit Push for Open WebUI
#
# Sends Conduit push notifications when a reply finishes or fails, and when
# someone posts in a channel. Every notification is encrypted here, on this
# server, to the receiving device's own P-256 key (Web Push, RFC 8291). It is
# then posted to that device's push endpoint: either the Conduit relay, which
# forwards the ciphertext to Apple or Google, or the user's own UnifiedPush
# distributor. Nothing between this server and the device can read it.
#
# Users register their devices from the Conduit app. Each device's
# subscription is stored in this function's user valves, which Conduit
# manages; nobody needs to edit them by hand.
#
# Protocol: docs/push/PROTOCOL.md in the Conduit repository.
# Admin guide: docs/push/ADMIN_SETUP.md in the same repository.
#
# The released conduit_push.py is generated by server-plugins/openwebui/build.py
# from conduit_push.template.py and the shared server-plugins/common/conduit_webpush
# library. Edit those two, then run the build.

import asyncio
import ipaddress
import json
import logging
import re
import socket
import sys
import time
import types
import urllib.parse
import weakref
from collections import OrderedDict
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

from cryptography.hazmat.primitives.asymmetric import ec
from pydantic import BaseModel, Field

# >>> conduit_webpush (generated by server-plugins/openwebui/build.py; do not edit)
# Verbatim copies of server-plugins/common/conduit_webpush/{webpush,payload}.py.
_CONDUIT_WEBPUSH_SOURCES = {
    'webpush': r'''"""Web Push message encryption (RFC 8291 / RFC 8188 aes128gcm) for Conduit push.

Every notification is encrypted to the device's own P-256 key before it leaves
the user's server, so neither the Conduit relay nor Apple or Google can read it.
See docs/push/PROTOCOL.md section 3.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import struct
from typing import Dict, Optional, Tuple

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

RECORD_SIZE = 4096
HEADER_LEN = 86
TAG_LEN = 16
# AES-GCM output sizes (padded plaintext + tag) a body is padded to, so the
# size of a notification only leaks which of three classes it falls into.
BUCKETS = (512, 1024, 2048)
MAX_BODY = HEADER_LEN + BUCKETS[-1]

_KEY_INFO = b"WebPush: info\x00"
_CEK_INFO = b"Content-Encoding: aes128gcm\x00"
_NONCE_INFO = b"Content-Encoding: nonce\x00"


class PayloadTooLarge(ValueError):
    """The plaintext does not fit the largest padding bucket."""


class DecryptError(ValueError):
    """A body that is malformed or fails authentication."""


def b64u_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def b64u_decode(text: str) -> bytes:
    text = "".join(text.split())
    return base64.urlsafe_b64decode(text + "=" * (-len(text) % 4))


def _hkdf_extract(salt: bytes, ikm: bytes) -> bytes:
    return hmac.new(salt, ikm, hashlib.sha256).digest()


def _hkdf_expand(prk: bytes, info: bytes, length: int) -> bytes:
    # Every output here is at most one SHA-256 block.
    return hmac.new(prk, info + b"\x01", hashlib.sha256).digest()[:length]


def _public_bytes(key: ec.EllipticCurvePublicKey) -> bytes:
    return key.public_bytes(
        serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint
    )


def _load_public(raw: bytes) -> ec.EllipticCurvePublicKey:
    if len(raw) != 65 or raw[0] != 0x04:
        raise ValueError("p256dh must be an uncompressed P-256 point")
    return ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP256R1(), raw)


def load_private(raw: bytes) -> ec.EllipticCurvePrivateKey:
    return ec.derive_private_key(int.from_bytes(raw, "big"), ec.SECP256R1())


def private_bytes(key: ec.EllipticCurvePrivateKey) -> bytes:
    return key.private_numbers().private_value.to_bytes(32, "big")


def public_bytes_of(key: ec.EllipticCurvePrivateKey) -> bytes:
    return _public_bytes(key.public_key())


def _derive(
    ecdh_secret: bytes, auth: bytes, ua_public: bytes, as_public: bytes, salt: bytes
) -> Tuple[bytes, bytes]:
    prk_key = _hkdf_extract(auth, ecdh_secret)
    ikm = _hkdf_expand(prk_key, _KEY_INFO + ua_public + as_public, 32)
    prk = _hkdf_extract(salt, ikm)
    return _hkdf_expand(prk, _CEK_INFO, 16), _hkdf_expand(prk, _NONCE_INFO, 12)


def bucket_for(plaintext_len: int) -> int:
    """The smallest bucket that holds the plaintext, its delimiter and the tag."""
    needed = plaintext_len + 1 + TAG_LEN
    for bucket in BUCKETS:
        if needed <= bucket:
            return bucket
    raise PayloadTooLarge(f"{plaintext_len} bytes do not fit {BUCKETS[-1]}")


def encrypt(
    plaintext: bytes,
    ua_public: bytes,
    auth: bytes,
    *,
    pad: bool = True,
    as_private: Optional[bytes] = None,
    salt: Optional[bytes] = None,
    _delimiter: int = 0x02,
) -> bytes:
    """Encrypts one notification body for one subscription.

    `as_private` and `salt` are only passed by the test-vector generator;
    production calls always use fresh random values.
    """
    if len(auth) != 16:
        raise ValueError("auth secret must be 16 bytes")
    peer = _load_public(ua_public)
    sender = load_private(as_private) if as_private else ec.generate_private_key(ec.SECP256R1())
    as_public = _public_bytes(sender.public_key())
    salt = salt if salt is not None else os.urandom(16)
    cek, nonce = _derive(sender.exchange(ec.ECDH(), peer), auth, ua_public, as_public, salt)

    record = plaintext + bytes([_delimiter])
    if pad:
        record += b"\x00" * (bucket_for(len(plaintext)) - TAG_LEN - len(record))
    header = salt + struct.pack("!I", RECORD_SIZE) + bytes([len(as_public)]) + as_public
    return header + AESGCM(cek).encrypt(nonce, record, None)


def decrypt(body: bytes, ua_private: bytes, auth: bytes) -> bytes:
    """Decrypts a body the way the device does. Used by tests and diagnostics."""
    if len(body) > MAX_BODY:
        raise DecryptError("body too large")
    if len(body) < HEADER_LEN + TAG_LEN + 1:
        raise DecryptError("body too short")
    salt = body[:16]
    (record_size,) = struct.unpack("!I", body[16:20])
    idlen = body[20]
    if idlen != 65:
        raise DecryptError("keyid must be a 65-byte P-256 key")
    if record_size < 18:
        raise DecryptError("record size too small")
    as_public = body[21:86]
    ciphertext = body[86:]
    if len(ciphertext) > record_size:
        raise DecryptError("more than one record")

    receiver = load_private(ua_private)
    try:
        sender = _load_public(as_public)
    except ValueError as error:
        raise DecryptError(str(error)) from error
    ua_public = _public_bytes(receiver.public_key())
    cek, nonce = _derive(receiver.exchange(ec.ECDH(), sender), auth, ua_public, as_public, salt)
    try:
        record = AESGCM(cek).decrypt(nonce, ciphertext, None)
    except Exception as error:  # InvalidTag
        raise DecryptError("authentication failed") from error

    end = len(record)
    while end > 0 and record[end - 1] == 0:
        end -= 1
    if end == 0 or record[end - 1] != 0x02:
        raise DecryptError("missing last-record delimiter")
    return record[: end - 1]


def topic(auth: bytes, dedup_key: str) -> str:
    """The `Topic` header: collapses retries without telling the relay anything."""
    digest = hmac.new(auth, dedup_key.encode("utf-8"), hashlib.sha256).digest()
    return b64u_encode(digest)[:22]


TTL = {"reply": 86400, "reply_failed": 86400, "channel": 86400, "cron": 259200, "test": 300}


def headers(kind: str, auth: bytes, dedup_key: str) -> Dict[str, str]:
    return {
        "Content-Encoding": "aes128gcm",
        "Content-Type": "application/octet-stream",
        "TTL": str(TTL.get(kind, 86400)),
        "Urgency": "normal" if kind == "cron" else "high",
        "Topic": topic(auth, dedup_key),
    }
''',
    'payload': r'''"""The `cp/1` notification payload: what a Conduit push says once decrypted.

See docs/push/PROTOCOL.md section 2. Servers build the payload, clean the
preview text, and fit it into the largest padding bucket.
"""

from __future__ import annotations

import json
import re
import time
from typing import Any, Dict, Mapping, Optional

from . import webpush

KINDS = ("reply", "reply_failed", "channel", "cron", "test")
SOURCES = ("owui", "hermes")
ID_KEYS = ("chat", "msg", "channel", "session", "turn", "job", "run")
TITLE_LIMIT = 100
BODY_LIMIT = 200
AUTHOR_LIMIT = 64
ELLIPSIS = "…"

_BLOCKS = [
    re.compile(r"<details\b[^>]*>.*?</details\s*>", re.IGNORECASE | re.DOTALL),
    re.compile(r"<think\b[^>]*>.*?</think\s*>", re.IGNORECASE | re.DOTALL),
    re.compile(r"<thinking\b[^>]*>.*?</thinking\s*>", re.IGNORECASE | re.DOTALL),
    # A fence left open by a truncated or still-streaming reply runs to the end.
    re.compile(r"(^|\n)[ \t]*(```|~~~).*?(\n[ \t]*\2[ \t]*(?=\n|$)|$)", re.DOTALL),
]
_IMAGE = re.compile(r"!\[([^\]]*)\]\([^)]*\)")
_LINK = re.compile(r"\[([^\]]+)\]\([^)]*\)")
_TAG = re.compile(r"</?[A-Za-z][A-Za-z0-9-]*(\s[^<>]*)?/?>")
_LINE_MARKER = re.compile(r"^[ \t]*(#{1,6}[ \t]+|>[ \t]?|[-*+][ \t]+|\d+[.)][ \t]+)", re.MULTILINE)
_EMPHASIS = re.compile(r"(\*\*|__|~~|`)")
_SPACE = re.compile(r"\s+")


def clean_text(text: Optional[str]) -> str:
    """Turns a Markdown reply into one line of plain text for a preview."""
    if not text:
        return ""
    for pattern in _BLOCKS:
        text = pattern.sub("\n", text)
    text = _IMAGE.sub(lambda m: m.group(1), text)
    text = _LINK.sub(lambda m: m.group(1), text)
    text = _TAG.sub("", text)
    text = _LINE_MARKER.sub("", text)
    text = _EMPHASIS.sub("", text)
    return _SPACE.sub(" ", text).strip()


def clip(text: Optional[str], limit: int) -> str:
    """Cuts on code points, never inside a UTF-16 pair or UTF-8 sequence."""
    text = _SPACE.sub(" ", text or "").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + ELLIPSIS


def build(
    kind: str,
    src: str,
    *,
    ids: Mapping[str, Any],
    title: Optional[str],
    body: Optional[str],
    dedup_key: str,
    group: Optional[str] = None,
    author: Optional[str] = None,
    nonce: Optional[str] = None,
    ts: Optional[int] = None,
    clean: bool = True,
) -> Dict[str, Any]:
    if kind not in KINDS:
        raise ValueError(f"unknown kind {kind!r}")
    if src not in SOURCES:
        raise ValueError(f"unknown source {src!r}")
    payload: Dict[str, Any] = {
        "v": 1,
        "k": kind,
        "src": src,
        "ids": {key: str(value) for key, value in ids.items() if key in ID_KEYS and value is not None},
        "t": clip(title, TITLE_LIMIT),
        "b": clip(clean_text(body) if clean else body, BODY_LIMIT),
        "ts": int(ts if ts is not None else time.time()),
        "dk": dedup_key,
    }
    if group:
        payload["g"] = group
    if author:
        payload["a"] = clip(author, AUTHOR_LIMIT)
    if nonce:
        payload["n"] = nonce
    return payload


def encode(payload: Mapping[str, Any]) -> bytes:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def encode_fitting(payload: Dict[str, Any]) -> bytes:
    """Encodes the payload, shortening the preview until it fits the largest bucket.

    Only reachable with very long ids; titles and previews are already capped.
    """
    limit = webpush.BUCKETS[-1] - webpush.TAG_LEN - 1
    data = encode(payload)
    while len(data) > limit and payload.get("b"):
        body = payload["b"]
        payload["b"] = clip(body, len(body) // 2) if len(body) > 1 else ""
        data = encode(payload)
    if len(data) > limit:
        raise webpush.PayloadTooLarge("payload does not fit the largest bucket")
    return data


def seal(payload: Dict[str, Any], subscription: Mapping[str, Any]) -> bytes:
    """Encrypts a payload for one stored subscription (`p256dh`, `auth`)."""
    return webpush.encrypt(
        encode_fitting(dict(payload)),
        webpush.b64u_decode(subscription["p256dh"]),
        webpush.b64u_decode(subscription["auth"]),
    )
''',
}
# <<< conduit_webpush


def _load_webpush_library():
    """Loads the inlined library as private modules, so its own relative imports work."""
    package_name = __name__ + "._conduit_webpush"
    package = types.ModuleType(package_name)
    package.__path__ = []
    package.__package__ = package_name
    sys.modules[package_name] = package
    for name in ("webpush", "payload"):
        module = types.ModuleType(package_name + "." + name)
        module.__package__ = package_name
        module.__file__ = "<conduit_webpush/" + name + ".py>"
        sys.modules[module.__name__] = module
        exec(compile(_CONDUIT_WEBPUSH_SOURCES[name], module.__file__, "exec"), module.__dict__)
        setattr(package, name, module)
    return package.webpush, package.payload


webpush, cp = _load_webpush_library()

log = logging.getLogger(__name__)

PROTOCOL = 1
SOURCE = "owui"
DEFAULT_EVENTS = ("reply", "reply_failed", "channel")
STALE_AFTER_S = 30 * 24 * 3600
TEST_MAX_AGE_S = 3600
SEND_CONCURRENCY = 16
MAX_PENDING_JOBS = 1000
NONCE_MEMORY = 4096
SSRF_CACHE_SIZE = 2048
SSRF_OK_TTL_S = 600
SSRF_BLOCKED_TTL_S = 60
# Open WebUI cuts every event string at 1000 characters and appends "...".
EVENT_TEXT_LIMIT = 1000

_B64U = re.compile(r"^[A-Za-z0-9_-]+={0,2}$")
_SID = re.compile(r"^[A-Za-z0-9_-]{22}$")
_NONCE = re.compile(r"^[A-Za-z0-9_-]{8,128}$")
# Reasoning and tool blocks never belong in a preview. Open WebUI's default
# reasoning tags, <details> blocks and code interpreter blocks are dropped,
# including one left open because the event text was cut short.
_HIDDEN = re.compile(
    r"<(/?)(details|think|thinking|reason|reasoning|thought|code_interpreter)\b[^>]*>"
    r"|<\|(begin|end)_of_thought\|>"
    r"|◁(/?)think▷",
    re.IGNORECASE,
)
_SOLUTION_MARKER = re.compile(r"<\|(?:begin|end)_of_solution\|>")
# Channel mentions are stored as <@U:id|Label>; a preview shows @Label.
_MENTION = re.compile(r"<([@#])[A-Z]:([^|>]+)(?:\|([^>]+))?>")


class _Subscription(object):
    """One device subscription that passed validation."""

    __slots__ = (
        "sid", "did", "endpoint", "host", "p256dh", "auth", "auth_bytes",
        "events", "origin", "seen", "nonce", "test_at",
    )

    def __init__(self, **fields):
        for key, value in fields.items():
            setattr(self, key, value)


def _text(value: Any) -> str:
    return value if isinstance(value, str) else ""


def _int(value: Any) -> int:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return 0
    return int(value)


def _attr(obj: Any, name: str) -> Any:
    if obj is None:
        return None
    if isinstance(obj, dict):
        return obj.get(name)
    return getattr(obj, name, None)


def _dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _parse_list(value: Any) -> Optional[List[Any]]:
    """The stored subscription list, [] when unset, or None when it can't be read."""
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except ValueError:
            return None
        return parsed if isinstance(parsed, list) else None
    return None


def _parse_dict(value: Any) -> Dict[str, Any]:
    if isinstance(value, dict):
        return dict(value)
    if isinstance(value, str) and value:
        try:
            parsed = json.loads(value)
        except ValueError:
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _b64u_bytes(value: Any, size: int) -> Optional[bytes]:
    if not isinstance(value, str) or not _B64U.match(value):
        return None
    try:
        raw = webpush.b64u_decode(value)
    except ValueError:
        return None
    return raw if len(raw) == size else None


def _is_sid(value: Any) -> bool:
    return isinstance(value, str) and bool(_SID.match(value)) and _b64u_bytes(value, 16) is not None


def _is_p256_point(raw: Optional[bytes]) -> bool:
    if raw is None or raw[0] != 0x04:
        return False
    try:
        ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP256R1(), raw)
    except (ValueError, TypeError):
        return False
    return True


def _endpoint_host(value: Any) -> Optional[str]:
    """The host of a well-formed https endpoint, or None."""
    if not isinstance(value, str) or not 8 < len(value) <= 2048 or not value.isascii():
        return None
    if any(ch in value for ch in "\\ ") or any(ord(ch) < 0x21 or ord(ch) == 0x7F for ch in value):
        return None
    try:
        parts = urllib.parse.urlsplit(value)
        parts.port  # Raises on a malformed port.
    except ValueError:
        return None
    if parts.scheme != "https" or not parts.hostname or "@" in parts.netloc:
        return None
    return parts.hostname.lower()


def _parse_subscription(raw: Any) -> Tuple[str, Optional[_Subscription]]:
    """Returns ("ok", subscription), ("unsupported", None) or ("invalid", None).

    An entry for a newer protocol is unsupported: it is kept but not used.
    """
    if not isinstance(raw, dict):
        return "invalid", None
    proto = raw.get("proto", PROTOCOL)
    if isinstance(proto, bool) or not isinstance(proto, int) or proto < 1:
        return "invalid", None
    if proto > PROTOCOL:
        return "unsupported", None
    sid = raw.get("sid")
    host = _endpoint_host(raw.get("endpoint"))
    p256dh = _b64u_bytes(raw.get("p256dh"), 65)
    auth = _b64u_bytes(raw.get("auth"), 16)
    if not _is_sid(sid) or host is None or auth is None or not _is_p256_point(p256dh):
        return "invalid", None

    did = raw.get("did")
    if not isinstance(did, str) or not 0 < len(did) <= 128:
        did = sid
    events = raw.get("events")
    events = tuple(e for e in events if isinstance(e, str)) if isinstance(events, list) else DEFAULT_EVENTS
    test = raw.get("test") if isinstance(raw.get("test"), dict) else {}
    nonce = test.get("nonce")
    return "ok", _Subscription(
        sid=sid,
        did=did,
        endpoint=raw["endpoint"],
        host=host,
        p256dh=raw["p256dh"],
        auth=raw["auth"],
        auth_bytes=auth,
        events=events,
        origin="any" if raw.get("origin") == "any" else "conduit",
        seen=_int(raw.get("seen")),
        nonce=nonce if isinstance(nonce, str) and _NONCE.match(nonce) else None,
        test_at=_int(test.get("at")),
    )


def _select(raw_list: List[Any], now: int, cap: int) -> Tuple[List[_Subscription], Set[int], List[str]]:
    """Normalizes a stored subscription list.

    Drops malformed entries and entries not seen for 30 days, keeps the newest
    entry per device (`did`) and per `sid`, and keeps at most `cap` entries,
    newest first. Returns the usable subscriptions in stored order, the indexes
    of the stored entries to keep, and the sids of malformed entries.
    """
    keep: Set[int] = set()
    invalid: List[str] = []
    fresh: List[Tuple[int, _Subscription]] = []
    for index, raw in enumerate(raw_list):
        state, sub = _parse_subscription(raw)
        if state == "unsupported":
            keep.add(index)
        elif state == "invalid":
            sid = raw.get("sid") if isinstance(raw, dict) else None
            if _is_sid(sid):
                invalid.append(sid)
        elif now - sub.seen <= STALE_AFTER_S:
            fresh.append((index, sub))

    def newest(pairs, key):
        best: Dict[str, Tuple[int, _Subscription]] = {}
        for index, sub in pairs:
            current = best.get(key(sub))
            if current is None or (sub.seen, index) >= (current[1].seen, current[0]):
                best[key(sub)] = (index, sub)
        return list(best.values())

    chosen = newest(newest(fresh, lambda s: s.did), lambda s: s.sid)
    chosen.sort(key=lambda pair: (pair[1].seen, pair[0]), reverse=True)
    chosen = sorted(chosen[: max(int(cap), 1)], key=lambda pair: pair[0])
    keep.update(index for index, _ in chosen)
    return [sub for _, sub in chosen], keep, invalid


def _strip_hidden(text: str) -> str:
    """Drops reasoning and tool blocks, including one cut off before its end."""
    kept: List[str] = []
    depth = 0
    position = 0
    for match in _HIDDEN.finditer(text):
        if depth == 0:
            kept.append(text[position:match.start()])
        closing = bool(match.group(1)) or match.group(3) == "end" or bool(match.group(4))
        depth = max(depth - 1, 0) if closing else depth + 1
        position = match.end()
    if depth == 0:
        kept.append(text[position:])
    return _SOLUTION_MARKER.sub(" ", " ".join(kept))


def _preview(raw: Any) -> str:
    """Plain-text preview of an event's Markdown text."""
    text = _text(raw)
    truncated = len(text) == EVENT_TEXT_LIMIT + 3 and text.endswith("...")
    if truncated:
        text = text[:EVENT_TEXT_LIMIT]
    text = _MENTION.sub(lambda m: m.group(1) + (m.group(3) or m.group(2)), text)
    text = cp.clean_text(_strip_hidden(text))
    return text + cp.ELLIPSIS if truncated and text else text


def _classify(status: int) -> Optional[str]:
    if 200 <= status < 300:
        return None
    if status in (404, 410):
        return "gone"
    if status == 413:
        return "too_large"
    if status == 429:
        return "rate_limited"
    if status >= 500:
        return "server_error"
    return "rejected"


def _status_key(entry: Any) -> Tuple[Any, Any, Any]:
    entry = entry if isinstance(entry, dict) else {}
    return entry.get("code"), entry.get("err"), entry.get("nonce")


def _allowed_hosts(text: str) -> Set[str]:
    return {h.strip().lower().rstrip(".") for h in re.split(r"[,\s]+", text or "") if h.strip()}


def _from_conduit(request: Any) -> bool:
    """True when the completion request came from the Conduit app."""
    try:
        headers = getattr(request, "headers", None)
        agent = headers.get("user-agent") if headers is not None else None
    except Exception:
        return False
    if not isinstance(agent, str):
        return False
    # Conduit sends a bare "Conduit" until startup has read its own version.
    agent = agent.strip()
    return agent == "Conduit" or agent.startswith("Conduit/")


def _check_public_endpoint(url: str) -> bool:
    """Open WebUI's SSRF check: blocks private, loopback and filter-listed hosts.

    It resolves DNS, so it runs in a worker thread.
    """
    try:
        from open_webui.retrieval.web.utils import validate_url
    except Exception:
        validate_url = None
    try:
        if validate_url is not None:
            return bool(validate_url(url))
        # Fallback for an Open WebUI without validate_url: every address must be public.
        host = urllib.parse.urlsplit(url).hostname
        addresses = {info[4][0] for info in socket.getaddrinfo(host, 443, 0, socket.SOCK_STREAM)}
        return bool(addresses) and all(ipaddress.ip_address(a.split("%")[0]).is_global for a in addresses)
    except Exception:
        return False


def _session_ssl() -> Any:
    try:
        from open_webui.env import AIOHTTP_CLIENT_SESSION_SSL
    except Exception:
        return None
    return AIOHTTP_CLIENT_SESSION_SSL


async def _post(session: Any, url: str, body: bytes, headers: Dict[str, str], timeout_s: float) -> int:
    import aiohttp

    options: Dict[str, Any] = {
        "data": body,
        "headers": headers,
        "timeout": aiohttp.ClientTimeout(total=float(timeout_s)),
        "allow_redirects": False,
    }
    ssl = _session_ssl()
    if ssl is not None:
        options["ssl"] = ssl
    async with session.post(url, **options) as response:
        return int(response.status)


class _Sessions(object):
    """HTTP sessions for one batch of sends, closed when the batch ends.

    Public endpoints use Open WebUI's SSRF-safe session, which re-checks every
    resolved address at connect time and so defeats DNS rebinding. Hosts the
    admin trusts use a plain session.
    """

    def __init__(self):
        self._safe = None
        self._plain = None

    def get(self, trusted: bool) -> Any:
        import aiohttp

        if trusted:
            if self._plain is None:
                self._plain = aiohttp.ClientSession(trust_env=True)
            return self._plain
        if self._safe is None:
            try:
                from open_webui.retrieval.web.utils import get_ssrf_safe_session

                self._safe = get_ssrf_safe_session()
            except Exception:
                self._safe = aiohttp.ClientSession(trust_env=True)
        return self._safe

    async def close(self) -> None:
        for session in (self._safe, self._plain):
            if session is not None:
                try:
                    await session.close()
                except Exception:
                    pass


async def _read_user_valves(function_id: str, user_id: str) -> Optional[Dict[str, Any]]:
    from open_webui.models.functions import Functions

    stored = await Functions.get_user_valves_by_id_and_user_id(function_id, user_id)
    return dict(stored) if isinstance(stored, dict) else None


class Event:
    class Valves(BaseModel):
        allow_private_endpoints: bool = Field(
            default=False,
            description=(
                "Allow push endpoints on private, local or loopback addresses, such as a "
                "UnifiedPush distributor on your LAN. Leave off unless you need it."
            ),
        )
        extra_allowed_hosts: str = Field(
            default="",
            description="Comma-separated host names that skip the private-address check, e.g. ntfy.home.arpa.",
        )
        max_subscriptions_per_user: int = Field(
            default=10, ge=1, le=100, description="How many devices each user can register."
        )
        timeout_s: float = Field(default=5, gt=0, le=60, description="Seconds to wait for each push endpoint.")
        max_channel_recipients: int = Field(
            default=500,
            ge=0,
            le=10000,
            description="The most people one channel message notifies. 0 turns channel notifications off.",
        )

    class UserValves(BaseModel):
        subscriptions: str = Field(default="[]", description="Managed by Conduit. Do not edit.")
        status: str = Field(default="{}", description="Delivery status for Conduit. Do not edit.")

    def __init__(self):
        self.valves = self.Valves()
        self._tasks: Set[asyncio.Task] = set()
        self._loop: Any = None
        self._semaphore: Any = None
        self._locks: Any = weakref.WeakValueDictionary()
        self._nonces: "OrderedDict[str, bool]" = OrderedDict()
        self._ssrf_cache: "OrderedDict[str, Tuple[bool, float]]" = OrderedDict()
        self._warned: Set[str] = set()

    async def event(self, event, __event_name__=None, __request__=None, __id__=None, **kwargs):
        """Called by Open WebUI for every event. Returns at once; sends run in the background."""
        try:
            self._dispatch(event, __event_name__, __request__, __id__)
        except Exception as error:
            log.warning("conduit push: could not handle an event (%s)", type(error).__name__)

    def _dispatch(self, event: Any, name: Any, request: Any, function_id: Any) -> None:
        if not isinstance(event, dict):
            return
        name = name or event.get("event")
        if name not in ("chat.finished", "chat.failed", "message.created", "function.valves_updated"):
            return
        function_id = function_id or (__name__[len("function_"):] if __name__.startswith("function_") else "conduit_push")
        data = event.get("data") if isinstance(event.get("data"), dict) else {}
        actor = event.get("actor") if isinstance(event.get("actor"), dict) else {}
        subject = event.get("subject") if isinstance(event.get("subject"), dict) else {}
        valves = self.valves
        self._bind_loop()

        if name in ("chat.finished", "chat.failed"):
            self._spawn("reply", self._on_chat(function_id, name, data, _from_conduit(request), valves))
        elif name == "message.created":
            if data.get("channel_id") and _text(subject.get("id")):
                self._spawn("channel", self._on_channel(function_id, data, actor, subject["id"], valves))
        elif subject.get("id") == function_id and data.get("scope") == "user" and _text(actor.get("id")):
            self._spawn("subscribe", self._on_valves_updated(function_id, actor["id"], valves))

    def _bind_loop(self) -> None:
        loop = asyncio.get_running_loop()
        if self._loop is not loop:
            self._loop = loop
            self._semaphore = asyncio.Semaphore(SEND_CONCURRENCY)
            self._locks = weakref.WeakValueDictionary()

    def _spawn(self, label: str, job: Any) -> None:
        if len(self._tasks) >= MAX_PENDING_JOBS:
            job.close()
            log.warning("conduit push: too many notifications in flight, dropped one")
            return
        task = asyncio.ensure_future(self._guard(label, job))
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)

    async def _guard(self, label: str, job: Any) -> None:
        try:
            await job
        except asyncio.CancelledError:
            raise
        except Exception as error:
            log.warning("conduit push: %s failed (%s)", label, type(error).__name__)

    async def _wait_idle(self) -> None:
        """Waits for every notification in flight. Used by tests."""
        while self._tasks:
            await asyncio.gather(*list(self._tasks), return_exceptions=True)

    def _warn_once(self, key: str, message: str) -> None:
        if key not in self._warned:
            self._warned.add(key)
            log.warning(message)

    def _user_lock(self, user_id: str) -> asyncio.Lock:
        lock = self._locks.get(user_id)
        if lock is None:
            lock = asyncio.Lock()
            self._locks[user_id] = lock
        return lock

    def _claim_nonce(self, user_id: str, sid: str, nonce: str) -> bool:
        key = user_id + "|" + sid + "|" + nonce
        if key in self._nonces:
            return False
        self._nonces[key] = True
        while len(self._nonces) > NONCE_MEMORY:
            self._nonces.popitem(last=False)
        return True

    # Events

    async def _on_chat(self, function_id: str, name: str, data: Dict[str, Any], from_conduit: bool, valves: Any) -> None:
        user_id, chat_id, message_id = (_text(data.get(k)) for k in ("user_id", "chat_id", "message_id"))
        if not (user_id and chat_id and message_id):
            return
        kind = "reply" if name == "chat.finished" else "reply_failed"
        stored = await _read_user_valves(function_id, user_id)
        targets = [
            sub
            for sub in self._usable(stored, valves)
            if kind in sub.events and (sub.origin == "any" or from_conduit)
        ]
        if not targets:
            return
        if kind == "reply":
            title, body = _text(data.get("title")), _preview(data.get("message"))
        else:
            title, body = await self._chat_title(chat_id), ""
        note = cp.build(
            kind,
            SOURCE,
            ids={"chat": chat_id, "msg": message_id},
            title=title,
            body=body,
            dedup_key="chat:" + chat_id + ":" + message_id,
            group="chat:" + chat_id,
            clean=False,
        )
        await self._deliver(function_id, {user_id: [(sub, note) for sub in targets]}, valves)

    async def _on_channel(
        self, function_id: str, data: Dict[str, Any], actor: Dict[str, Any], message_id: str, valves: Any
    ) -> None:
        limit = int(valves.max_channel_recipients)
        if limit <= 0:
            return
        from open_webui.models.channels import Channels
        from open_webui.models.messages import Messages

        channel_id = _text(data.get("channel_id"))
        try:
            message = await Messages.get_message_by_id(message_id, include_thread_replies=False)
        except TypeError:
            message = await Messages.get_message_by_id(message_id)
        if message is None or _attr(message, "channel_id") != channel_id:
            return
        if _attr(message, "parent_id"):
            return  # Thread replies don't notify.
        channel = await Channels.get_channel_by_id(channel_id)
        if channel is None or _attr(channel, "deleted_at") or _attr(channel, "archived_at"):
            return

        members = await Channels.get_members_by_channel_id(channel_id) or []
        recipients = list(
            dict.fromkeys(
                _text(_attr(m, "user_id")) for m in members if not _attr(m, "is_channel_muted")
            )
        )
        kind = _attr(channel, "type")
        if kind not in ("dm", "group"):
            # Standard channels: members who still have read access, as Open WebUI's
            # own channel notifications do. Group and DM access is membership.
            allowed = await self._read_access(channel)
            if allowed is not None:
                recipients = [uid for uid in recipients if uid in allowed]
        sender_id = None if actor.get("type") == "webhook" else (_text(actor.get("id")) or _text(_attr(message, "user_id")))
        recipients = [uid for uid in recipients if uid and uid != sender_id][:limit]
        if not recipients:
            return

        sender = _text(actor.get("name")) or _text(_attr(_attr(message, "user"), "name"))
        channel_name = _text(_attr(channel, "name"))
        title = sender if kind == "dm" or not channel_name else "#" + channel_name
        note = cp.build(
            "channel",
            SOURCE,
            ids={"channel": channel_id, "msg": message_id},
            title=title,
            body=_preview(_attr(message, "content") or data.get("content_preview")),
            author=sender or None,
            dedup_key="channel:" + channel_id + ":" + message_id,
            group="channel:" + channel_id,
            clean=False,
        )
        stored = await self._read_many_user_valves(function_id, recipients)
        work = {}
        for uid in recipients:
            jobs = [(sub, note) for sub in self._usable(stored.get(uid), valves) if "channel" in sub.events]
            if jobs:
                work[uid] = jobs
        if work:
            await self._deliver(function_id, work, valves)

    async def _on_valves_updated(self, function_id: str, user_id: str, valves: Any) -> None:
        """A user saved this function's valves, normally Conduit subscribing a device."""
        stored = await _read_user_valves(function_id, user_id)
        if stored is None:
            return
        raw_list = _parse_list(stored.get("subscriptions"))
        if raw_list is None:
            return
        status = _parse_dict(stored.get("status"))
        now = int(time.time())
        subs, _, invalid = _select(raw_list, now, valves.max_subscriptions_per_user)
        notes = {sid: {"code": None, "at": now, "err": "invalid"} for sid in invalid}
        jobs = []
        for sub in subs:
            pending = sub.nonce and not (sub.test_at and now - sub.test_at > TEST_MAX_AGE_S)
            handled = _attr(status.get(sub.sid), "nonce") == sub.nonce
            if pending and not handled:
                if self._claim_nonce(user_id, sub.sid, sub.nonce):
                    test = cp.build(
                        "test", SOURCE, ids={}, title="", body="", dedup_key="test:" + sub.nonce, nonce=sub.nonce
                    )
                    jobs.append((sub, test))
            elif not self._trusted(sub, valves) and not await self._endpoint_is_public(sub.endpoint):
                notes[sub.sid] = {"code": None, "at": now, "err": "blocked"}
        await self._deliver(function_id, {user_id: jobs}, valves, notes={user_id: notes})

    # Loading

    def _usable(self, stored: Optional[Dict[str, Any]], valves: Any) -> List[_Subscription]:
        if not isinstance(stored, dict):
            return []
        raw_list = _parse_list(stored.get("subscriptions"))
        if not raw_list:
            return []
        return _select(raw_list, int(time.time()), valves.max_subscriptions_per_user)[0]

    async def _chat_title(self, chat_id: str) -> str:
        try:
            from open_webui.models.chats import Chats

            return _text(await Chats.get_chat_title_by_id(chat_id))
        except Exception:
            return ""

    async def _read_access(self, channel: Any) -> Optional[Set[str]]:
        """Ids of users with read access, or None when Open WebUI has no such helper."""
        try:
            from open_webui.routers.channels import get_channel_users_with_access
        except Exception:
            self._warn_once("access", "conduit push: channel access helper missing, notifying channel members")
            return None
        users = await get_channel_users_with_access(channel, "read")
        return {_text(_attr(user, "id")) for user in users or []}

    async def _read_many_user_valves(self, function_id: str, user_ids: List[str]) -> Dict[str, Dict[str, Any]]:
        """Every recipient's valves for this function, in one query when possible."""
        try:
            from open_webui.models.users import Users

            users = await Users.get_users_by_user_ids(list(user_ids))
        except Exception:
            users = None
        try:
            from open_webui.utils.valves import decrypt_valves
        except Exception:
            decrypt_valves = None

        found: Dict[str, Dict[str, Any]] = {}
        slow: List[str] = list(user_ids) if users is None else []
        for user in users or []:
            settings = _attr(user, "settings")
            if hasattr(settings, "model_dump"):
                settings = settings.model_dump()
            functions = settings.get("functions") if isinstance(settings, dict) else None
            valve_map = functions.get("valves") if isinstance(functions, dict) else None
            stored = valve_map.get(function_id) if isinstance(valve_map, dict) else None
            if isinstance(stored, str) and stored:
                if decrypt_valves is None:
                    slow.append(_text(_attr(user, "id")))
                    continue
                stored = decrypt_valves(stored)
            if isinstance(stored, dict) and stored:
                found[_text(_attr(user, "id"))] = stored
        for user_id in slow:
            stored = await _read_user_valves(function_id, user_id)
            if stored:
                found[user_id] = stored
        return found

    # Sending

    def _trusted(self, sub: _Subscription, valves: Any) -> bool:
        return bool(valves.allow_private_endpoints) or sub.host in _allowed_hosts(valves.extra_allowed_hosts)

    async def _endpoint_is_public(self, url: str) -> bool:
        now = time.monotonic()
        cached = self._ssrf_cache.get(url)
        if cached is not None and cached[1] > now:
            return cached[0]
        allowed = await asyncio.to_thread(_check_public_endpoint, url)
        self._ssrf_cache[url] = (allowed, now + (SSRF_OK_TTL_S if allowed else SSRF_BLOCKED_TTL_S))
        self._ssrf_cache.move_to_end(url)
        while len(self._ssrf_cache) > SSRF_CACHE_SIZE:
            self._ssrf_cache.popitem(last=False)
        return allowed

    async def _deliver(
        self,
        function_id: str,
        work: Dict[str, List[Tuple[_Subscription, Dict[str, Any]]]],
        valves: Any,
        notes: Optional[Dict[str, Dict[str, Dict[str, Any]]]] = None,
    ) -> None:
        sessions = _Sessions()
        try:
            results = await asyncio.gather(
                *(
                    self._deliver_user(function_id, user_id, jobs, valves, sessions, (notes or {}).get(user_id))
                    for user_id, jobs in work.items()
                ),
                return_exceptions=True,
            )
        finally:
            await sessions.close()
        for result in results:
            if isinstance(result, Exception):
                log.warning("conduit push: delivery failed (%s)", type(result).__name__)

    async def _deliver_user(
        self,
        function_id: str,
        user_id: str,
        jobs: List[Tuple[_Subscription, Dict[str, Any]]],
        valves: Any,
        sessions: _Sessions,
        notes: Optional[Dict[str, Dict[str, Any]]],
    ) -> None:
        results = await asyncio.gather(*(self._send(sessions, sub, note, valves) for sub, note in jobs))
        now = int(time.time())
        statuses = dict(notes or {})
        dead: Set[Tuple[str, str]] = set()
        for (sub, note), (code, err) in zip(jobs, results):
            entry = {"code": code, "at": now, "err": err}
            if note.get("k") == "test":
                entry["nonce"] = note.get("n")
            statuses[sub.sid] = entry
            if err == "gone":
                dead.add((sub.sid, sub.endpoint))
        failed = sum(1 for _, err in results if err)
        if failed:
            log.info("conduit push: %d of %d sends failed", failed, len(results))
        await self._commit(function_id, user_id, valves, statuses, dead)

    async def _send(
        self, sessions: _Sessions, sub: _Subscription, note: Dict[str, Any], valves: Any
    ) -> Tuple[Optional[int], Optional[str]]:
        """Encrypts and posts one notification. Returns (HTTP status, error category)."""
        async with self._semaphore:
            try:
                trusted = self._trusted(sub, valves)
                if not trusted and not await self._endpoint_is_public(sub.endpoint):
                    return None, "blocked"
                try:
                    body = cp.seal(note, {"p256dh": sub.p256dh, "auth": sub.auth})
                except Exception:
                    return None, "encrypt"
                headers = webpush.headers(note["k"], sub.auth_bytes, note["dk"])
                status = await _post(sessions.get(trusted), sub.endpoint, body, headers, valves.timeout_s)
            except asyncio.CancelledError:
                raise
            except asyncio.TimeoutError:
                return None, "timeout"
            except ValueError:
                return None, "blocked"  # Open WebUI's connector refused the resolved address.
            except Exception:
                return None, "network"
            return status, _classify(status)

    async def _commit(
        self,
        function_id: str,
        user_id: str,
        valves: Any,
        statuses: Dict[str, Dict[str, Any]],
        dead: Set[Tuple[str, str]],
    ) -> None:
        """Records delivery status and prunes dead or stale subscriptions.

        Reads the valves again under a per-user lock, so a device that subscribed
        meanwhile is kept. Writes only when something changed, through the model
        method, which doesn't publish an event, so nothing loops.
        """
        from open_webui.models.functions import Functions

        async with self._user_lock(user_id):
            stored = await _read_user_valves(function_id, user_id)
            if stored is None:
                return
            raw_list = _parse_list(stored.get("subscriptions"))
            status = _parse_dict(stored.get("status"))
            changed = False
            if raw_list is not None:
                _, keep, _ = _select(raw_list, int(time.time()), valves.max_subscriptions_per_user)
                kept = [
                    raw
                    for index, raw in enumerate(raw_list)
                    if index in keep and (_attr(raw, "sid"), _attr(raw, "endpoint")) not in dead
                ]
                if len(kept) != len(raw_list):
                    stored["subscriptions"] = _dumps(kept)
                    changed = True
                live = {_attr(raw, "sid") for raw in kept} | set(statuses)
                for sid in [sid for sid in status if sid not in live]:
                    del status[sid]
                    changed = True
            for sid, entry in statuses.items():
                previous = status.get(sid) if isinstance(status.get(sid), dict) else {}
                entry = dict(entry)
                if "nonce" not in entry and isinstance(previous.get("nonce"), str):
                    entry["nonce"] = previous["nonce"]
                if not previous or _status_key(previous) != _status_key(entry):
                    status[sid] = entry
                    changed = True
            if not changed:
                return
            stored["status"] = _dumps(status)
            await Functions.update_user_valves_by_id_and_user_id(function_id, user_id, stored)
