import 'palette.dart';
import 'registry.dart';

/// Prefix for the raw palette variables the app overrides at runtime.
///
/// Kept distinct from Tailwind's own `--color-*` namespace so the two layers
/// stay separable: Tailwind reads `--color-background`, which is aliased to
/// `--conduit-background`, which is what a `[data-palette]` rule rewrites.
const String kThemeVarPrefix = '--conduit-';

/// Renders the whole palette registry as a Tailwind v4 stylesheet.
///
/// The shape is the shadcn/Tailwind-v4 idiom:
///
/// * `@theme inline` aliases each Tailwind token to a `--conduit-*` variable,
///   so Tailwind generates `bg-background` and friends *referencing* the
///   variable rather than inlining a literal colour. Without `inline`,
///   Tailwind would bake today's value into every utility and runtime palette
///   switching would do nothing.
/// * One rule per palette sets the light values; a `[data-mode="dark"]`
///   rule overrides them.
/// * `data-mode="system"` is handled by `prefers-color-scheme`, so following
///   the OS costs no JavaScript and survives a change while the app is open.
///
/// Switching palettes at runtime is therefore two attribute writes on
/// `<html>`: `data-palette` and `data-mode`.
String generateThemeCss({
  List<ThemePalette> palettes = kConduitPalettes,
  ThemePalette? fallback,
}) {
  final defaultPalette = fallback ?? palettes.first;
  final buffer = StringBuffer()
    ..writeln('/* GENERATED by package:conduit_theme.')
    ..writeln(' *')
    ..writeln(' * Run `dart run conduit_theme:generate_theme_css` from the')
    ..writeln(' * repo root after changing a palette. Do not edit by hand.')
    ..writeln(' */')
    ..writeln()
    ..writeln('@theme inline {');
  for (final token in defaultPalette.light.colors.keys) {
    buffer.writeln(
      '  --color-${_kebab(token)}: var($kThemeVarPrefix${_kebab(token)});',
    );
  }
  buffer
    ..writeln('  --radius: var(${kThemeVarPrefix}radius);')
    ..writeln('}')
    ..writeln()
    ..writeln('/* Defaults, used before the app sets data-palette. */')
    ..writeln(_block(':root', defaultPalette.light))
    ..writeln('@media (prefers-color-scheme: dark) {')
    ..writeln(_indent(_block(':root', defaultPalette.dark)))
    ..writeln('}');

  for (final palette in palettes) {
    final selector = '[data-palette="${palette.id}"]';
    buffer
      ..writeln()
      ..writeln('/* ${palette.id} */')
      ..writeln(
        _block('$selector,\n$selector[data-mode="light"]', palette.light),
      )
      ..writeln(_block('$selector[data-mode="dark"]', palette.dark))
      ..writeln('@media (prefers-color-scheme: dark) {')
      ..writeln(
        _indent(_block('$selector[data-mode="system"]', palette.dark)),
      )
      ..writeln('}');
  }
  return buffer.toString();
}

String _block(String selector, ThemeVariant variant) {
  final buffer = StringBuffer('$selector {\n');
  variant.colors.forEach((token, argb) {
    buffer.writeln('  $kThemeVarPrefix${_kebab(token)}: ${cssColor(argb)};');
  });
  buffer
    ..writeln('  ${kThemeVarPrefix}radius: ${_px(variant.radius)};')
    ..write('}\n');
  return buffer.toString();
}

/// Formats an ARGB integer the way CSS wants it.
///
/// Fully opaque colours become `#rrggbb` — shorter, and what a designer
/// expects to see when they open the file. Anything else becomes
/// `rgb(r g b / a)`, since `#rrggbbaa` is still not universally safe in
/// author-facing tooling.
String cssColor(int argb) {
  final a = (argb >> 24) & 0xFF;
  final r = (argb >> 16) & 0xFF;
  final g = (argb >> 8) & 0xFF;
  final b = argb & 0xFF;
  if (a == 0xFF) {
    return '#${_hex(r)}${_hex(g)}${_hex(b)}';
  }
  final alpha = (a / 255).toStringAsFixed(3).replaceFirst(RegExp(r'0+$'), '');
  return 'rgb($r $g $b / ${alpha.endsWith('.') ? '${alpha}0' : alpha})';
}

String _hex(int value) => value.toRadixString(16).padLeft(2, '0');

String _px(double value) =>
    value == value.roundToDouble() ? '${value.round()}px' : '${value}px';

/// `sidebarPrimaryForeground` -> `sidebar-primary-foreground`.
String _kebab(String camel) => camel
    .replaceAllMapped(
      RegExp('([a-z0-9])([A-Z])'),
      (m) => '${m[1]}-${m[2]!.toLowerCase()}',
    )
    .toLowerCase();

String _indent(String block) => block
    .trimRight()
    .split('\n')
    .map((line) => line.isEmpty ? line : '  $line')
    .join('\n');
