// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `internal`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AuthStateInfo {
  final bool authenticated;
  final String? email;
  final String? planType;
  final String? accountId;
  final String? accountFingerprint;

  const AuthStateInfo({
    required this.authenticated,
    this.email,
    this.planType,
    this.accountId,
    this.accountFingerprint,
  });

  @override
  int get hashCode =>
      authenticated.hashCode ^
      email.hashCode ^
      planType.hashCode ^
      accountId.hashCode ^
      accountFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStateInfo &&
          runtimeType == other.runtimeType &&
          authenticated == other.authenticated &&
          email == other.email &&
          planType == other.planType &&
          accountId == other.accountId &&
          accountFingerprint == other.accountFingerprint;
}

class BridgeError implements FrbException {
  final BridgeErrorKind kind;
  final String message;
  final int? retryAfterSeconds;

  const BridgeError({
    required this.kind,
    required this.message,
    this.retryAfterSeconds,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ message.hashCode ^ retryAfterSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          retryAfterSeconds == other.retryAfterSeconds;
}

enum BridgeErrorKind {
  invalidInput,
  authentication,
  network,
  rateLimit,
  unsupported,
  cancellation,
  protocolMismatch,
  internal,
}

class DeviceCodeChallenge {
  final String loginId;
  final String verificationUrl;
  final String userCode;

  const DeviceCodeChallenge({
    required this.loginId,
    required this.verificationUrl,
    required this.userCode,
  });

  @override
  int get hashCode =>
      loginId.hashCode ^ verificationUrl.hashCode ^ userCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeChallenge &&
          runtimeType == other.runtimeType &&
          loginId == other.loginId &&
          verificationUrl == other.verificationUrl &&
          userCode == other.userCode;
}

class ModelInfo {
  final String id;
  final String displayName;
  final String description;
  final bool supportsImages;
  final bool supportsAudio;
  final List<String> supportedReasoningEfforts;
  final String? defaultReasoningEffort;

  const ModelInfo({
    required this.id,
    required this.displayName,
    required this.description,
    required this.supportsImages,
    required this.supportsAudio,
    required this.supportedReasoningEfforts,
    this.defaultReasoningEffort,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      supportsImages.hashCode ^
      supportsAudio.hashCode ^
      supportedReasoningEfforts.hashCode ^
      defaultReasoningEffort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          supportsImages == other.supportsImages &&
          supportsAudio == other.supportsAudio &&
          supportedReasoningEfforts == other.supportedReasoningEfforts &&
          defaultReasoningEffort == other.defaultReasoningEffort;
}

class RunInfo {
  final String runId;
  final String sessionId;

  const RunInfo({required this.runId, required this.sessionId});

  @override
  int get hashCode => runId.hashCode ^ sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunInfo &&
          runtimeType == other.runtimeType &&
          runId == other.runId &&
          sessionId == other.sessionId;
}

class RuntimeEvent {
  final BigInt clientEpoch;
  final BigInt sequence;
  final RuntimeEventKind kind;
  final String? runId;
  final String? sessionId;
  final String? itemId;
  final String? text;

  /// Sanitized structured metadata. Authentication material is never placed here.
  final String? jsonData;

  /// Used only by generated media and opaque auth mutation snapshots.
  final Uint8List? binaryData;

  const RuntimeEvent({
    required this.clientEpoch,
    required this.sequence,
    required this.kind,
    this.runId,
    this.sessionId,
    this.itemId,
    this.text,
    this.jsonData,
    this.binaryData,
  });

  @override
  int get hashCode =>
      clientEpoch.hashCode ^
      sequence.hashCode ^
      kind.hashCode ^
      runId.hashCode ^
      sessionId.hashCode ^
      itemId.hashCode ^
      text.hashCode ^
      jsonData.hashCode ^
      binaryData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeEvent &&
          runtimeType == other.runtimeType &&
          clientEpoch == other.clientEpoch &&
          sequence == other.sequence &&
          kind == other.kind &&
          runId == other.runId &&
          sessionId == other.sessionId &&
          itemId == other.itemId &&
          text == other.text &&
          jsonData == other.jsonData &&
          binaryData == other.binaryData;
}

enum RuntimeEventKind {
  authState,
  authMutationRequired,
  loginCompleted,
  turnStarted,
  textDelta,
  reasoningDelta,
  source,
  generatedImage,
  usage,
  checkpointUpdated,
  cancelled,
  completed,
  failure,
  diagnostic,
}

class TurnInputPart {
  /// `text`, `image`, `audio`, or `document`.
  final String kind;
  final String? text;
  final String? filename;
  final String? mimeType;
  final Uint8List? bytes;

  const TurnInputPart({
    required this.kind,
    this.text,
    this.filename,
    this.mimeType,
    this.bytes,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      text.hashCode ^
      filename.hashCode ^
      mimeType.hashCode ^
      bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TurnInputPart &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          filename == other.filename &&
          mimeType == other.mimeType &&
          bytes == other.bytes;
}

class TurnMessage {
  final TurnMessageRole role;
  final String? messageId;
  final List<TurnInputPart> parts;

  const TurnMessage({required this.role, this.messageId, required this.parts});

  @override
  int get hashCode => role.hashCode ^ messageId.hashCode ^ parts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TurnMessage &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          messageId == other.messageId &&
          parts == other.parts;
}

enum TurnMessageRole { system, user, assistant }

class TurnRequest {
  final String sessionId;
  final String modelId;
  final String? reasoningEffort;
  final bool enableWebSearch;
  final bool enableImageGeneration;
  final List<TurnMessage> messages;
  final Uint8List? checkpoint;
  final BigInt? previousInputTokens;

  const TurnRequest({
    required this.sessionId,
    required this.modelId,
    this.reasoningEffort,
    required this.enableWebSearch,
    required this.enableImageGeneration,
    required this.messages,
    this.checkpoint,
    this.previousInputTokens,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      modelId.hashCode ^
      reasoningEffort.hashCode ^
      enableWebSearch.hashCode ^
      enableImageGeneration.hashCode ^
      messages.hashCode ^
      checkpoint.hashCode ^
      previousInputTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TurnRequest &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          modelId == other.modelId &&
          reasoningEffort == other.reasoningEffort &&
          enableWebSearch == other.enableWebSearch &&
          enableImageGeneration == other.enableImageGeneration &&
          messages == other.messages &&
          checkpoint == other.checkpoint &&
          previousInputTokens == other.previousInputTokens;
}
