// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_fingerprint`, `api_error_body`, `api_error_class`, `api_error_status`, `auth_event`, `auth_state_info`, `bounded`, `build`, `cancel_all_work`, `cancel_device_code_login_inner`, `cancellable_api`, `cancellable_bridge`, `cancellation_error`, `checkpoint_mismatch`, `classify_login_failure`, `classify_provider_error_detail`, `coalesce_delta`, `compact_history`, `current_auth_snapshot`, `data_url`, `decode_checkpoint`, `device_login_options`, `emit_checkpoint`, `emit_sources`, `emit`, `encode_messages`, `encode_part`, `enqueue`, `escape_attribute`, `event`, `execute_image_tool`, `execute_response_loop`, `execute_turn`, `execute_web_tool`, `finish_run`, `flush_pending`, `hex_prefix`, `image_tool_spec`, `install_auth_snapshot`, `into_bridge`, `is_unauthorized`, `map_api_error`, `map_turn_api_error`, `model_compact_limit`, `new`, `persist_current_auth`, `prepare_auth`, `recent_image_urls`, `refresh_after_unauthorized`, `remove_queued`, `report_api_failure`, `request_auth_mutation`, `request_image`, `response_api_request`, `response_options`, `response_wire_config`, `restore_auth`, `run_event`, `runtime_handle`, `safe_web_url`, `sanitized_diagnostic_token`, `shutdown_runtime_inner`, `snapshot_hash`, `spawn_run`, `standalone_image_edit_request`, `standalone_image_generation_request`, `standalone_search_input`, `standalone_search_request`, `subscribe`, `take_next_ready`, `tool_policy_hash`, `tool_specs`, `tool_text_output`, `try_coalesce_delta`, `turn_request_size`, `validate_checkpoint_items`, `validate_identifier`, `validate_turn_request`, `validated_binary`, `validated_image_tool_args`, `validated_image`, `validated_mime`, `web_tool_spec`, `with_binary`, `with_item`, `with_json`, `with_optional_binary`, `with_text`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveLogin`, `ActiveRun`, `CachedModels`, `CheckpointEnvelope`, `DynamicBearerAuth`, `EventHub`, `ImageToolArgs`, `PendingAuthMutation`, `QueuedRun`, `ResponseWireConfig`, `RuntimeEventBuilder`, `RuntimeHandle`, `TurnExecutionError`, `TurnScheduler`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `add_auth_headers`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<int> bridgeProtocolVersion() =>
    RustLib.instance.api.crateApiRuntimeBridgeProtocolVersion();

Future<void> initializeRuntime({
  required BigInt clientEpoch,
  Uint8List? authSnapshot,
}) => RustLib.instance.api.crateApiRuntimeInitializeRuntime(
  clientEpoch: clientEpoch,
  authSnapshot: authSnapshot,
);

Stream<RuntimeEvent> runtimeEvents({required BigInt clientEpoch}) =>
    RustLib.instance.api.crateApiRuntimeRuntimeEvents(clientEpoch: clientEpoch);

Future<AuthStateInfo> authState() =>
    RustLib.instance.api.crateApiRuntimeAuthState();

Future<DeviceCodeChallenge> beginDeviceCodeLogin() =>
    RustLib.instance.api.crateApiRuntimeBeginDeviceCodeLogin();

Future<void> cancelDeviceCodeLogin() =>
    RustLib.instance.api.crateApiRuntimeCancelDeviceCodeLogin();

Future<List<ModelInfo>> listModels() =>
    RustLib.instance.api.crateApiRuntimeListModels();

Future<RunInfo> startTurn({required TurnRequest request}) =>
    RustLib.instance.api.crateApiRuntimeStartTurn(request: request);

Future<void> interruptTurn({required String runId}) =>
    RustLib.instance.api.crateApiRuntimeInterruptTurn(runId: runId);

Future<void> ackAuthMutation({
  required String mutationId,
  required bool persisted,
}) => RustLib.instance.api.crateApiRuntimeAckAuthMutation(
  mutationId: mutationId,
  persisted: persisted,
);

Future<void> disconnectAccount() =>
    RustLib.instance.api.crateApiRuntimeDisconnectAccount();

Future<void> shutdownRuntime() =>
    RustLib.instance.api.crateApiRuntimeShutdownRuntime();
