// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blank_event`, `bounded_string`, `chatgpt_account_id`, `classify_protocol_error`, `context_snapshot`, `data_url`, `drain_queued`, `emit_runtime_event`, `emit`, `encode_turn_inputs`, `encoded_inputs_size`, `enqueue`, `escaped_document_text`, `event_with_ids`, `expire_stalled_runs`, `fail_all_runtime_runs`, `finish_scheduled_run`, `generated_image_bytes`, `generated_image_media_type`, `hex_prefix`, `install_auth_snapshot`, `item_label`, `json_string_at`, `map_notification`, `maybe_request_auth_persistence`, `merge_or_flush_delta`, `new`, `notification_ids`, `parse_auth_state`, `pop_queued`, `release_and_take_next`, `remove_queued`, `request_auth_persistence`, `required_nested_string`, `required_string`, `rpc`, `run_queued_chain`, `runtime_not_initialized`, `safe_web_url`, `sanitized_account_json`, `sanitized_document_attribute`, `sanitized_error_json`, `sanitized_generated_image_json`, `sanitized_item_json`, `sanitized_json`, `sanitized_source_json`, `sanitized_usage_json`, `sanitized_warning`, `shutdown_runtime_inner`, `snapshot_hash`, `start_native_turn`, `start_next_queued_run`, `subscribe`, `take_next_ready_run`, `touch_active_run`, `validate_client_epoch`, `validate_identifier`, `validated_media_type`, `validated_runtime_root`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveRun`, `EventContext`, `EventHub`, `NotificationIds`, `PendingAuthMutation`, `PendingDelta`, `QueuedRun`, `RuntimeHandle`, `TurnScheduler`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<int> bridgeProtocolVersion() =>
    RustLib.instance.api.crateApiRuntimeBridgeProtocolVersion();

Future<void> initializeRuntime({
  required BigInt clientEpoch,
  required String dataDirectory,
  Uint8List? authSnapshot,
}) => RustLib.instance.api.crateApiRuntimeInitializeRuntime(
  clientEpoch: clientEpoch,
  dataDirectory: dataDirectory,
  authSnapshot: authSnapshot,
);

Stream<RuntimeEvent> runtimeEvents({required BigInt clientEpoch}) =>
    RustLib.instance.api.crateApiRuntimeRuntimeEvents(clientEpoch: clientEpoch);

Future<AuthStateInfo> authState() =>
    RustLib.instance.api.crateApiRuntimeAuthState();

Future<DeviceCodeChallenge> beginDeviceCodeLogin() =>
    RustLib.instance.api.crateApiRuntimeBeginDeviceCodeLogin();

Future<void> cancelDeviceCodeLogin() =>
    RustLib.instance.api.crateApiRuntimeCancelDeviceCodeLogin();

Future<List<ModelInfo>> listModels() =>
    RustLib.instance.api.crateApiRuntimeListModels();

Future<ThreadInfo> startThread({
  required String modelId,
  required bool enableWebSearch,
  required bool enableImageGeneration,
}) => RustLib.instance.api.crateApiRuntimeStartThread(
  modelId: modelId,
  enableWebSearch: enableWebSearch,
  enableImageGeneration: enableImageGeneration,
);

Future<ThreadInfo> resumeThread({required String threadId}) =>
    RustLib.instance.api.crateApiRuntimeResumeThread(threadId: threadId);

Future<ThreadInfo> forkThread({required String threadId, String? turnId}) =>
    RustLib.instance.api.crateApiRuntimeForkThread(
      threadId: threadId,
      turnId: turnId,
    );

Future<RunInfo> startTurn({required TurnRequest request}) =>
    RustLib.instance.api.crateApiRuntimeStartTurn(request: request);

Future<void> interruptTurn({required String runId}) =>
    RustLib.instance.api.crateApiRuntimeInterruptTurn(runId: runId);

Future<void> ackAuthMutation({
  required String mutationId,
  required bool persisted,
}) => RustLib.instance.api.crateApiRuntimeAckAuthMutation(
  mutationId: mutationId,
  persisted: persisted,
);

Future<void> disconnectAccount() =>
    RustLib.instance.api.crateApiRuntimeDisconnectAccount();

Future<void> shutdownRuntime() =>
    RustLib.instance.api.crateApiRuntimeShutdownRuntime();
