/// Picks a Direct model's avatar from the models.dev logos bundled with the
/// app (`assets/model_logos`, regenerated by `tool/generate_model_logos.dart`).
///
/// A model gets its maker's logo, found from, in order: a `lab/model` id
/// prefix, the models.dev model index, or a family prefix (`llama3.2` is
/// Meta's). A model whose maker is unknown gets the logo of the provider it
/// is served by, matched on the connection's API host.
final class ModelLogoCatalog {
  ModelLogoCatalog({
    required Map<String, String> logos,
    Map<String, String> labAliases = const {},
    List<(String, String)> families = const [],
    Map<String, String> hosts = const {},
    Map<String, String> models = const {},
  }) : logos = Map.unmodifiable(logos),
       _labAliases = Map.unmodifiable(labAliases),
       _families = List.unmodifiable(families),
       _hosts = Map.unmodifiable(hosts),
       _models = Map.unmodifiable(models);

  /// Parses `catalog.json`. Malformed sections are skipped, not fatal.
  factory ModelLogoCatalog.fromJson(Map<String, dynamic> json) {
    Map<String, String> strings(Object? value) => {
      if (value is Map)
        for (final entry in value.entries)
          if (entry.value is String) '${entry.key}': entry.value as String,
    };
    final families = <(String, String)>[
      if (json['families'] case final List<dynamic> list)
        for (final pair in list)
          if (pair case [final String prefix, final String lab]) (prefix, lab),
    ];
    return ModelLogoCatalog(
      logos: strings(json['logos']),
      labAliases: strings(json['labAliases']),
      families: families,
      hosts: strings(json['hosts']),
      models: strings(json['models']),
    );
  }

  /// Logo id → the maker or provider's display name.
  final Map<String, String> logos;
  final Map<String, String> _labAliases;
  final List<(String, String)> _families;
  final Map<String, String> _hosts;
  final Map<String, String> _models;

  /// The logo id for a model, or `null` for the lettered fallback.
  ///
  /// [baseHost] is the connection's API host; [adapterKey] lets any Ollama
  /// server fall back to Ollama's logo.
  String? logoFor({
    required String remoteModelId,
    String? baseHost,
    String? adapterKey,
  }) {
    final id = remoteModelId.trim().toLowerCase();
    if (id.isEmpty) return _providerLogo(baseHost, adapterKey);

    final segments = id.split('/');
    if (segments.length > 1) {
      final lab = _lab(segments.first);
      if (lab != null) return lab;
    }

    final name = segments.last;
    final untagged = name.split(':').first;
    final indexed = _known(_models[name]) ?? _known(_models[untagged]);
    if (indexed != null) return indexed;

    for (final (prefix, lab) in _families) {
      if (untagged.startsWith(prefix)) return _known(lab);
    }
    return _providerLogo(baseHost, adapterKey);
  }

  String? _lab(String prefix) => _known(_labAliases[prefix] ?? prefix);

  String? _providerLogo(String? baseHost, String? adapterKey) {
    final host = baseHost?.trim().toLowerCase();
    if (host != null && host.isNotEmpty) {
      final byHost = _known(_hosts[host]);
      if (byHost != null) return byHost;
    }
    if (adapterKey == 'ollama') return _known('ollama-cloud');
    return null;
  }

  String? _known(String? id) => id != null && logos.containsKey(id) ? id : null;
}
