import CryptoKit
import Foundation
import XCTest

@testable import ConduitPushCore

/// The shared vectors in `push/test-vectors`, generated by
/// `push/test-vectors/generate.py`.
enum TestVectors {
  static let directory = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()  // ConduitPushCoreTests
    .deletingLastPathComponent()  // Tests
    .deletingLastPathComponent()  // ConduitPushCore
    .deletingLastPathComponent()  // ios
    .deletingLastPathComponent()  // repository root
    .appendingPathComponent("push/test-vectors", isDirectory: true)

  struct RFC8291: Decodable {
    let plaintext: String
    let ua_private: String
    let ua_public: String
    let auth: String
    let body: String
  }

  struct Subscription: Decodable {
    let sid: String
    let ua_private: String
    let ua_public: String
    let auth: String
  }

  struct Case: Decodable {
    let name: String
    let sid: String
    let scope: String
    let ua_private: String
    let ua_public: String
    let auth: String
    let plaintext: String
    let body: String
    let bucket: Int
    let app_dedup_key: String
  }

  struct Reject: Decodable {
    let ua_private: String
    let auth: String
    let bodies: [String: String]
  }

  struct PayloadReject: Decodable {
    let name: String
    let plaintext: String
  }

  struct CP1: Decodable {
    let debug_subscription: Subscription
    let cases: [Case]
    let reject: Reject
    let payload_reject: [PayloadReject]
  }

  static func load<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
    let data = try Data(contentsOf: directory.appendingPathComponent(name))
    return try JSONDecoder().decode(T.self, from: data)
  }

  static func rfc8291() throws -> RFC8291 {
    try load("rfc8291.json", as: RFC8291.self)
  }

  static func cp1() throws -> CP1 {
    try load("cp1_vectors.json", as: CP1.self)
  }

  static func cp1Case(_ name: String) throws -> Case {
    try XCTUnwrap(cp1().cases.first { $0.name == name }, "no vector case \(name)")
  }
}

func b64u(_ text: String, file: StaticString = #filePath, line: UInt = #line) throws -> Data {
  try XCTUnwrap(Data(base64URLEncoded: text), "not base64url: \(text)", file: file, line: line)
}

func privateKey(_ text: String) throws -> P256.KeyAgreement.PrivateKey {
  try P256.KeyAgreement.PrivateKey(rawRepresentation: b64u(text))
}

/// Keychain stand-in, since `swift test` runs without entitlements.
final class MemorySecretStorage: PushSecretStorage {
  var items: [String: Data] = [:]

  func read(account: String) throws -> Data? { items[account] }
  func write(_ data: Data, account: String) throws { items[account] = data }
  func delete(account: String) throws { items.removeValue(forKey: account) }
  func accounts() throws -> [String] { Array(items.keys) }
}

func temporaryDirectory() throws -> URL {
  let url = FileManager.default.temporaryDirectory
    .appendingPathComponent("ConduitPushCoreTests-\(UUID().uuidString)", isDirectory: true)
  try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
  return url
}

/// A sender, for pushes the vectors don't cover: RFC 8291 aes128gcm with
/// Conduit's padding buckets, as in server-plugins/common/conduit_webpush.
enum TestWebPush {
  static func encrypt(_ plaintext: Data, to record: PushKeyRecord) throws -> Data {
    let sender = P256.KeyAgreement.PrivateKey()
    let receiver = try P256.KeyAgreement.PublicKey(x963Representation: record.publicKey)
    let secret = try sender.sharedSecretFromKeyAgreement(with: receiver).withUnsafeBytes { Data($0) }
    let salt = PushKeyRecord.randomBytes(16)
    let asPublic = sender.publicKey.x963Representation
    func hmac(_ key: Data, _ data: Data) -> Data {
      Data(HMAC<SHA256>.authenticationCode(for: data, using: SymmetricKey(data: key)))
    }
    let ikm = hmac(
      hmac(record.authSecret, secret),
      Data("WebPush: info\0".utf8) + record.publicKey + asPublic + [1])
    let prk = hmac(salt, ikm)
    let key = hmac(prk, Data("Content-Encoding: aes128gcm\0".utf8) + [1]).prefix(16)
    let nonce = hmac(prk, Data("Content-Encoding: nonce\0".utf8) + [1]).prefix(12)
    let bucket = try XCTUnwrap([512, 1024, 2048].first { plaintext.count + 1 + 16 <= $0 })
    let padded = plaintext + [2] + Data(count: bucket - 16 - plaintext.count - 1)
    let sealed = try AES.GCM.seal(
      padded, using: SymmetricKey(data: key), nonce: AES.GCM.Nonce(data: nonce))
    return salt + [0, 0, 0x10, 0, 65] + asPublic + sealed.ciphertext + sealed.tag
  }
}
