// Vendors the Lucide icons the renderer uses into a Dart file.
//
//   node scripts/vendor-lucide.mjs
//
// Reads lucide-static's icon-nodes.json (a pinned devDependency) and writes
// apps/desktop_ui/lib/src/widgets/lucide_icons.dart, which is committed:
// the icons are part of the renderer's source, drawn as inline SVG with no
// font or sprite to load. Add a name to ICONS and rerun to use a new one.
//
// Lucide is ISC-licensed, with some icons MIT from Feather; both notices are
// copied into the generated file.
import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ICONS = [
  'app-window', 'archive', 'arrow-down', 'arrow-left', 'arrow-right', 'arrow-up',
  'arrow-up-right', 'audio-lines', 'ban', 'bell', 'book-open', 'bookmark', 'bot',
  'brain', 'calendar', 'check', 'chevron-down', 'chevron-left', 'chevron-right',
  'chevron-up', 'circle', 'circle-alert', 'circle-check', 'circle-dot',
  'circle-question-mark', 'circle-x', 'clipboard', 'clock', 'cloud', 'code',
  'columns-2', 'command', 'copy', 'copy-check', 'corner-down-left', 'cpu',
  'database', 'download', 'ellipsis', 'ellipsis-vertical', 'external-link', 'eye',
  'file', 'file-code', 'file-image', 'file-text', 'files', 'folder', 'folder-open',
  'folder-plus', 'globe', 'grip-vertical', 'hash', 'house', 'image', 'info',
  'key-round', 'keyboard', 'languages', 'layers', 'library', 'link', 'list',
  'list-checks', 'list-filter', 'list-tree', 'loader-circle', 'lock', 'log-out',
  'maximize-2', 'message-square', 'message-square-plus', 'messages-square', 'mic',
  'mic-off', 'minimize-2', 'minus', 'monitor', 'moon', 'network', 'notebook-pen',
  'panel-bottom', 'panel-left', 'panel-right', 'paperclip', 'pause', 'pencil',
  'phone', 'phone-off', 'pin', 'pin-off', 'play', 'plug', 'plus', 'power', 'quote',
  'radio', 'redo-2', 'refresh-cw', 'rotate-ccw', 'rss', 'save', 'scroll-text',
  'search', 'send', 'server', 'settings', 'share-2', 'shield-check',
  'sliders-horizontal', 'sparkles', 'square', 'square-pen', 'square-stop',
  'square-terminal', 'star', 'sticky-note', 'sun', 'tag', 'terminal', 'trash',
  'triangle-alert', 'undo-2', 'upload', 'user', 'users', 'volume-2', 'volume-x',
  'wifi-off', 'wrench', 'x', 'zap',
]

const here = dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)
const packageDir = dirname(require.resolve('lucide-static/package.json'))
const { version } = JSON.parse(readFileSync(join(packageDir, 'package.json'), 'utf8'))
const nodes = JSON.parse(readFileSync(join(packageDir, 'icon-nodes.json'), 'utf8'))
const license = readFileSync(join(packageDir, 'LICENSE'), 'utf8').trim()

const camel = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const dartString = (value) => `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`

const missing = ICONS.filter((name) => !nodes[name])
if (missing.length) {
  console.error(`Not in lucide-static ${version}: ${missing.join(', ')}`)
  process.exit(1)
}

const lines = [
  '// GENERATED by desktop/electron/scripts/vendor-lucide.mjs from',
  `// lucide-static ${version}. Do not edit by hand; add a name there and rerun.`,
  '//',
  ...license.split('\n').map((line) => (line ? `// ${line}` : '//')),
  '',
  '/// The vendored Lucide icons, each as its SVG child elements on a 24 x 24',
  '/// grid: a tag and its attributes.',
  'enum LucideIcon {',
]
const sorted = [...new Set(ICONS)].sort()
sorted.forEach((name, index) => {
  const children = nodes[name]
    .map(([tag, attributes]) => {
      const pairs = Object.entries(attributes)
        .map(([key, value]) => `${dartString(key)}: ${dartString(String(value))}`)
        .join(', ')
      return `    (${dartString(tag)}, <String, String>{${pairs}}),`
    })
    .join('\n')
  lines.push(`  ${camel(name)}(${dartString(name)}, [`)
  lines.push(children)
  lines.push(`  ])${index === sorted.length - 1 ? ';' : ','}`)
})
lines.push(
  '',
  '  const LucideIcon(this.lucideName, this.nodes);',
  '',
  "  /// The icon's name on lucide.dev.",
  '  final String lucideName;',
  '',
  '  final List<(String, Map<String, String>)> nodes;',
  '}',
  '',
)

const target = join(here, '..', '..', '..', 'apps', 'desktop_ui', 'lib', 'src', 'widgets', 'lucide_icons.dart')
writeFileSync(target, lines.join('\n'))
spawnSync('dart', ['format', target], { stdio: 'ignore' })
console.log(`Wrote ${sorted.length} icons from lucide-static ${version}`)
