// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/contract.dart';
import 'api/runtime.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiRuntimeInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1262678885;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'conduit_chatgpt_runtime',
        ioDirectory: 'native/chatgpt_runtime/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiRuntimeAckAuthMutation({
    required String mutationId,
    required bool persisted,
  });

  Future<AuthStateInfo> crateApiRuntimeAuthState();

  Future<DeviceCodeChallenge> crateApiRuntimeBeginDeviceCodeLogin();

  Future<int> crateApiRuntimeBridgeProtocolVersion();

  Future<void> crateApiRuntimeCancelDeviceCodeLogin();

  Future<void> crateApiRuntimeDisconnectAccount();

  Future<ThreadInfo> crateApiRuntimeForkThread({
    required String threadId,
    String? turnId,
  });

  Future<void> crateApiRuntimeInitApp();

  Future<void> crateApiRuntimeInitializeRuntime({
    required BigInt clientEpoch,
    required String dataDirectory,
    Uint8List? authSnapshot,
  });

  Future<void> crateApiRuntimeInterruptTurn({required String runId});

  Future<List<ModelInfo>> crateApiRuntimeListModels();

  Future<ThreadInfo> crateApiRuntimeResumeThread({required String threadId});

  Stream<RuntimeEvent> crateApiRuntimeRuntimeEvents({
    required BigInt clientEpoch,
  });

  Future<void> crateApiRuntimeShutdownRuntime();

  Future<ThreadInfo> crateApiRuntimeStartThread({
    required String modelId,
    required bool enableWebSearch,
    required bool enableImageGeneration,
  });

  Future<RunInfo> crateApiRuntimeStartTurn({required TurnRequest request});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiRuntimeAckAuthMutation({
    required String mutationId,
    required bool persisted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mutationId, serializer);
          sse_encode_bool(persisted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeAckAuthMutationConstMeta,
        argValues: [mutationId, persisted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeAckAuthMutationConstMeta =>
      const TaskConstMeta(
        debugName: "ack_auth_mutation",
        argNames: ["mutationId", "persisted"],
      );

  @override
  Future<AuthStateInfo> crateApiRuntimeAuthState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_state_info,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeAuthStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeAuthStateConstMeta =>
      const TaskConstMeta(debugName: "auth_state", argNames: []);

  @override
  Future<DeviceCodeChallenge> crateApiRuntimeBeginDeviceCodeLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_challenge,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeBeginDeviceCodeLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeBeginDeviceCodeLoginConstMeta =>
      const TaskConstMeta(debugName: "begin_device_code_login", argNames: []);

  @override
  Future<int> crateApiRuntimeBridgeProtocolVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRuntimeBridgeProtocolVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeBridgeProtocolVersionConstMeta =>
      const TaskConstMeta(debugName: "bridge_protocol_version", argNames: []);

  @override
  Future<void> crateApiRuntimeCancelDeviceCodeLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeCancelDeviceCodeLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeCancelDeviceCodeLoginConstMeta =>
      const TaskConstMeta(debugName: "cancel_device_code_login", argNames: []);

  @override
  Future<void> crateApiRuntimeDisconnectAccount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeDisconnectAccountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeDisconnectAccountConstMeta =>
      const TaskConstMeta(debugName: "disconnect_account", argNames: []);

  @override
  Future<ThreadInfo> crateApiRuntimeForkThread({
    required String threadId,
    String? turnId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(threadId, serializer);
          sse_encode_opt_String(turnId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_thread_info,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeForkThreadConstMeta,
        argValues: [threadId, turnId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeForkThreadConstMeta => const TaskConstMeta(
    debugName: "fork_thread",
    argNames: ["threadId", "turnId"],
  );

  @override
  Future<void> crateApiRuntimeInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRuntimeInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiRuntimeInitializeRuntime({
    required BigInt clientEpoch,
    required String dataDirectory,
    Uint8List? authSnapshot,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(clientEpoch, serializer);
          sse_encode_String(dataDirectory, serializer);
          sse_encode_opt_list_prim_u_8_strict(authSnapshot, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeInitializeRuntimeConstMeta,
        argValues: [clientEpoch, dataDirectory, authSnapshot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeInitializeRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_runtime",
        argNames: ["clientEpoch", "dataDirectory", "authSnapshot"],
      );

  @override
  Future<void> crateApiRuntimeInterruptTurn({required String runId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeInterruptTurnConstMeta,
        argValues: [runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeInterruptTurnConstMeta =>
      const TaskConstMeta(debugName: "interrupt_turn", argNames: ["runId"]);

  @override
  Future<List<ModelInfo>> crateApiRuntimeListModels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_model_info,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeListModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeListModelsConstMeta =>
      const TaskConstMeta(debugName: "list_models", argNames: []);

  @override
  Future<ThreadInfo> crateApiRuntimeResumeThread({required String threadId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(threadId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_thread_info,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeResumeThreadConstMeta,
        argValues: [threadId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeResumeThreadConstMeta =>
      const TaskConstMeta(debugName: "resume_thread", argNames: ["threadId"]);

  @override
  Stream<RuntimeEvent> crateApiRuntimeRuntimeEvents({
    required BigInt clientEpoch,
  }) {
    final sink = RustStreamSink<RuntimeEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_64(clientEpoch, serializer);
            sse_encode_StreamSink_runtime_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 13,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_bridge_error,
          ),
          constMeta: kCrateApiRuntimeRuntimeEventsConstMeta,
          argValues: [clientEpoch, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRuntimeRuntimeEventsConstMeta =>
      const TaskConstMeta(
        debugName: "runtime_events",
        argNames: ["clientEpoch", "sink"],
      );

  @override
  Future<void> crateApiRuntimeShutdownRuntime() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeShutdownRuntimeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeShutdownRuntimeConstMeta =>
      const TaskConstMeta(debugName: "shutdown_runtime", argNames: []);

  @override
  Future<ThreadInfo> crateApiRuntimeStartThread({
    required String modelId,
    required bool enableWebSearch,
    required bool enableImageGeneration,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          sse_encode_bool(enableWebSearch, serializer);
          sse_encode_bool(enableImageGeneration, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_thread_info,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeStartThreadConstMeta,
        argValues: [modelId, enableWebSearch, enableImageGeneration],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeStartThreadConstMeta => const TaskConstMeta(
    debugName: "start_thread",
    argNames: ["modelId", "enableWebSearch", "enableImageGeneration"],
  );

  @override
  Future<RunInfo> crateApiRuntimeStartTurn({required TurnRequest request}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_turn_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_run_info,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRuntimeStartTurnConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeStartTurnConstMeta =>
      const TaskConstMeta(debugName: "start_turn", argNames: ["request"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<RuntimeEvent> dco_decode_StreamSink_runtime_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthStateInfo dco_decode_auth_state_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AuthStateInfo(
      authenticated: dco_decode_bool(arr[0]),
      email: dco_decode_opt_String(arr[1]),
      planType: dco_decode_opt_String(arr[2]),
      accountId: dco_decode_opt_String(arr[3]),
      accountFingerprint: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  TurnRequest dco_decode_box_autoadd_turn_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_turn_request(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeError(
      kind: dco_decode_bridge_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      retryAfterSeconds: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeErrorKind.values[raw as int];
  }

  @protected
  DeviceCodeChallenge dco_decode_device_code_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeviceCodeChallenge(
      loginId: dco_decode_String(arr[0]),
      verificationUrl: dco_decode_String(arr[1]),
      userCode: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TurnInputPart> dco_decode_list_turn_input_part(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_turn_input_part).toList();
  }

  @protected
  ModelInfo dco_decode_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ModelInfo(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      supportsImages: dco_decode_bool(arr[3]),
      supportsAudio: dco_decode_bool(arr[4]),
      supportedReasoningEfforts: dco_decode_list_String(arr[5]),
      defaultReasoningEffort: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  RunInfo dco_decode_run_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RunInfo(
      runId: dco_decode_String(arr[0]),
      threadId: dco_decode_String(arr[1]),
      turnId: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  RuntimeEvent dco_decode_runtime_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RuntimeEvent(
      clientEpoch: dco_decode_u_64(arr[0]),
      sequence: dco_decode_u_64(arr[1]),
      kind: dco_decode_runtime_event_kind(arr[2]),
      runId: dco_decode_opt_String(arr[3]),
      threadId: dco_decode_opt_String(arr[4]),
      turnId: dco_decode_opt_String(arr[5]),
      itemId: dco_decode_opt_String(arr[6]),
      text: dco_decode_opt_String(arr[7]),
      jsonData: dco_decode_opt_String(arr[8]),
      binaryData: dco_decode_opt_list_prim_u_8_strict(arr[9]),
    );
  }

  @protected
  RuntimeEventKind dco_decode_runtime_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RuntimeEventKind.values[raw as int];
  }

  @protected
  ThreadInfo dco_decode_thread_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ThreadInfo(
      threadId: dco_decode_String(arr[0]),
      modelId: dco_decode_String(arr[1]),
    );
  }

  @protected
  TurnInputPart dco_decode_turn_input_part(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TurnInputPart(
      kind: dco_decode_String(arr[0]),
      text: dco_decode_opt_String(arr[1]),
      filename: dco_decode_opt_String(arr[2]),
      mimeType: dco_decode_opt_String(arr[3]),
      bytes: dco_decode_opt_list_prim_u_8_strict(arr[4]),
    );
  }

  @protected
  TurnRequest dco_decode_turn_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TurnRequest(
      threadId: dco_decode_String(arr[0]),
      clientUserMessageId: dco_decode_opt_String(arr[1]),
      modelId: dco_decode_String(arr[2]),
      reasoningEffort: dco_decode_opt_String(arr[3]),
      enableWebSearch: dco_decode_bool(arr[4]),
      enableImageGeneration: dco_decode_bool(arr[5]),
      inputs: dco_decode_list_turn_input_part(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<RuntimeEvent> sse_decode_StreamSink_runtime_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthStateInfo sse_decode_auth_state_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_authenticated = sse_decode_bool(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_planType = sse_decode_opt_String(deserializer);
    var var_accountId = sse_decode_opt_String(deserializer);
    var var_accountFingerprint = sse_decode_opt_String(deserializer);
    return AuthStateInfo(
      authenticated: var_authenticated,
      email: var_email,
      planType: var_planType,
      accountId: var_accountId,
      accountFingerprint: var_accountFingerprint,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  TurnRequest sse_decode_box_autoadd_turn_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_turn_request(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_bridge_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_retryAfterSeconds = sse_decode_opt_box_autoadd_u_32(deserializer);
    return BridgeError(
      kind: var_kind,
      message: var_message,
      retryAfterSeconds: var_retryAfterSeconds,
    );
  }

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeErrorKind.values[inner];
  }

  @protected
  DeviceCodeChallenge sse_decode_device_code_challenge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loginId = sse_decode_String(deserializer);
    var var_verificationUrl = sse_decode_String(deserializer);
    var var_userCode = sse_decode_String(deserializer);
    return DeviceCodeChallenge(
      loginId: var_loginId,
      verificationUrl: var_verificationUrl,
      userCode: var_userCode,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TurnInputPart> sse_decode_list_turn_input_part(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TurnInputPart>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_turn_input_part(deserializer));
    }
    return ans_;
  }

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_supportsImages = sse_decode_bool(deserializer);
    var var_supportsAudio = sse_decode_bool(deserializer);
    var var_supportedReasoningEfforts = sse_decode_list_String(deserializer);
    var var_defaultReasoningEffort = sse_decode_opt_String(deserializer);
    return ModelInfo(
      id: var_id,
      displayName: var_displayName,
      description: var_description,
      supportsImages: var_supportsImages,
      supportsAudio: var_supportsAudio,
      supportedReasoningEfforts: var_supportedReasoningEfforts,
      defaultReasoningEffort: var_defaultReasoningEffort,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RunInfo sse_decode_run_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_runId = sse_decode_String(deserializer);
    var var_threadId = sse_decode_String(deserializer);
    var var_turnId = sse_decode_opt_String(deserializer);
    return RunInfo(
      runId: var_runId,
      threadId: var_threadId,
      turnId: var_turnId,
    );
  }

  @protected
  RuntimeEvent sse_decode_runtime_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_clientEpoch = sse_decode_u_64(deserializer);
    var var_sequence = sse_decode_u_64(deserializer);
    var var_kind = sse_decode_runtime_event_kind(deserializer);
    var var_runId = sse_decode_opt_String(deserializer);
    var var_threadId = sse_decode_opt_String(deserializer);
    var var_turnId = sse_decode_opt_String(deserializer);
    var var_itemId = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_jsonData = sse_decode_opt_String(deserializer);
    var var_binaryData = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return RuntimeEvent(
      clientEpoch: var_clientEpoch,
      sequence: var_sequence,
      kind: var_kind,
      runId: var_runId,
      threadId: var_threadId,
      turnId: var_turnId,
      itemId: var_itemId,
      text: var_text,
      jsonData: var_jsonData,
      binaryData: var_binaryData,
    );
  }

  @protected
  RuntimeEventKind sse_decode_runtime_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RuntimeEventKind.values[inner];
  }

  @protected
  ThreadInfo sse_decode_thread_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threadId = sse_decode_String(deserializer);
    var var_modelId = sse_decode_String(deserializer);
    return ThreadInfo(threadId: var_threadId, modelId: var_modelId);
  }

  @protected
  TurnInputPart sse_decode_turn_input_part(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_filename = sse_decode_opt_String(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    var var_bytes = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return TurnInputPart(
      kind: var_kind,
      text: var_text,
      filename: var_filename,
      mimeType: var_mimeType,
      bytes: var_bytes,
    );
  }

  @protected
  TurnRequest sse_decode_turn_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threadId = sse_decode_String(deserializer);
    var var_clientUserMessageId = sse_decode_opt_String(deserializer);
    var var_modelId = sse_decode_String(deserializer);
    var var_reasoningEffort = sse_decode_opt_String(deserializer);
    var var_enableWebSearch = sse_decode_bool(deserializer);
    var var_enableImageGeneration = sse_decode_bool(deserializer);
    var var_inputs = sse_decode_list_turn_input_part(deserializer);
    return TurnRequest(
      threadId: var_threadId,
      clientUserMessageId: var_clientUserMessageId,
      modelId: var_modelId,
      reasoningEffort: var_reasoningEffort,
      enableWebSearch: var_enableWebSearch,
      enableImageGeneration: var_enableImageGeneration,
      inputs: var_inputs,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_runtime_event_Sse(
    RustStreamSink<RuntimeEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_runtime_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_state_info(
    AuthStateInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.authenticated, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.planType, serializer);
    sse_encode_opt_String(self.accountId, serializer);
    sse_encode_opt_String(self.accountFingerprint, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_turn_request(
    TurnRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_turn_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_u_32(self.retryAfterSeconds, serializer);
  }

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_device_code_challenge(
    DeviceCodeChallenge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.loginId, serializer);
    sse_encode_String(self.verificationUrl, serializer);
    sse_encode_String(self.userCode, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_turn_input_part(
    List<TurnInputPart> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_turn_input_part(item, serializer);
    }
  }

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_bool(self.supportsImages, serializer);
    sse_encode_bool(self.supportsAudio, serializer);
    sse_encode_list_String(self.supportedReasoningEfforts, serializer);
    sse_encode_opt_String(self.defaultReasoningEffort, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_run_info(RunInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.runId, serializer);
    sse_encode_String(self.threadId, serializer);
    sse_encode_opt_String(self.turnId, serializer);
  }

  @protected
  void sse_encode_runtime_event(RuntimeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.clientEpoch, serializer);
    sse_encode_u_64(self.sequence, serializer);
    sse_encode_runtime_event_kind(self.kind, serializer);
    sse_encode_opt_String(self.runId, serializer);
    sse_encode_opt_String(self.threadId, serializer);
    sse_encode_opt_String(self.turnId, serializer);
    sse_encode_opt_String(self.itemId, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.jsonData, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.binaryData, serializer);
  }

  @protected
  void sse_encode_runtime_event_kind(
    RuntimeEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_thread_info(ThreadInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.threadId, serializer);
    sse_encode_String(self.modelId, serializer);
  }

  @protected
  void sse_encode_turn_input_part(
    TurnInputPart self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.filename, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_turn_request(TurnRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.threadId, serializer);
    sse_encode_opt_String(self.clientUserMessageId, serializer);
    sse_encode_String(self.modelId, serializer);
    sse_encode_opt_String(self.reasoningEffort, serializer);
    sse_encode_bool(self.enableWebSearch, serializer);
    sse_encode_bool(self.enableImageGeneration, serializer);
    sse_encode_list_turn_input_part(self.inputs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
