[package]
name = "codex-code-mode"
version = "0.145.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
name = "codex_code_mode"
path = "src/lib.rs"

[features]
sandbox = []

[dependencies]
codex-code-mode-protocol = { git = "https://github.com/openai/codex", rev = "25af12f7e61572b0bc18ddb1008be543b91519b0" }
