// Regenerates test/src/protocol_goldens.dart from the live DTOs.
//
//   dart run tool/dump_goldens.dart
//
// Review the diff before committing. An unexplained change here means the wire
// format moved, which requires bumping `kConduitProtocolVersion`.
import 'dart:convert';
import 'dart:io';

import '../test/src/protocol_fixtures.dart';

void main() {
  const encoder = JsonEncoder.withIndent('  ');
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/dump_goldens.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// The exact bytes each DTO puts on the wire. Checked in so a')
    ..writeln('// change to any `@freezed` class shows up as a reviewable diff')
    ..writeln('// rather than as a silent protocol break.')
    ..writeln('//')
    ..writeln('// Stored as Dart constants, not as .json files on disk, so the')
    ..writeln('// same goldens can be compiled to JS and checked in a browser')
    ..writeln('// context where there is no filesystem.')
    ..writeln()
    ..writeln('const Map<String, String> protocolGoldens = <String, String>{');
  for (final entry in protocolFixtures.entries) {
    final json = encoder.convert(encodeFixture(entry.value));
    if (json.contains("'''") || json.contains(r'\')) {
      throw StateError(
        'Fixture "${entry.key}" contains a sequence that cannot be embedded '
        'in a raw triple-quoted string. Adjust the fixture or the emitter.',
      );
    }
    buffer
      ..writeln("  '${entry.key}': r'''")
      ..writeln("$json''',")
      ..writeln();
  }
  buffer.writeln('};');
  File('test/src/protocol_goldens.dart').writeAsStringSync(buffer.toString());
  stdout.writeln(
    'Wrote ${protocolFixtures.length} goldens to '
    'test/src/protocol_goldens.dart',
  );
}
