// GENERATED by tool/dump_goldens.dart — do not edit by hand.
//
// The exact bytes each DTO puts on the wire. Checked in so a
// change to any `@freezed` class shows up as a reviewable diff
// rather than as a silent protocol break.
//
// Stored as Dart constants, not as .json files on disk, so the
// same goldens can be compiled to JS and checked in a browser
// context where there is no filesystem.

const Map<String, String> protocolGoldens = <String, String>{
  'handshakeRequest': r'''
{
  "protocolVersion": "1.0.0",
  "clientName": "conduit-desktop-ui",
  "clientVersion": "0.1.0",
  "windowKind": "main",
  "locale": "zh-Hant"
}''',

  'handshakeResponse': r'''
{
  "protocolVersion": "1.0.0",
  "daemonVersion": "0.1.0",
  "sessionId": "0f9d1c2e-4b6a-4d8f-9a1b-2c3d4e5f6071",
  "capabilities": {
    "workspace": true,
    "notes": true,
    "channels": true,
    "hermes": false,
    "terminal": false,
    "directConnections": false,
    "mcp": false,
    "serverStt": true,
    "onDeviceStt": false,
    "serverTts": true,
    "deviceTts": true,
    "appleOnDeviceModels": false,
    "applePcc": false,
    "branchNavigation": true,
    "messageRating": false,
    "tags": true,
    "bulkSelection": false
  },
  "paths": {
    "userData": "/home/u/.config/Conduit",
    "database": "/home/u/.config/Conduit/db",
    "cache": "/home/u/.config/Conduit/cache",
    "logs": "/home/u/.config/Conduit/logs",
    "staging": "/home/u/.config/Conduit/staging"
  },
  "platform": "linux",
  "needsOnboarding": true
}''',

  'capabilitiesNone': r'''
{
  "workspace": false,
  "notes": false,
  "channels": false,
  "hermes": false,
  "terminal": false,
  "directConnections": false,
  "mcp": false,
  "serverStt": false,
  "onDeviceStt": false,
  "serverTts": false,
  "deviceTts": false,
  "appleOnDeviceModels": false,
  "applePcc": false,
  "branchNavigation": false,
  "messageRating": false,
  "tags": false,
  "bulkSelection": false
}''',

  'rpcErrorMinimal': r'''
{
  "code": "net.offline",
  "args": {},
  "retryable": false
}''',

  'rpcErrorFull': r'''
{
  "code": "net.serverError",
  "args": {
    "status": "503",
    "host": "chat.example.com"
  },
  "debugMessage": "upstream returned 503",
  "retryable": true
}''',

  'eventEnvelope': r'''
{
  "event": "turn.delta",
  "seq": 9007199254740991,
  "scope": "chat_01HV8Z",
  "payload": {
    "text": "Hello",
    "index": 3
  }
}''',

  'eventSubscription': r'''
{
  "events": [
    "turn.delta",
    "chats.changed"
  ],
  "scopes": [
    "chat_01HV8Z"
  ]
}''',

  'uiRequest': r'''
{
  "requestId": "req_7",
  "kind": "toolApproval",
  "messageCode": "tool.approvalPrompt",
  "messageArgs": {
    "tool": "web_search"
  },
  "detail": {
    "tool": "web_search",
    "arguments": {
      "query": "jaspr 0.23"
    }
  },
  "timeoutMs": 120000,
  "defaultChoice": "deny"
}''',

  'uiResponse': r'''
{
  "requestId": "req_7",
  "choice": "allow",
  "remember": true
}''',

  'pongResult': r'''
{
  "uptimeMs": 421337,
  "serverTimeMs": 1789000000000
}''',

  'shutdownResult': r'''
{
  "flushed": false,
  "pendingOutboxEntries": 2
}''',

  'diagnosticsExport': r'''
{
  "path": "/home/u/.config/Conduit/staging/diagnostics-2026-09-21.zip",
  "sizeBytes": 148213
}''',

};
