// GENERATED by tool/dump_goldens.dart — do not edit by hand.
//
// The exact bytes each DTO puts on the wire. Checked in so a
// change to any `@freezed` class shows up as a reviewable diff
// rather than as a silent protocol break.
//
// Stored as Dart constants, not as .json files on disk, so the
// same goldens can be compiled to JS and checked in a browser
// context where there is no filesystem.

const Map<String, String> protocolGoldens = <String, String>{
  'handshakeRequest': r'''
{
  "protocolVersion": "1.0.0",
  "clientName": "conduit-desktop-ui",
  "clientVersion": "0.1.0",
  "windowKind": "main",
  "locale": "zh-Hant"
}''',

  'handshakeResponse': r'''
{
  "protocolVersion": "1.0.0",
  "daemonVersion": "0.1.0",
  "sessionId": "0f9d1c2e-4b6a-4d8f-9a1b-2c3d4e5f6071",
  "capabilities": {
    "workspace": true,
    "notes": true,
    "channels": true,
    "hermes": false,
    "terminal": false,
    "directConnections": false,
    "mcp": false,
    "serverStt": true,
    "onDeviceStt": false,
    "serverTts": true,
    "deviceTts": true,
    "appleOnDeviceModels": false,
    "applePcc": false,
    "branchNavigation": true,
    "messageRating": false,
    "tags": true,
    "bulkSelection": false
  },
  "paths": {
    "userData": "/home/u/.config/Conduit",
    "database": "/home/u/.config/Conduit/db",
    "cache": "/home/u/.config/Conduit/cache",
    "logs": "/home/u/.config/Conduit/logs",
    "staging": "/home/u/.config/Conduit/staging"
  },
  "platform": "linux",
  "needsOnboarding": true
}''',

  'capabilitiesNone': r'''
{
  "workspace": false,
  "notes": false,
  "channels": false,
  "hermes": false,
  "terminal": false,
  "directConnections": false,
  "mcp": false,
  "serverStt": false,
  "onDeviceStt": false,
  "serverTts": false,
  "deviceTts": false,
  "appleOnDeviceModels": false,
  "applePcc": false,
  "branchNavigation": false,
  "messageRating": false,
  "tags": false,
  "bulkSelection": false
}''',

  'rpcErrorMinimal': r'''
{
  "code": "net.offline",
  "args": {},
  "retryable": false
}''',

  'rpcErrorFull': r'''
{
  "code": "net.serverError",
  "args": {
    "status": "503",
    "host": "chat.example.com"
  },
  "debugMessage": "upstream returned 503",
  "retryable": true
}''',

  'eventEnvelope': r'''
{
  "event": "turn.delta",
  "seq": 9007199254740991,
  "scope": "chat_01HV8Z",
  "payload": {
    "text": "Hello",
    "index": 3
  }
}''',

  'eventSubscription': r'''
{
  "events": [
    "turn.delta",
    "chats.changed"
  ],
  "scopes": [
    "chat_01HV8Z"
  ]
}''',

  'uiRequest': r'''
{
  "requestId": "req_7",
  "kind": "toolApproval",
  "messageCode": "tool.approvalPrompt",
  "messageArgs": {
    "tool": "web_search"
  },
  "detail": {
    "tool": "web_search",
    "arguments": {
      "query": "jaspr 0.23"
    }
  },
  "timeoutMs": 120000,
  "defaultChoice": "deny"
}''',

  'uiResponse': r'''
{
  "requestId": "req_7",
  "choice": "allow",
  "remember": true
}''',

  'pongResult': r'''
{
  "uptimeMs": 421337,
  "serverTimeMs": 1789000000000
}''',

  'shutdownResult': r'''
{
  "flushed": false,
  "pendingOutboxEntries": 2
}''',

  'diagnosticsExport': r'''
{
  "path": "/home/u/.config/Conduit/staging/diagnostics-2026-09-21.zip",
  "sizeBytes": 148213
}''',

  'daemonPaths': r'''
{
  "userData": "/home/u/.config/Conduit",
  "database": "/home/u/.config/Conduit/db",
  "cache": "/home/u/.config/Conduit/cache",
  "logs": "/home/u/.config/Conduit/logs",
  "staging": "/home/u/.config/Conduit/staging"
}''',

  'serverSummaryMinimal': r'''
{
  "id": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d",
  "name": "Home",
  "url": "https://chat.example.com",
  "isActive": false,
  "allowSelfSignedCertificates": false,
  "hasMutualTlsCredentials": false,
  "customHeaderNames": [],
  "hasStoredSession": false
}''',

  'serverSummaryFull': r'''
{
  "id": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d",
  "name": "Work",
  "url": "https://openwebui.corp.example.com",
  "isActive": true,
  "lastConnectedMs": 1758412800000,
  "allowSelfSignedCertificates": true,
  "hasMutualTlsCredentials": true,
  "mtlsCertificateLabel": "corp-client.pem",
  "mtlsPrivateKeyLabel": "corp-client-key.pem",
  "customHeaderNames": [
    "X-Conduit-Tenant",
    "CF-Access-Client-Id"
  ],
  "hasStoredSession": true
}''',

  'serverDraft': r'''
{
  "id": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d",
  "name": "Work",
  "url": "https://openwebui.corp.example.com",
  "allowSelfSignedCertificates": true,
  "clearMutualTls": false,
  "customHeaders": {
    "X-Conduit-Tenant": "acme"
  }
}''',

  'serverRef': r'''
{
  "id": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d"
}''',

  'serverList': r'''
{
  "servers": [
    {
      "id": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d",
      "name": "Home",
      "url": "https://chat.example.com",
      "isActive": true,
      "allowSelfSignedCertificates": false,
      "hasMutualTlsCredentials": false,
      "customHeaderNames": [],
      "hasStoredSession": false
    }
  ],
  "activeServerId": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d"
}''',

  'authSnapshotSignedOut': r'''
{
  "phase": "unauthenticated",
  "isAuthenticated": false,
  "isLoading": false,
  "hasToken": false,
  "errorArgs": {},
  "isReviewerMode": false
}''',

  'authSnapshotSignedIn': r'''
{
  "phase": "authenticated",
  "isAuthenticated": true,
  "isLoading": false,
  "hasToken": true,
  "user": {
    "id": "c3a1b2d4-5e6f-4708-9a1b-2c3d4e5f6071",
    "name": "Ada Lovelace",
    "email": "ada@example.com",
    "role": "admin",
    "avatarUrl": "/api/v1/users/c3a1b2d4/avatar"
  },
  "errorArgs": {},
  "isReviewerMode": false
}''',

  'authSnapshotError': r'''
{
  "phase": "credentialError",
  "isAuthenticated": false,
  "isLoading": false,
  "hasToken": false,
  "errorCode": "auth.invalidCredentials",
  "errorArgs": {
    "attempt": "3"
  },
  "isReviewerMode": false
}''',

  'authUser': r'''
{
  "id": "c3a1b2d4-5e6f-4708-9a1b-2c3d4e5f6071",
  "name": "Ada Lovelace"
}''',

  'passwordLogin': r'''
{
  "username": "ada@example.com",
  "password": "correct horse battery staple"
}''',

  'apiKeyLogin': r'''
{
  "apiKey": "sk-not-a-real-key"
}''',

  'externalAuthCompletion': r'''
{
  "origin": "https://chat.example.com",
  "cookies": {
    "oauth2_proxy": "opaque-session-value"
  },
  "token": "eyJhbGciOiJIUzI1NiJ9.not-a-real-token"
}''',

  'signOutRequest': r'''
{
  "keepServerDetails": false
}''',

  'modelSummary': r'''
{
  "id": "gpt-4o",
  "name": "GPT-4o",
  "description": "Fast, multimodal.",
  "pinned": true,
  "capabilities": [
    "tools",
    "vision"
  ]
}''',

  'modelList': r'''
{
  "models": [
    {
      "id": "gpt-4o",
      "name": "GPT-4o",
      "pinned": false,
      "capabilities": []
    }
  ],
  "selectedId": "gpt-4o"
}''',

  'selectModel': r'''
{
  "id": "gpt-4o"
}''',

  'sendTurn': r'''
{
  "chatId": "chat-7c1f0b2a",
  "model": "gpt-4o",
  "text": "How does the outbox order writes?",
  "toolIds": [
    "web_search"
  ],
  "webSearch": true,
  "imageGeneration": false,
  "codeInterpreter": false,
  "fileIds": []
}''',

  'sendTurnAccepted': r'''
{
  "chatId": "chat-7c1f0b2a",
  "userMessageId": "msg-user-1",
  "assistantMessageId": "msg-assistant-1"
}''',

  'turnStarted': r'''
{
  "chatId": "chat-7c1f0b2a",
  "messageId": "msg-assistant-1",
  "model": "gpt-4o"
}''',

  'turnDelta': r'''
{
  "chatId": "chat-7c1f0b2a",
  "messageId": "msg-assistant-1",
  "text": "The outbox drains",
  "reasoning": "Checking the DAO."
}''',

  'turnCompleted': r'''
{
  "chatId": "chat-7c1f0b2a",
  "messageId": "msg-assistant-1",
  "text": "The outbox drains oldest-first.",
  "usage": {
    "prompt_tokens": 812,
    "completion_tokens": 46
  }
}''',

  'turnFailed': r'''
{
  "chatId": "chat-7c1f0b2a",
  "messageId": "msg-assistant-1",
  "code": "net.serverError",
  "args": {
    "status": "502"
  },
  "partialText": "The outbox dra"
}''',

  'stopTurn': r'''
{
  "chatId": "chat-7c1f0b2a"
}''',

  'chatSummary': r'''
{
  "id": "chat-7c1f0b2a",
  "title": "Rewriting the sync engine",
  "updatedAtMs": 1758412800000,
  "pinned": true,
  "archived": false,
  "model": "gpt-4o",
  "tags": [
    "work",
    "architecture"
  ],
  "shared": true
}''',

  'chatList': r'''
{
  "chats": [
    {
      "id": "chat-7c1f0b2a",
      "title": "Rewriting the sync engine",
      "updatedAtMs": 1758412800000,
      "pinned": false,
      "archived": false,
      "tags": [],
      "shared": false
    }
  ],
  "hasMore": true,
  "archivedCount": 12
}''',

  'chatMessage': r'''
{
  "id": "msg-1",
  "role": "assistant",
  "content": "The outbox drains oldest-first.",
  "timestampMs": 1758412800000,
  "model": "gpt-4o",
  "streaming": true
}''',

  'chatDetail': r'''
{
  "summary": {
    "id": "chat-7c1f0b2a",
    "title": "Rewriting the sync engine",
    "updatedAtMs": 1758412800000,
    "pinned": false,
    "archived": false,
    "tags": [],
    "shared": false
  },
  "messages": [
    {
      "id": "msg-1",
      "role": "user",
      "content": "How does the outbox order writes?",
      "timestampMs": 1758412700000,
      "streaming": false
    }
  ]
}''',

  'chatRef': r'''
{
  "id": "chat-7c1f0b2a"
}''',

  'chatSearchQuery': r'''
{
  "query": "outbox",
  "limit": 20
}''',

  'chatSearchHit': r'''
{
  "chatId": "chat-7c1f0b2a",
  "title": "Rewriting the sync engine",
  "snippet": "the <b>outbox</b> drains oldest-first",
  "updatedAtMs": 1758412800000
}''',

  'chatSearchResults': r'''
{
  "hits": [
    {
      "chatId": "chat-7c1f0b2a",
      "title": "Rewriting the sync engine",
      "updatedAtMs": 1758412800000
    }
  ]
}''',

  'serverStatusNoServer': r'''
{
  "capabilities": {
    "workspace": false,
    "notes": false,
    "channels": false,
    "hermes": false,
    "terminal": false,
    "directConnections": false,
    "mcp": false,
    "serverStt": false,
    "onDeviceStt": false,
    "serverTts": false,
    "deviceTts": false,
    "appleOnDeviceModels": false,
    "applePcc": false,
    "branchNavigation": false,
    "messageRating": false,
    "tags": false,
    "bulkSelection": false
  },
  "reachability": "unknown",
  "isVersionSupported": true,
  "maxSupportedVersion": "0.11.3"
}''',

  'serverStatusReachable': r'''
{
  "activeServerId": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d",
  "capabilities": {
    "workspace": true,
    "notes": true,
    "channels": true,
    "hermes": false,
    "terminal": false,
    "directConnections": false,
    "mcp": false,
    "serverStt": true,
    "onDeviceStt": false,
    "serverTts": true,
    "deviceTts": true,
    "appleOnDeviceModels": false,
    "applePcc": false,
    "branchNavigation": true,
    "messageRating": false,
    "tags": true,
    "bulkSelection": false
  },
  "reachability": "reachable",
  "version": "0.11.3",
  "isVersionSupported": true,
  "maxSupportedVersion": "0.11.3"
}''',

  'serverStatusUnreachable': r'''
{
  "activeServerId": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d",
  "capabilities": {
    "workspace": false,
    "notes": false,
    "channels": false,
    "hermes": false,
    "terminal": false,
    "directConnections": false,
    "mcp": false,
    "serverStt": false,
    "onDeviceStt": false,
    "serverTts": false,
    "deviceTts": false,
    "appleOnDeviceModels": false,
    "applePcc": false,
    "branchNavigation": false,
    "messageRating": false,
    "tags": false,
    "bulkSelection": false
  },
  "reachability": "unreachable",
  "isVersionSupported": true,
  "maxSupportedVersion": "0.11.3",
  "errorCode": "net.connectionFailed"
}''',

  'serverStatusTooNew': r'''
{
  "activeServerId": "7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d",
  "capabilities": {
    "workspace": false,
    "notes": false,
    "channels": false,
    "hermes": false,
    "terminal": false,
    "directConnections": false,
    "mcp": false,
    "serverStt": false,
    "onDeviceStt": false,
    "serverTts": false,
    "deviceTts": false,
    "appleOnDeviceModels": false,
    "applePcc": false,
    "branchNavigation": false,
    "messageRating": false,
    "tags": false,
    "bulkSelection": false
  },
  "reachability": "reachable",
  "version": "0.99.0",
  "isVersionSupported": false,
  "maxSupportedVersion": "0.11.3"
}''',

  'appPreferencesDefault': r'''
{
  "themeMode": "system",
  "themePaletteId": "conduit"
}''',

  'appPreferencesFull': r'''
{
  "themeMode": "dark",
  "themePaletteId": "t3_chat",
  "localeCode": "zh-Hant"
}''',

  'appPreferencesPatch': r'''
{
  "themePaletteId": "claude",
  "clearLocaleCode": true
}''',

  'signOutResult': r'''
{
  "outcome": "localDataClearedSessionCleanupIncomplete",
  "remaining": [
    "cookies"
  ]
}''',

};
