import 'package:conduit_protocol/conduit_protocol.dart';

/// The canonical sample of every DTO that crosses the wire.
///
/// One map, consumed by three things: the golden encode/decode test, the
/// compiled-to-JS variant of that same test, and (later) the daemon and UI
/// integration fakes. Adding a DTO without adding it here is what "schema
/// drift" looks like in practice, so [protocolFixtures] is asserted to be
/// exhaustive in the golden test.
final Map<String, Object> protocolFixtures = <String, Object>{
  'handshakeRequest': const HandshakeRequest(
    protocolVersion: kConduitProtocolVersion,
    clientName: 'conduit-desktop-ui',
    clientVersion: '0.1.0',
    windowKind: WindowKind.main,
    locale: 'zh-Hant',
  ),
  'handshakeResponse': const HandshakeResponse(
    protocolVersion: kConduitProtocolVersion,
    daemonVersion: '0.1.0',
    sessionId: '0f9d1c2e-4b6a-4d8f-9a1b-2c3d4e5f6071',
    capabilities: Capabilities(
      workspace: true,
      notes: true,
      channels: true,
      serverStt: true,
      serverTts: true,
      deviceTts: true,
      branchNavigation: true,
      tags: true,
    ),
    paths: DaemonPaths(
      userData: '/home/u/.config/Conduit',
      database: '/home/u/.config/Conduit/db',
      cache: '/home/u/.config/Conduit/cache',
      logs: '/home/u/.config/Conduit/logs',
      staging: '/home/u/.config/Conduit/staging',
    ),
    platform: 'linux',
    needsOnboarding: true,
  ),
  'capabilitiesNone': Capabilities.none,
  'rpcErrorMinimal': const RpcError(code: ConduitErrorCodes.offline),
  'rpcErrorFull': const RpcError(
    code: ConduitErrorCodes.serverError,
    args: <String, String>{'status': '503', 'host': 'chat.example.com'},
    debugMessage: 'upstream returned 503',
    retryable: true,
  ),
  'eventEnvelope': const EventEnvelope(
    event: ConduitEvents.turnDelta,
    // Deliberately large: well past 2^32 but inside 2^53, so this fixture
    // fails loudly if anyone makes `seq` a type JS cannot represent exactly.
    seq: 9007199254740991,
    scope: 'chat_01HV8Z',
    payload: <String, dynamic>{'text': 'Hello', 'index': 3},
  ),
  'eventSubscription': const EventSubscription(
    events: <String>[ConduitEvents.turnDelta, ConduitEvents.chatsChanged],
    scopes: <String>['chat_01HV8Z'],
  ),
  'uiRequest': const UiRequest(
    requestId: 'req_7',
    kind: UiRequestKind.toolApproval,
    messageCode: 'tool.approvalPrompt',
    messageArgs: <String, String>{'tool': 'web_search'},
    detail: <String, dynamic>{
      'tool': 'web_search',
      'arguments': <String, dynamic>{'query': 'jaspr 0.23'},
    },
    timeoutMs: 120000,
  ),
  'uiResponse': const UiResponse(
    requestId: 'req_7',
    choice: 'allow',
    remember: true,
  ),
  'pongResult': const PongResult(uptimeMs: 421337, serverTimeMs: 1789000000000),
  'shutdownResult': const ShutdownResult(
    flushed: false,
    pendingOutboxEntries: 2,
  ),
  'diagnosticsExport': const DiagnosticsExport(
    path: '/home/u/.config/Conduit/staging/diagnostics-2026-09-21.zip',
    sizeBytes: 148213,
  ),

  // Nested inside handshakeResponse, so it is encoded there -- but its own
  // `fromJson` had never been exercised until the missing-fixture check in
  // protocol_golden_test.dart went looking.
  'daemonPaths': const DaemonPaths(
    userData: '/home/u/.config/Conduit',
    database: '/home/u/.config/Conduit/db',
    cache: '/home/u/.config/Conduit/cache',
    logs: '/home/u/.config/Conduit/logs',
    staging: '/home/u/.config/Conduit/staging',
  ),

  // servers.* and auth.* (WP-2.1). Two variants of ServerSummary on purpose:
  // the redacted-secrets shape is the one that carries the security claim, so
  // it is golden-checked rather than trusted.
  'serverSummaryMinimal': const ServerSummary(
    id: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
    name: 'Home',
    url: 'https://chat.example.com',
  ),
  'serverSummaryFull': const ServerSummary(
    id: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
    name: 'Work',
    url: 'https://openwebui.corp.example.com',
    isActive: true,
    lastConnectedMs: 1758412800000,
    allowSelfSignedCertificates: true,
    hasMutualTlsCredentials: true,
    mtlsCertificateLabel: 'corp-client.pem',
    mtlsPrivateKeyLabel: 'corp-client-key.pem',
    customHeaderNames: <String>['X-Conduit-Tenant', 'CF-Access-Client-Id'],
    hasStoredSession: true,
  ),
  'serverDraft': const ServerDraft(
    id: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
    name: 'Work',
    url: 'https://openwebui.corp.example.com',
    allowSelfSignedCertificates: true,
    customHeaders: <String, String>{'X-Conduit-Tenant': 'acme'},
  ),
  'serverRef': const ServerRef(id: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d'),
  'serverList': const ServerList(
    servers: <ServerSummary>[
      ServerSummary(
        id: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
        name: 'Home',
        url: 'https://chat.example.com',
        isActive: true,
      ),
    ],
    activeServerId: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
  ),
  'authSnapshotSignedOut': const AuthSnapshot(phase: AuthPhase.unauthenticated),
  'authSnapshotSignedIn': const AuthSnapshot(
    phase: AuthPhase.authenticated,
    isAuthenticated: true,
    hasToken: true,
    user: AuthUser(
      id: 'c3a1b2d4-5e6f-4708-9a1b-2c3d4e5f6071',
      name: 'Ada Lovelace',
      email: 'ada@example.com',
      role: 'admin',
      avatarUrl: '/api/v1/users/c3a1b2d4/avatar',
    ),
  ),
  'authSnapshotError': const AuthSnapshot(
    phase: AuthPhase.credentialError,
    errorCode: ConduitErrorCodes.invalidCredentials,
    errorArgs: <String, String>{'attempt': '3'},
  ),
  'authUser': const AuthUser(
    id: 'c3a1b2d4-5e6f-4708-9a1b-2c3d4e5f6071',
    name: 'Ada Lovelace',
  ),
  'passwordLogin': const PasswordLogin(
    username: 'ada@example.com',
    password: 'correct horse battery staple',
  ),
  'apiKeyLogin': const ApiKeyLogin(apiKey: 'sk-not-a-real-key'),
  'externalAuthCompletion': const ExternalAuthCompletion(
    origin: 'https://chat.example.com',
    cookies: <String, String>{'oauth2_proxy': 'opaque-session-value'},
    token: 'eyJhbGciOiJIUzI1NiJ9.not-a-real-token',
  ),
  'signOutRequest': const SignOutRequest(keepServerDetails: false),
  'modelSummary': const ModelSummary(
    id: 'gpt-4o',
    name: 'GPT-4o',
    description: 'Fast, multimodal.',
    pinned: true,
    capabilities: <String>['tools', 'vision'],
  ),
  'modelList': const ModelList(
    models: <ModelSummary>[
      ModelSummary(id: 'gpt-4o', name: 'GPT-4o'),
      ModelSummary(
        id: 'direct:home:bGxhbWEz',
        name: 'llama3',
        connection: 'Home Ollama',
      ),
    ],
    selectedId: 'gpt-4o',
  ),
  'selectModel': const SelectModel(id: 'gpt-4o'),
  'sendTurn': const SendTurn(
    chatId: 'chat-7c1f0b2a',
    model: 'gpt-4o',
    text: 'How does the outbox order writes?',
    toolIds: <String>['web_search'],
    knowledge: <KnowledgeSummary>[
      KnowledgeSummary(id: 'kb-1', name: 'Handbook'),
    ],
    webSearch: true,
  ),
  'sendTurnAccepted': const SendTurnAccepted(
    chatId: 'chat-7c1f0b2a',
    userMessageId: 'msg-user-1',
    assistantMessageId: 'msg-assistant-1',
  ),
  'turnStarted': const TurnStarted(
    chatId: 'chat-7c1f0b2a',
    messageId: 'msg-assistant-1',
    model: 'gpt-4o',
  ),
  'turnDelta': const TurnDelta(
    chatId: 'chat-7c1f0b2a',
    messageId: 'msg-assistant-1',
    text: 'The outbox drains',
    reasoning: 'Checking the DAO.',
  ),
  'turnCompleted': const TurnCompleted(
    chatId: 'chat-7c1f0b2a',
    messageId: 'msg-assistant-1',
    text: 'The outbox drains oldest-first.',
    usage: <String, int>{'prompt_tokens': 812, 'completion_tokens': 46},
  ),
  'turnFailed': const TurnFailed(
    chatId: 'chat-7c1f0b2a',
    messageId: 'msg-assistant-1',
    code: ConduitErrorCodes.serverError,
    args: <String, String>{'status': '502'},
    partialText: 'The outbox dra',
  ),
  'stopTurn': const StopTurn(chatId: 'chat-7c1f0b2a'),
  'toolSummary': const ToolSummary(
    id: 'weather',
    name: 'Weather',
    description: 'Current conditions for a city',
  ),
  'chatFile': const ChatFileDto(
    id: 'file-1',
    name: 'diagram.png',
    image: true,
    contentType: 'image/png',
  ),
  'chatUsage': const ChatUsageDto(
    generationPerSecond: 42.5,
    generationTokens: 85,
    promptPerSecond: 300,
    promptTokens: 30,
    reasoningTokens: 12,
    totalTokens: 115,
    totalSeconds: 2.25,
    queueSeconds: 0.02,
    loadSeconds: 1,
  ),
  'chatSource': const ChatSourceDto(
    label: 'dart.dev',
    url: 'https://dart.dev/overview',
    snippet: 'Dart is a client-optimized language',
  ),
  'directConnectionSummary': const DirectConnectionSummary(
    id: 'openrouter',
    name: 'OpenRouter',
    kind: DirectKind.openai,
    baseUrl: 'https://openrouter.ai/api/v1',
    hasApiKey: true,
    customHeaderNames: <String>['HTTP-Referer'],
    openRouter: true,
    tags: <String>['cloud'],
    certificateLabel: 'client.pem',
    privateKeyLabel: 'client.key',
  ),
  'directConnectionList': const DirectConnectionList(
    connections: <DirectConnectionSummary>[
      DirectConnectionSummary(
        id: 'ollama',
        name: 'Home Ollama',
        kind: DirectKind.ollama,
        baseUrl: 'http://192.168.1.10:11434',
      ),
      DirectConnectionSummary(
        id: 'owui-0',
        name: 'Team gateway',
        kind: DirectKind.openai,
        baseUrl: 'https://llm.example.com/v1',
        openWebUi: true,
        compatible: false,
      ),
    ],
    localHistory: true,
    openWebUiAvailable: true,
    preferred: true,
    usable: true,
  ),
  'directPreferred': const DirectPreferred(preferred: true),
  'directConnectionEdit': const DirectConnectionEdit(
    name: 'Azure',
    kind: DirectKind.openai,
    baseUrl: 'https://example.openai.azure.com/openai',
    apiVersion: '2024-10-21',
    apiKeyHeader: true,
    apiKey: 'sk-test',
    customHeaders: <String, String>{'X-Team': 'platform'},
    manualModelIds: <String>['gpt-4o'],
    tags: <String>['work'],
    certificatePem: '-----BEGIN CERTIFICATE-----',
    certificateLabel: 'client.pem',
  ),
  'directTestResult': const DirectTestResult(reachable: true, modelCount: 12),
  'directRef': const DirectRef(id: 'ollama'),
  'directEnable': const DirectEnable(id: 'ollama', enabled: false),
  'directHistory': const DirectHistory(localOnly: true),
  'ollamaModelStatus': const OllamaModelStatus(
    id: 'llama3.2:1b',
    name: 'llama3.2:1b',
    loaded: true,
    keepAlive: '30m',
  ),
  'ollamaModelList': const OllamaModelList(
    models: <OllamaModelStatus>[
      OllamaModelStatus(
        id: 'gpt-oss:120b',
        name: 'gpt-oss:120b',
        thinking: 'high',
      ),
    ],
    cloud: true,
  ),
  'ollamaModelAction': const OllamaModelAction(
    id: 'ollama',
    model: 'llama3.2:1b',
    value: '-1',
  ),
  'mcpApprovalSummary': const McpApprovalSummary(
    digest: 'sha256:1f2e',
    toolName: 'search',
    createdAtMs: 1790000000000,
  ),
  'mcpServerSummary': const McpServerSummary(
    id: 'mcp-1',
    name: 'Docs',
    endpoint: 'https://mcp.example.com/mcp',
    auth: McpAuth.oauth,
    oauthConnected: true,
    customHeaderNames: <String>['X-Team'],
    approvals: <McpApprovalSummary>[
      McpApprovalSummary(
        digest: 'sha256:1f2e',
        toolName: 'search',
        createdAtMs: 1790000000000,
      ),
    ],
  ),
  'mcpServerList': const McpServerList(
    servers: <McpServerSummary>[
      McpServerSummary(
        id: 'mcp-2',
        name: 'Local',
        endpoint: 'http://127.0.0.1:8808/mcp',
        enabled: false,
      ),
    ],
  ),
  'mcpServerEdit': const McpServerEdit(
    name: 'Docs',
    endpoint: 'https://mcp.example.com/mcp',
    auth: McpAuth.bearer,
    bearerToken: 'secret',
    customHeaders: <String, String>{'X-Team': 'blue'},
  ),
  'mcpTestResult': const McpTestResult(reachable: true, toolCount: 4),
  'mcpRef': const McpRef(id: 'mcp-1'),
  'mcpEnable': const McpEnable(id: 'mcp-1', enabled: false),
  'mcpForgetApproval': const McpForgetApproval(serverId: 'mcp-1'),
  'openUrl': const OpenUrl(url: 'https://auth.example.com/authorize?x=1'),
  'noteSummary': const NoteSummary(
    id: 'n1',
    title: 'Groceries',
    updatedAtMs: 1790000000000,
    pinned: true,
    preview: '- milk',
  ),
  'noteList': const NoteList(
    notes: <NoteSummary>[
      NoteSummary(
        id: 'local:n3',
        title: 'Ideas (conflict copy)',
        updatedAtMs: 1790000000001,
        conflictCopy: true,
      ),
    ],
  ),
  'noteQuery': const NoteQuery(query: 'milk'),
  'noteDetail': const NoteDetail(
    summary: NoteSummary(id: 'n1', title: 'Groceries', updatedAtMs: 1),
    files: <NoteFile>[
      NoteFile(id: 'f1', name: 'list.pdf', contentType: 'application/pdf'),
    ],
    ops: <Map<String, dynamic>>[
      <String, dynamic>{'insert': 'milk '},
      <String, dynamic>{
        'insert': 'and eggs',
        'attributes': <String, dynamic>{'bold': true},
      },
    ],
  ),
  'noteSave': const NoteSave(
    title: 'New',
    ops: <Map<String, dynamic>>[
      <String, dynamic>{'insert': 'Hello'},
    ],
  ),
  'noteRef': const NoteRef(id: 'n1'),
  'notePin': const NotePin(id: 'n1', pinned: true),
  'channelSummary': const ChannelSummary(
    id: 'c1',
    name: 'general',
    description: 'Everything',
    unread: 3,
    lastMessageAtMs: 1790000000000,
    manager: true,
    userCount: 12,
  ),
  'channelList': const ChannelList(
    channels: <ChannelSummary>[
      ChannelSummary(id: 'c2', name: 'ops', private: true, canPost: false),
    ],
    enabled: true,
  ),
  'channelUser': const ChannelUser(id: 'u1', name: 'Ada'),
  'channelReaction': const ChannelReaction(name: '👍', count: 2, mine: true),
  'channelMessageDto': const ChannelMessageDto(
    id: 'm1',
    channelId: 'c1',
    user: ChannelUser(id: 'u1', name: 'Ada'),
    content: 'Deploy is done',
    pinned: true,
    replyCount: 2,
    createdAtMs: 1790000000000,
    editedAtMs: 1790000001000,
    reactions: <ChannelReaction>[ChannelReaction(name: '🎉', count: 1)],
    mine: true,
  ),
  'channelMessagesQuery': const ChannelMessagesQuery(
    channelId: 'c1',
    parentId: 'm1',
    older: true,
  ),
  'channelMessages': const ChannelMessages(
    channelId: 'c1',
    messages: <ChannelMessageDto>[
      ChannelMessageDto(
        id: 'm2',
        channelId: 'c1',
        parentId: 'm1',
        createdAtMs: 1,
      ),
    ],
    hasOlder: true,
  ),
  'channelPost': const ChannelPost(
    channelId: 'c1',
    content: 'Hi',
    parentId: 'm1',
  ),
  'channelMessageRef': const ChannelMessageRef(
    channelId: 'c1',
    messageId: 'm1',
  ),
  'channelMessageEdit': const ChannelMessageEdit(
    channelId: 'c1',
    messageId: 'm1',
    content: 'Deploy is done.',
  ),
  'channelReact': const ChannelReact(
    channelId: 'c1',
    messageId: 'm1',
    emoji: '👍',
    add: false,
  ),
  'channelPin': const ChannelPin(
    channelId: 'c1',
    messageId: 'm1',
    pinned: true,
  ),
  'channelEdit': const ChannelEdit(
    name: 'general',
    description: 'All',
    private: true,
  ),
  'channelRef': const ChannelRef(id: 'c1'),
  'channelTyping': const ChannelTyping(channelId: 'c1', typing: false),
  'channelTypingUsers': const ChannelTypingUsers(
    channelId: 'c1',
    names: <String>['Ada', 'Grace'],
  ),
  'channelMessagesChanged': const ChannelMessagesChanged(channelId: 'c1'),
  'channelMembers': const ChannelMembers(
    users: <ChannelUser>[ChannelUser(id: 'u1', name: 'Ada')],
  ),
  'workspaceSectionAccess': const WorkspaceSectionAccess(
    manage: true,
    exportItems: true,
  ),
  'workspaceAccess': const WorkspaceAccess(
    models: WorkspaceSectionAccess(manage: true, share: true),
    prompts: WorkspaceSectionAccess(manage: true, importItems: true),
    allowUserGrants: true,
  ),
  'workspaceGrant': const WorkspaceGrant(
    principalType: 'group',
    principalId: 'g1',
    write: true,
  ),
  'workspaceItem': const WorkspaceItem(
    kind: WorkspaceKind.prompts,
    id: 'p1',
    name: 'Summarize',
    subtitle: '/summarize',
    ownerName: 'Ada',
    writeAccess: true,
    active: true,
    public: true,
    updatedAtMs: 1767225600000,
    tags: <String>['writing'],
  ),
  'workspaceQuery': const WorkspaceQuery(
    kind: WorkspaceKind.knowledge,
    query: 'docs',
    view: 'created',
    source: 'local',
    more: true,
  ),
  'workspacePage': const WorkspacePage(
    kind: WorkspaceKind.tools,
    items: <WorkspaceItem>[
      WorkspaceItem(kind: WorkspaceKind.tools, id: 't1', name: 'Web'),
    ],
    total: 3,
    hasMore: true,
  ),
  'workspaceRef': const WorkspaceRef(kind: WorkspaceKind.skills, id: 's1'),
  'workspaceRelation': const WorkspaceRelation(
    id: 'k1',
    name: 'Handbook',
    subtitle: 'Ada',
  ),
  'workspaceModelDto': const WorkspaceModelDto(
    id: 'helper',
    name: 'Helper',
    baseModelId: 'gemma3:1b',
    description: 'Answers briefly',
    tags: <String>['short'],
    system: 'Be brief.',
    stop: <String>['END'],
    suggestionPrompts: <String>['Hello'],
    capabilities: <String, bool>{'vision': true, 'usage': false},
    knowledge: <WorkspaceRelation>[WorkspaceRelation(id: 'k1', name: 'Docs')],
    toolIds: <String>['t1'],
    skillIds: <String>['s1'],
    filterIds: <String>['f1'],
    defaultFilterIds: <String>['f1'],
    actionIds: <String>['a1'],
    defaultFeatureIds: <String>['web_search'],
    ttsVoice: 'alloy',
    terminalId: 'http://127.0.0.1:8000',
    hidden: true,
    params: <String, dynamic>{'temperature': 0.5},
  ),
  'workspaceKnowledgeDto': const WorkspaceKnowledgeDto(
    id: 'k1',
    name: 'Docs',
    description: 'Manuals',
    fileCount: 4,
  ),
  'workspacePromptDto': const WorkspacePromptDto(
    id: 'p1',
    command: 'summarize',
    name: 'Summarize',
    content: 'Summarize {{CLIPBOARD}}',
    tags: <String>['writing'],
    versionId: 'v2',
    commitMessage: 'Shorter',
    production: false,
  ),
  'workspaceToolDto': const WorkspaceToolDto(
    id: 'web',
    name: 'Web',
    description: 'Fetches pages',
    content: 'class Tools: pass',
    functions: <String>['fetch'],
    hasValves: true,
    requiresServerVersion: '0.9.0',
  ),
  'workspaceSkillDto': const WorkspaceSkillDto(
    id: 'tidy',
    name: 'Tidy',
    description: 'Tidies text',
    content: 'Tidy the text.',
    active: false,
  ),
  'workspaceDetail': const WorkspaceDetail(
    kind: WorkspaceKind.skills,
    skill: WorkspaceSkillDto(id: 'tidy', name: 'Tidy'),
    grants: <WorkspaceGrant>[WorkspaceGrant(principalId: '*')],
    writeAccess: false,
    ownerName: 'Ada',
    updatedAtMs: 1767225600000,
  ),
  'workspaceSave': const WorkspaceSave(
    detail: WorkspaceDetail(
      kind: WorkspaceKind.knowledge,
      knowledge: WorkspaceKnowledgeDto(name: 'Docs'),
    ),
    create: true,
    metadataOnly: true,
  ),
  'workspaceAccessEdit': const WorkspaceAccessEdit(
    kind: WorkspaceKind.models,
    id: 'helper',
    grants: <WorkspaceGrant>[WorkspaceGrant(principalId: 'u2')],
  ),
  'workspacePrincipal': const WorkspacePrincipal(
    type: 'user',
    id: 'u2',
    name: 'Grace',
    email: 'grace@example.com',
  ),
  'workspacePrincipalQuery': const WorkspacePrincipalQuery(
    query: 'gr',
    ids: <String>['g1'],
  ),
  'workspacePrincipals': const WorkspacePrincipals(
    items: <WorkspacePrincipal>[
      WorkspacePrincipal(type: 'group', id: 'g1', name: 'Staff'),
    ],
  ),
  'workspaceExportQuery': const WorkspaceExportQuery(
    kind: WorkspaceKind.prompts,
    id: 'p1',
  ),
  'workspaceExportFile': const WorkspaceExportFile(
    filename: 'docs.zip',
    mimeType: 'application/zip',
    base64: 'UEsDBA==',
  ),
  'workspaceImport': const WorkspaceImport(
    kind: WorkspaceKind.skills,
    text: '[]',
  ),
  'workspaceImportFailure': const WorkspaceImportFailure(
    label: 'Tidy',
    reason: 'already exists',
  ),
  'workspaceImportResult': const WorkspaceImportResult(
    imported: 2,
    failed: <WorkspaceImportFailure>[WorkspaceImportFailure(label: 'Tidy')],
  ),
  'workspaceModelOptions': const WorkspaceModelOptions(
    baseModels: <WorkspaceRelation>[WorkspaceRelation(id: 'gemma3:1b')],
    knowledge: <WorkspaceRelation>[WorkspaceRelation(id: 'k1', name: 'Docs')],
    tools: <WorkspaceRelation>[WorkspaceRelation(id: 't1', name: 'Web')],
    skills: <WorkspaceRelation>[WorkspaceRelation(id: 's1', name: 'Tidy')],
    filters: <WorkspaceRelation>[WorkspaceRelation(id: 'f1', name: 'Clean')],
    actions: <WorkspaceRelation>[WorkspaceRelation(id: 'a1', name: 'Copy')],
  ),
  'workspacePromptVersion': const WorkspacePromptVersion(
    id: 'v1',
    parentId: 'v0',
    commitMessage: 'First',
    authorName: 'Ada',
    createdAtMs: 1767225600000,
    name: 'Summarize',
    command: 'summarize',
    content: 'Summarize this.',
    production: true,
  ),
  'workspacePromptHistory': const WorkspacePromptHistory(
    promptId: 'p1',
    versions: <WorkspacePromptVersion>[WorkspacePromptVersion(id: 'v1')],
  ),
  'workspacePromptVersionRef': const WorkspacePromptVersionRef(
    promptId: 'p1',
    versionId: 'v1',
  ),
  'workspacePromptDiffQuery': const WorkspacePromptDiffQuery(
    promptId: 'p1',
    fromId: 'v1',
    toId: 'v2',
  ),
  'workspacePromptDiff': const WorkspacePromptDiff(
    lines: <String>['-Summarize this.', '+Summarize this briefly.'],
    nameChanged: true,
  ),
  'workspaceValvesQuery': const WorkspaceValvesQuery(toolId: 'web', user: true),
  'workspaceValves': const WorkspaceValves(
    toolId: 'web',
    user: true,
    schema: <String, dynamic>{
      'properties': <String, dynamic>{
        'limit': <String, dynamic>{'type': 'integer', 'default': 3},
      },
    },
    values: <String, dynamic>{'limit': 5},
  ),
  'workspaceUrl': const WorkspaceUrl(url: 'https://example.com/tool.py'),
  'workspaceDirectory': const WorkspaceDirectory(
    id: 'd1',
    name: 'Guides',
    parentId: 'd0',
  ),
  'workspaceFile': const WorkspaceFile(
    id: 'f1',
    filename: 'guide.pdf',
    contentType: 'application/pdf',
    size: 2048,
    updatedAtMs: 1767225600000,
    status: 'failed',
    error: 'unreadable',
  ),
  'workspaceFilesQuery': const WorkspaceFilesQuery(
    knowledgeId: 'k1',
    directoryId: 'd1',
    more: true,
  ),
  'workspaceFiles': const WorkspaceFiles(
    knowledgeId: 'k1',
    directoryId: 'd1',
    breadcrumbs: <WorkspaceDirectory>[WorkspaceDirectory(id: 'd1')],
    directories: <WorkspaceDirectory>[WorkspaceDirectory(id: 'd2')],
    files: <WorkspaceFile>[WorkspaceFile(id: 'f1')],
    pending: <WorkspaceFile>[WorkspaceFile(id: 'f2', status: 'processing')],
    total: 9,
    hasMore: true,
  ),
  'workspaceFilesAttach': const WorkspaceFilesAttach(
    knowledgeId: 'k1',
    directoryId: 'd1',
    fileIds: <String>['f1', 'f2'],
  ),
  'workspaceFileAction': const WorkspaceFileAction(
    knowledgeId: 'k1',
    fileId: 'f1',
    op: WorkspaceFileOp.move,
    filename: 'renamed.pdf',
    directoryId: 'd2',
  ),
  'workspaceDirectoryAction': const WorkspaceDirectoryAction(
    knowledgeId: 'k1',
    op: WorkspaceDirectoryOp.rename,
    directoryId: 'd1',
    parentId: 'd0',
    name: 'Manuals',
  ),
  'workspaceChanged': const WorkspaceChanged(
    kind: WorkspaceKind.models,
    id: 'helper',
  ),
  'terminalServerDto': const TerminalServerDto(
    id: 'http://127.0.0.1:8000',
    name: 'Laptop',
    kind: 'direct',
    requiresSavedChat: true,
  ),
  'terminalScope': const TerminalScope(scopeId: 'c1'),
  'terminalServers': const TerminalServers(
    servers: <TerminalServerDto>[TerminalServerDto(id: 't1', name: 'Box')],
    selectedId: 't1',
  ),
  'terminalSelect': const TerminalSelect(serverId: 't1'),
  'terminalAttach': const TerminalAttach(serverId: 't1', scopeId: 'c1'),
  'terminalAttached': const TerminalAttached(
    handle: 'h1',
    cwd: '/home/ada',
    supported: false,
  ),
  'terminalPath': const TerminalPath(handle: 'h1', path: '/home/ada/'),
  'terminalEntry': const TerminalEntry(
    name: 'notes.txt',
    path: '/home/ada/notes.txt',
    directory: false,
    size: 12,
    modifiedAtMs: 1767225600000,
  ),
  'terminalListing': const TerminalListing(
    path: '/home/ada/',
    entries: <TerminalEntry>[
      TerminalEntry(name: 'src', path: '/home/ada/src/', directory: true),
    ],
  ),
  'terminalFileContent': const TerminalFileContent(
    name: 'logo.png',
    contentType: 'image/png',
    text: 'hello',
    base64: 'iVBORw0K',
  ),
  'terminalFileAction': const TerminalFileAction(
    handle: 'h1',
    op: TerminalFileOp.move,
    path: '/home/ada/a.txt',
    destination: '/home/ada/b.txt',
  ),
  'terminalPort': const TerminalPort(port: 3000, pid: 42, process: 'node'),
  'terminalPorts': const TerminalPorts(
    ports: <TerminalPort>[TerminalPort(port: 8080)],
  ),
  'terminalHandleRef': const TerminalHandleRef(handle: 'h1'),
  'terminalPortRef': const TerminalPortRef(handle: 'h1', port: 3000),
  'terminalPreview': const TerminalPreview(url: 'http://127.0.0.1:41234/k1'),
  'hermesSettings': const HermesSettings(
    enabled: true,
    baseUrl: 'https://hermes.example.com/v1',
    hasApiKey: true,
    hasSessionKey: true,
    desktopProfile: 'work',
    desktopAuthKind: 'nativePkce',
    desktopSignedIn: true,
    allowSelfSignedCertificates: true,
    usable: true,
  ),
  'hermesSettingsEdit': const HermesSettingsEdit(
    enabled: false,
    baseUrl: 'https://hermes.example.com',
    mode: 'desktop',
    apiKey: 'k',
    sessionKey: '',
    desktopProfile: 'work',
    desktopAuthKind: 'dashboardCookie',
    allowSelfSignedCertificates: true,
  ),
  'hermesTestResult': const HermesTestResult(reason: 'unauthorized'),
  'hermesCapabilitiesDto': const HermesCapabilitiesDto(
    runApproval: true,
    skills: true,
    toolsets: true,
    jobs: true,
    jobsAdmin: true,
    sessions: true,
    inputImages: true,
    inputFiles: true,
  ),
  'hermesStatus': const HermesStatus(
    configured: true,
    reachable: true,
    capabilities: HermesCapabilitiesDto(jobs: true),
    details: <String, dynamic>{'active_sessions': 2},
  ),
  'hermesSessionDto': const HermesSessionDto(
    id: 's1',
    chatId: 'local:hermes_s1',
    title: 'Plan the trip',
    preview: 'Where to?',
    updatedAtMs: 1767225600000,
  ),
  'hermesSessions': const HermesSessions(
    sessions: <HermesSessionDto>[
      HermesSessionDto(id: 's2', chatId: 'local:hermes_s2'),
    ],
  ),
  'hermesRef': const HermesRef(id: 's1'),
  'hermesRename': const HermesRename(id: 's1', title: 'Trip'),
  'hermesJobDto': const HermesJobDto(
    id: 'j1',
    name: 'Morning brief',
    prompt: 'Summarise the news',
    schedule: '0 8 * * *',
    scheduleText: 'At 08:00',
    enabled: false,
    lastStatus: 'ok',
    lastError: 'none',
    lastRunAtMs: 1767225600000,
    nextRunAtMs: 1767312000000,
  ),
  'hermesJobs': const HermesJobs(jobs: <HermesJobDto>[HermesJobDto(id: 'j2')]),
  'hermesJobEdit': const HermesJobEdit(
    id: 'j1',
    name: 'Brief',
    prompt: 'Summarise',
    schedule: 'every 1h',
  ),
  'hermesJobToggle': const HermesJobToggle(id: 'j1', enabled: true),
  'hermesSkillDto': const HermesSkillDto(
    name: 'review',
    description: 'Reviews code',
  ),
  'hermesToolsetDto': const HermesToolsetDto(
    name: 'web',
    label: 'Web',
    description: 'Search and fetch',
    enabled: false,
    tools: <String>['search', 'fetch'],
  ),
  'hermesCatalog': const HermesCatalog(
    skills: <HermesSkillDto>[HermesSkillDto(name: 'review')],
    toolsets: <HermesToolsetDto>[HermesToolsetDto(name: 'web')],
  ),
  'voiceSettings': const VoiceSettings(
    serverStt: true,
    localStt: true,
    sttEngine: 'local',
    localModel: 'base.en',
    localReady: true,
    serverTts: true,
    sttLanguage: 'en',
    silenceMs: 1500,
    holdToTalk: true,
    autoSend: true,
    ttsEngine: 'server',
    deviceVoice: 'Samantha',
    serverVoice: 'alloy',
    rate: 0.75,
    pitch: 1.1,
    volume: 0.8,
    splitOn: 'paragraphs',
  ),
  'voiceSettingsEdit': const VoiceSettingsEdit(
    sttEngine: 'local',
    localModel: 'tiny',
    clearSttLanguage: true,
    silenceMs: 1000,
    ttsEngine: 'device',
    deviceVoice: 'Alex',
    clearServerVoice: true,
    rate: 0.6,
  ),
  'voiceOption': const VoiceOption(id: 'alloy', name: 'Alloy'),
  'voiceVoices': const VoiceVoices(
    voices: <VoiceOption>[VoiceOption(id: 'echo')],
    defaultVoice: 'alloy',
  ),
  'voiceSpeak': const VoiceSpeak(text: 'Hello there.', voice: 'alloy'),
  'voiceSpeech': const VoiceSpeech(jobId: 'tts-1'),
  'voiceTranscript': const VoiceTranscript(text: 'The quick brown fox.'),
  'voiceModel': const VoiceModel(
    id: 'base.en',
    name: 'Base (English)',
    sizeBytes: 147964211,
    englishOnly: true,
    receivedBytes: 1024,
  ),
  'voiceModels': const VoiceModels(
    models: <VoiceModel>[VoiceModel(id: 'tiny', downloaded: true)],
    failedId: 'small',
    failure: 'checksum',
  ),
  'voiceModelRef': const VoiceModelRef(id: 'tiny.en'),
  'terminalDisplayFile': const TerminalDisplayFile(
    chatId: 'c1',
    path: '/home/user/report.md',
  ),
  'noteFile': const NoteFile(
    id: 'f1',
    name: 'recording.webm',
    size: 48213,
    contentType: 'audio/webm',
  ),
  'noteAttach': const NoteAttach(
    noteId: 'n1',
    file: NoteFile(id: 'f1', name: 'recording.webm'),
  ),
  'noteDetach': const NoteDetach(noteId: 'n1', fileId: 'f1'),
  'noteAi': const NoteAi(
    ops: <Map<String, dynamic>>[
      <String, dynamic>{'insert': 'milk, eggs'},
    ],
    model: 'gemma3:1b',
  ),
  'noteTitle': const NoteTitle(title: '🛒 Shopping list'),
  'noteBody': const NoteBody(
    ops: <Map<String, dynamic>>[
      <String, dynamic>{'insert': 'Shopping'},
    ],
  ),
  'notesChanged': const NotesChanged(noteId: 'n1'),
  'mcpPromptArgument': const McpPromptArgument(
    name: 'topic',
    label: 'Topic',
    required: true,
  ),
  'mcpPromptSummary': const McpPromptSummary(
    name: 'summarize',
    displayName: 'Summarize',
    description: 'Summarizes a topic.',
    arguments: <McpPromptArgument>[
      McpPromptArgument(name: 'topic', label: 'Topic', required: true),
    ],
  ),
  'mcpResourceSummary': const McpResourceSummary(
    uri: 'file:///notes/today.md',
    displayName: 'Today',
    mimeType: 'text/markdown',
  ),
  'mcpContent': const McpContent(
    serverId: 'mcp-1',
    serverName: 'Docs',
    prompts: <McpPromptSummary>[
      McpPromptSummary(name: 'summarize', displayName: 'Summarize'),
    ],
    resources: <McpResourceSummary>[
      McpResourceSummary(uri: 'file:///a.txt', displayName: 'a.txt'),
    ],
  ),
  'mcpGetPrompt': const McpGetPrompt(
    serverId: 'mcp-1',
    name: 'summarize',
    arguments: <String, String>{'topic': 'llamas'},
  ),
  'mcpReadResource': const McpReadResource(
    serverId: 'mcp-1',
    uri: 'file:///a.txt',
  ),
  'mcpPromptMessage': const McpPromptMessage(role: 'user', text: 'Hi'),
  'mcpContentPreview': const McpContentPreview(
    messages: <McpPromptMessage>[
      McpPromptMessage(role: 'user', text: 'Summarize llamas.'),
      McpPromptMessage(role: 'assistant', text: 'Sure.'),
    ],
  ),
  'knowledgeSummary': const KnowledgeSummary(
    id: 'kb-1',
    name: 'Handbook',
    description: 'Team policies',
  ),
  'knowledgeQuery': const KnowledgeQuery(query: 'hand'),
  'knowledgeList': const KnowledgeList(
    items: <KnowledgeSummary>[KnowledgeSummary(id: 'kb-1', name: 'Handbook')],
  ),
  'promptSummary': const PromptSummary(
    command: '/standup',
    title: 'Stand-up notes',
    description: 'Yesterday, today, blockers',
    usesClipboard: true,
  ),
  'promptList': const PromptList(
    prompts: <PromptSummary>[
      PromptSummary(command: '/standup', title: 'Stand-up notes'),
    ],
  ),
  'renderPrompt': const RenderPrompt(
    command: '/standup',
    values: <String, String>{'team': 'Platform'},
    clipboard: 'pasted',
  ),
  'promptInput': const PromptInput(
    name: 'team',
    label: 'Team',
    type: 'select',
    placeholder: 'Which team',
    defaultValue: 'Platform',
    required: true,
    options: <String>['Platform', 'Mobile'],
  ),
  'renderedPrompt': const RenderedPrompt(
    content: 'Notes for {{team}}',
    inputs: <PromptInput>[PromptInput(name: 'team', label: 'Team')],
  ),
  'composerOptions': const ComposerOptions(
    webSearch: true,
    tools: <ToolSummary>[ToolSummary(id: 'weather', name: 'Weather')],
    mcpTools: <ToolSummary>[ToolSummary(id: 'local_mcp:mcp-1', name: 'Docs')],
  ),
  'syncState': const SyncState(running: true, progress: 0.4, online: false),
  'chatsChanged': const ChatsChanged(chatId: 'chat-7c1f0b2a'),
  'routeRemap': const RouteRemap(
    fromId: 'local:4b1c9e2d',
    toId: 'chat-7c1f0b2a',
  ),
  'editTurn': const EditTurn(
    chatId: 'chat-7c1f0b2a',
    messageId: 'msg-user-01',
    text: 'What I meant to ask',
  ),
  'chatMessageVersionDto': const ChatMessageVersionDto(
    id: 'msg-earlier',
    content: 'The first answer.',
    timestampMs: 1758412800000,
    model: 'llama3.2:1b',
  ),
  'folderSummary': const FolderSummary(
    id: 'folder-1d7c',
    name: 'Research',
    expanded: true,
  ),
  'archivedVisibility': const ArchivedVisibility(visible: true),
  'uploadedFile': const UploadedFile(
    id: 'file-3b91d0c4',
    name: 'notes.pdf',
    size: 182_344,
    contentType: 'application/pdf',
  ),
  'networkReport': const NetworkReport(online: false),
  'chatSystemPrompt': const ChatSystemPrompt(
    chatId: 'chat-7c1f0b2a',
    prompt: 'Answer as a sync-engine reviewer.',
  ),
  'bulkChats': const BulkChats(
    chatIds: <String>['chat-1', 'chat-2'],
    action: BulkChatAction.move,
    folderId: 'folder-1',
  ),
  'bulkChatsResult': const BulkChatsResult(
    list: ChatList(),
    failed: <String>['chat-2'],
  ),
  'chatTreeNode': const ChatTreeNode(
    id: 'msg-2',
    parentId: 'msg-1',
    role: 'assistant',
    preview: 'Oldest first.',
    timestampMs: 1758412800000,
    model: 'gpt-4o',
  ),
  'chatTree': const ChatTree(
    chatId: 'chat-7c1f0b2a',
    nodes: <ChatTreeNode>[
      ChatTreeNode(id: 'msg-1', role: 'user', preview: 'Hi', timestampMs: 1),
    ],
    currentId: 'msg-1',
  ),
  'chatCurrent': const ChatCurrent(chatId: 'chat-7c1f0b2a', messageId: 'msg-2'),
  'folderRef': const FolderRef(folderId: 'folder-1'),
  'folderContents': const FolderContents(
    folder: FolderSummary(id: 'folder-1', name: 'Work'),
    chats: <ChatSummary>[
      ChatSummary(id: 'chat-1', title: 'Q3 plan', updatedAtMs: 1758412800000),
    ],
  ),
  'moveChat': const MoveChat(chatId: 'chat-7c1f0b2a', folderId: 'folder-1'),
  'tag': const TagDto(id: 'work_notes', name: 'Work notes'),
  'tagList': const TagList(
    tags: <TagDto>[TagDto(id: 'q3', name: 'Q3')],
  ),
  'chatTagEdit': const ChatTagEdit(chatId: 'chat-7c1f0b2a', name: 'Work notes'),
  'rateTurn': const RateTurn(
    chatId: 'chat-7c1f0b2a',
    messageId: 'msg-2f9d4c17',
    rating: -1,
  ),
  'regenerateTurn': const RegenerateTurn(
    chatId: 'chat-7c1f0b2a',
    messageId: 'msg-2f9d4c17',
    model: 'llama3.2:1b',
  ),
  'chatSummary': const ChatSummary(
    id: 'chat-7c1f0b2a',
    title: 'Rewriting the sync engine',
    updatedAtMs: 1758412800000,
    pinned: true,
    model: 'gpt-4o',
    tags: <String>['work', 'architecture'],
    shared: true,
  ),
  'chatList': const ChatList(
    chats: <ChatSummary>[
      ChatSummary(
        id: 'chat-7c1f0b2a',
        title: 'Rewriting the sync engine',
        updatedAtMs: 1758412800000,
      ),
    ],
    hasMore: true,
    archivedCount: 12,
  ),
  'chatMessage': const ChatMessageDto(
    id: 'msg-1',
    role: 'assistant',
    content: 'The outbox drains oldest-first.',
    timestampMs: 1758412800000,
    model: 'gpt-4o',
    streaming: true,
    sources: <ChatSourceDto>[
      ChatSourceDto(
        label: 'Sync design notes',
        url: 'https://example.com/sync',
      ),
    ],
    usage: ChatUsageDto(generationTokens: 7, totalSeconds: 0.5),
    rating: 1,
  ),
  'chatDetail': const ChatDetail(
    summary: ChatSummary(
      id: 'chat-7c1f0b2a',
      title: 'Rewriting the sync engine',
      updatedAtMs: 1758412800000,
    ),
    messages: <ChatMessageDto>[
      ChatMessageDto(
        id: 'msg-1',
        role: 'user',
        content: 'How does the outbox order writes?',
        timestampMs: 1758412700000,
      ),
    ],
  ),
  'chatRef': const ChatRef(id: 'chat-7c1f0b2a'),
  'renameChat': const RenameChat(
    id: 'chat-7c1f0b2a',
    title: 'Rewriting the sync engine',
  ),
  'setChatFlag': const SetChatFlag(id: 'chat-7c1f0b2a', value: true),
  'chatShare': const ChatShare(
    chatId: 'chat-7c1f0b2a',
    shareId: '3f0b2a7c-1d4e-4a9c-8b7e-2d3f4a5b6c7d',
  ),
  'chatShareRemoved': const ChatShare(chatId: 'chat-7c1f0b2a'),
  'chatSearchQuery': const ChatSearchQuery(query: 'outbox', limit: 20),
  'chatSearchHit': const ChatSearchHit(
    chatId: 'chat-7c1f0b2a',
    title: 'Rewriting the sync engine',
    snippet: 'the <b>outbox</b> drains oldest-first',
    updatedAtMs: 1758412800000,
  ),
  'chatSearchResults': const ChatSearchResults(
    hits: <ChatSearchHit>[
      ChatSearchHit(
        chatId: 'chat-7c1f0b2a',
        title: 'Rewriting the sync engine',
        updatedAtMs: 1758412800000,
      ),
    ],
    complete: false,
  ),
  'serverStatusNoServer': const ServerStatus(maxSupportedVersion: '0.11.3'),
  'serverStatusReachable': const ServerStatus(
    activeServerId: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
    capabilities: Capabilities(
      workspace: true,
      notes: true,
      channels: true,
      serverStt: true,
      serverTts: true,
      deviceTts: true,
      branchNavigation: true,
      tags: true,
    ),
    reachability: ServerReachability.reachable,
    version: '0.11.3',
    maxSupportedVersion: '0.11.3',
  ),
  'serverStatusUnreachable': const ServerStatus(
    activeServerId: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
    reachability: ServerReachability.unreachable,
    errorCode: ConduitErrorCodes.connectionFailed,
    maxSupportedVersion: '0.11.3',
  ),
  'serverStatusTooNew': const ServerStatus(
    activeServerId: '7c1f0b2a-5e3d-4a9c-8b7e-1d2f3a4b5c6d',
    reachability: ServerReachability.reachable,
    version: '0.99.0',
    isVersionSupported: false,
    maxSupportedVersion: '0.11.3',
  ),
  'appPreferencesDefault': const AppPreferences(),
  'appPreferencesFull': const AppPreferences(
    themeMode: AppThemeMode.dark,
    themePaletteId: 't3_chat',
    localeCode: 'zh-Hant',
  ),
  'appPreferencesPatch': const AppPreferencesPatch(
    themePaletteId: 'claude',
    clearLocaleCode: true,
  ),
  'signOutResult': const SignOutResult(
    outcome: SignOutOutcome.localDataClearedSessionCleanupIncomplete,
    remaining: <String>['cookies'],
  ),
};

/// `fromJson` for each fixture, keyed the same way.
///
/// Kept beside [protocolFixtures] so a new DTO cannot be added to one without
/// the other; the golden test asserts the two key sets match.
final Map<String, Object Function(Map<String, dynamic>)> protocolDecoders =
    <String, Object Function(Map<String, dynamic>)>{
      'handshakeRequest': HandshakeRequest.fromJson,
      'handshakeResponse': HandshakeResponse.fromJson,
      'capabilitiesNone': Capabilities.fromJson,
      'rpcErrorMinimal': RpcError.fromJson,
      'rpcErrorFull': RpcError.fromJson,
      'eventEnvelope': EventEnvelope.fromJson,
      'eventSubscription': EventSubscription.fromJson,
      'uiRequest': UiRequest.fromJson,
      'uiResponse': UiResponse.fromJson,
      'pongResult': PongResult.fromJson,
      'shutdownResult': ShutdownResult.fromJson,
      'diagnosticsExport': DiagnosticsExport.fromJson,
      'daemonPaths': DaemonPaths.fromJson,
      'serverSummaryMinimal': ServerSummary.fromJson,
      'serverSummaryFull': ServerSummary.fromJson,
      'serverDraft': ServerDraft.fromJson,
      'serverRef': ServerRef.fromJson,
      'serverList': ServerList.fromJson,
      'authSnapshotSignedOut': AuthSnapshot.fromJson,
      'authSnapshotSignedIn': AuthSnapshot.fromJson,
      'authSnapshotError': AuthSnapshot.fromJson,
      'authUser': AuthUser.fromJson,
      'passwordLogin': PasswordLogin.fromJson,
      'apiKeyLogin': ApiKeyLogin.fromJson,
      'externalAuthCompletion': ExternalAuthCompletion.fromJson,
      'signOutRequest': SignOutRequest.fromJson,
      'modelSummary': ModelSummary.fromJson,
      'modelList': ModelList.fromJson,
      'selectModel': SelectModel.fromJson,
      'sendTurn': SendTurn.fromJson,
      'sendTurnAccepted': SendTurnAccepted.fromJson,
      'turnStarted': TurnStarted.fromJson,
      'turnDelta': TurnDelta.fromJson,
      'turnCompleted': TurnCompleted.fromJson,
      'turnFailed': TurnFailed.fromJson,
      'stopTurn': StopTurn.fromJson,
      'toolSummary': ToolSummary.fromJson,
      'chatFile': ChatFileDto.fromJson,
      'chatUsage': ChatUsageDto.fromJson,
      'chatSource': ChatSourceDto.fromJson,
      'directConnectionSummary': DirectConnectionSummary.fromJson,
      'directConnectionList': DirectConnectionList.fromJson,
      'directConnectionEdit': DirectConnectionEdit.fromJson,
      'directTestResult': DirectTestResult.fromJson,
      'directRef': DirectRef.fromJson,
      'directEnable': DirectEnable.fromJson,
      'directHistory': DirectHistory.fromJson,
      'directPreferred': DirectPreferred.fromJson,
      'ollamaModelStatus': OllamaModelStatus.fromJson,
      'ollamaModelList': OllamaModelList.fromJson,
      'ollamaModelAction': OllamaModelAction.fromJson,
      'mcpApprovalSummary': McpApprovalSummary.fromJson,
      'mcpServerSummary': McpServerSummary.fromJson,
      'mcpServerList': McpServerList.fromJson,
      'mcpServerEdit': McpServerEdit.fromJson,
      'mcpTestResult': McpTestResult.fromJson,
      'mcpRef': McpRef.fromJson,
      'mcpEnable': McpEnable.fromJson,
      'mcpForgetApproval': McpForgetApproval.fromJson,
      'openUrl': OpenUrl.fromJson,
      'noteSummary': NoteSummary.fromJson,
      'noteList': NoteList.fromJson,
      'noteQuery': NoteQuery.fromJson,
      'noteDetail': NoteDetail.fromJson,
      'noteSave': NoteSave.fromJson,
      'noteRef': NoteRef.fromJson,
      'notePin': NotePin.fromJson,
      'channelSummary': ChannelSummary.fromJson,
      'channelList': ChannelList.fromJson,
      'channelUser': ChannelUser.fromJson,
      'channelReaction': ChannelReaction.fromJson,
      'channelMessageDto': ChannelMessageDto.fromJson,
      'channelMessagesQuery': ChannelMessagesQuery.fromJson,
      'channelMessages': ChannelMessages.fromJson,
      'channelPost': ChannelPost.fromJson,
      'channelMessageRef': ChannelMessageRef.fromJson,
      'channelMessageEdit': ChannelMessageEdit.fromJson,
      'channelReact': ChannelReact.fromJson,
      'channelPin': ChannelPin.fromJson,
      'channelEdit': ChannelEdit.fromJson,
      'channelRef': ChannelRef.fromJson,
      'channelTyping': ChannelTyping.fromJson,
      'channelTypingUsers': ChannelTypingUsers.fromJson,
      'channelMessagesChanged': ChannelMessagesChanged.fromJson,
      'channelMembers': ChannelMembers.fromJson,
      'workspaceSectionAccess': WorkspaceSectionAccess.fromJson,
      'workspaceAccess': WorkspaceAccess.fromJson,
      'workspaceGrant': WorkspaceGrant.fromJson,
      'workspaceItem': WorkspaceItem.fromJson,
      'workspaceQuery': WorkspaceQuery.fromJson,
      'workspacePage': WorkspacePage.fromJson,
      'workspaceRef': WorkspaceRef.fromJson,
      'workspaceRelation': WorkspaceRelation.fromJson,
      'workspaceModelDto': WorkspaceModelDto.fromJson,
      'workspaceKnowledgeDto': WorkspaceKnowledgeDto.fromJson,
      'workspacePromptDto': WorkspacePromptDto.fromJson,
      'workspaceToolDto': WorkspaceToolDto.fromJson,
      'workspaceSkillDto': WorkspaceSkillDto.fromJson,
      'workspaceDetail': WorkspaceDetail.fromJson,
      'workspaceSave': WorkspaceSave.fromJson,
      'workspaceAccessEdit': WorkspaceAccessEdit.fromJson,
      'workspacePrincipal': WorkspacePrincipal.fromJson,
      'workspacePrincipalQuery': WorkspacePrincipalQuery.fromJson,
      'workspacePrincipals': WorkspacePrincipals.fromJson,
      'workspaceExportQuery': WorkspaceExportQuery.fromJson,
      'workspaceExportFile': WorkspaceExportFile.fromJson,
      'workspaceImport': WorkspaceImport.fromJson,
      'workspaceImportFailure': WorkspaceImportFailure.fromJson,
      'workspaceImportResult': WorkspaceImportResult.fromJson,
      'workspaceModelOptions': WorkspaceModelOptions.fromJson,
      'workspacePromptVersion': WorkspacePromptVersion.fromJson,
      'workspacePromptHistory': WorkspacePromptHistory.fromJson,
      'workspacePromptVersionRef': WorkspacePromptVersionRef.fromJson,
      'workspacePromptDiffQuery': WorkspacePromptDiffQuery.fromJson,
      'workspacePromptDiff': WorkspacePromptDiff.fromJson,
      'workspaceValvesQuery': WorkspaceValvesQuery.fromJson,
      'workspaceValves': WorkspaceValves.fromJson,
      'workspaceUrl': WorkspaceUrl.fromJson,
      'workspaceDirectory': WorkspaceDirectory.fromJson,
      'workspaceFile': WorkspaceFile.fromJson,
      'workspaceFilesQuery': WorkspaceFilesQuery.fromJson,
      'workspaceFiles': WorkspaceFiles.fromJson,
      'workspaceFilesAttach': WorkspaceFilesAttach.fromJson,
      'workspaceFileAction': WorkspaceFileAction.fromJson,
      'workspaceDirectoryAction': WorkspaceDirectoryAction.fromJson,
      'workspaceChanged': WorkspaceChanged.fromJson,
      'terminalServerDto': TerminalServerDto.fromJson,
      'terminalScope': TerminalScope.fromJson,
      'terminalServers': TerminalServers.fromJson,
      'terminalSelect': TerminalSelect.fromJson,
      'terminalAttach': TerminalAttach.fromJson,
      'terminalAttached': TerminalAttached.fromJson,
      'terminalPath': TerminalPath.fromJson,
      'terminalEntry': TerminalEntry.fromJson,
      'terminalListing': TerminalListing.fromJson,
      'terminalFileContent': TerminalFileContent.fromJson,
      'terminalFileAction': TerminalFileAction.fromJson,
      'terminalPort': TerminalPort.fromJson,
      'terminalPorts': TerminalPorts.fromJson,
      'terminalHandleRef': TerminalHandleRef.fromJson,
      'terminalPortRef': TerminalPortRef.fromJson,
      'terminalPreview': TerminalPreview.fromJson,
      'hermesSettings': HermesSettings.fromJson,
      'hermesSettingsEdit': HermesSettingsEdit.fromJson,
      'hermesTestResult': HermesTestResult.fromJson,
      'hermesCapabilitiesDto': HermesCapabilitiesDto.fromJson,
      'hermesStatus': HermesStatus.fromJson,
      'hermesSessionDto': HermesSessionDto.fromJson,
      'hermesSessions': HermesSessions.fromJson,
      'hermesRef': HermesRef.fromJson,
      'hermesRename': HermesRename.fromJson,
      'hermesJobDto': HermesJobDto.fromJson,
      'hermesJobs': HermesJobs.fromJson,
      'hermesJobEdit': HermesJobEdit.fromJson,
      'hermesJobToggle': HermesJobToggle.fromJson,
      'hermesSkillDto': HermesSkillDto.fromJson,
      'hermesToolsetDto': HermesToolsetDto.fromJson,
      'hermesCatalog': HermesCatalog.fromJson,
      'voiceSettings': VoiceSettings.fromJson,
      'voiceSettingsEdit': VoiceSettingsEdit.fromJson,
      'voiceOption': VoiceOption.fromJson,
      'voiceVoices': VoiceVoices.fromJson,
      'voiceSpeak': VoiceSpeak.fromJson,
      'voiceSpeech': VoiceSpeech.fromJson,
      'voiceTranscript': VoiceTranscript.fromJson,
      'voiceModel': VoiceModel.fromJson,
      'voiceModels': VoiceModels.fromJson,
      'voiceModelRef': VoiceModelRef.fromJson,
      'terminalDisplayFile': TerminalDisplayFile.fromJson,
      'noteFile': NoteFile.fromJson,
      'noteAttach': NoteAttach.fromJson,
      'noteDetach': NoteDetach.fromJson,
      'noteAi': NoteAi.fromJson,
      'noteTitle': NoteTitle.fromJson,
      'noteBody': NoteBody.fromJson,
      'notesChanged': NotesChanged.fromJson,
      'mcpPromptArgument': McpPromptArgument.fromJson,
      'mcpPromptSummary': McpPromptSummary.fromJson,
      'mcpResourceSummary': McpResourceSummary.fromJson,
      'mcpContent': McpContent.fromJson,
      'mcpGetPrompt': McpGetPrompt.fromJson,
      'mcpReadResource': McpReadResource.fromJson,
      'mcpPromptMessage': McpPromptMessage.fromJson,
      'mcpContentPreview': McpContentPreview.fromJson,
      'knowledgeSummary': KnowledgeSummary.fromJson,
      'knowledgeQuery': KnowledgeQuery.fromJson,
      'knowledgeList': KnowledgeList.fromJson,
      'promptSummary': PromptSummary.fromJson,
      'promptList': PromptList.fromJson,
      'renderPrompt': RenderPrompt.fromJson,
      'promptInput': PromptInput.fromJson,
      'renderedPrompt': RenderedPrompt.fromJson,
      'composerOptions': ComposerOptions.fromJson,
      'syncState': SyncState.fromJson,
      'chatsChanged': ChatsChanged.fromJson,
      'routeRemap': RouteRemap.fromJson,
      'editTurn': EditTurn.fromJson,
      'chatMessageVersionDto': ChatMessageVersionDto.fromJson,
      'folderSummary': FolderSummary.fromJson,
      'archivedVisibility': ArchivedVisibility.fromJson,
      'uploadedFile': UploadedFile.fromJson,
      'networkReport': NetworkReport.fromJson,
      'chatSystemPrompt': ChatSystemPrompt.fromJson,
      'bulkChats': BulkChats.fromJson,
      'bulkChatsResult': BulkChatsResult.fromJson,
      'chatTreeNode': ChatTreeNode.fromJson,
      'chatTree': ChatTree.fromJson,
      'chatCurrent': ChatCurrent.fromJson,
      'folderRef': FolderRef.fromJson,
      'folderContents': FolderContents.fromJson,
      'moveChat': MoveChat.fromJson,
      'tag': TagDto.fromJson,
      'tagList': TagList.fromJson,
      'chatTagEdit': ChatTagEdit.fromJson,
      'rateTurn': RateTurn.fromJson,
      'regenerateTurn': RegenerateTurn.fromJson,
      'chatSummary': ChatSummary.fromJson,
      'chatList': ChatList.fromJson,
      'chatMessage': ChatMessageDto.fromJson,
      'chatDetail': ChatDetail.fromJson,
      'chatRef': ChatRef.fromJson,
      'renameChat': RenameChat.fromJson,
      'setChatFlag': SetChatFlag.fromJson,
      'chatShare': ChatShare.fromJson,
      'chatShareRemoved': ChatShare.fromJson,
      'chatSearchQuery': ChatSearchQuery.fromJson,
      'chatSearchHit': ChatSearchHit.fromJson,
      'chatSearchResults': ChatSearchResults.fromJson,
      'serverStatusNoServer': ServerStatus.fromJson,
      'serverStatusReachable': ServerStatus.fromJson,
      'serverStatusUnreachable': ServerStatus.fromJson,
      'serverStatusTooNew': ServerStatus.fromJson,
      'appPreferencesDefault': AppPreferences.fromJson,
      'appPreferencesFull': AppPreferences.fromJson,
      'appPreferencesPatch': AppPreferencesPatch.fromJson,
      'signOutResult': SignOutResult.fromJson,
    };

/// Every fixture's `toJson`, so the checker can encode without `dynamic`.
Map<String, dynamic> encodeFixture(Object fixture) =>
    (fixture as dynamic).toJson() as Map<String, dynamic>;
