import 'dart:async';
import 'dart:convert';

/// Secrets and locations handed to the daemon at startup.
///
/// These arrive on stdin as a single JSON line, never on argv and never in the
/// environment: both are readable by any other process on the machine
/// (`/proc/<pid>/cmdline`, `ps`, `/proc/<pid>/environ`), and the session token
/// is a bearer credential for the whole core.
class BootstrapConfig {
  BootstrapConfig({
    required this.sessionToken,
    required this.masterKey,
    required this.userDataDir,
    this.logLevel = 'info',
  });

  /// Authorizes RPC and HTTP calls from the renderer. Regenerated by Electron
  /// on every launch, so a leaked token dies with the process.
  final String sessionToken;

  /// Base64 of the 32-byte key that encrypts the secure store. Electron holds
  /// it in `safeStorage`; the daemon keeps it in memory only.
  final String masterKey;

  /// Electron's `userData` directory. Everything the daemon writes lives here.
  final String userDataDir;

  final String logLevel;

  /// Parses one JSON line.
  ///
  /// Throws [FormatException] with a message safe to log — it names the field
  /// that is wrong but never echoes a value, because the payload is secret.
  factory BootstrapConfig.parse(String line) {
    final Object? decoded;
    try {
      decoded = jsonDecode(line);
    } on FormatException {
      throw const FormatException('bootstrap line is not valid JSON');
    }
    if (decoded is! Map<String, dynamic>) {
      throw const FormatException('bootstrap line must be a JSON object');
    }

    String required(String key) {
      final value = decoded is Map ? decoded[key] : null;
      if (value is! String || value.isEmpty) {
        throw FormatException('bootstrap field "$key" must be a non-empty '
            'string');
      }
      return value;
    }

    final token = required('sessionToken');
    // 32 bytes as base64url-without-padding is 43 chars. Reject anything
    // shorter outright rather than letting a truncated token silently weaken
    // the only thing guarding the RPC port.
    if (token.length < 43) {
      throw const FormatException(
        'bootstrap field "sessionToken" is too short; expected at least 256 '
        'bits of entropy',
      );
    }

    final key = required('masterKey');
    try {
      if (base64.decode(key).length != 32) {
        throw const FormatException(
          'bootstrap field "masterKey" must decode to exactly 32 bytes',
        );
      }
    } on FormatException catch (error) {
      // Re-throw our own message unchanged; replace base64's, which would
      // include a fragment of the key.
      if (error.message.startsWith('bootstrap field')) rethrow;
      throw const FormatException(
        'bootstrap field "masterKey" is not valid base64',
      );
    }

    final level = decoded['logLevel'];
    return BootstrapConfig(
      sessionToken: token,
      masterKey: key,
      userDataDir: required('userDataDir'),
      logLevel: level is String && level.isNotEmpty ? level : 'info',
    );
  }

  /// Reads exactly one line from [stdinLines].
  ///
  /// Times out rather than blocking forever: if Electron crashes between spawn
  /// and write, a hung daemon holding a port is worse than a clean exit.
  static Future<BootstrapConfig> readFrom(
    Stream<String> stdinLines, {
    Duration timeout = const Duration(seconds: 10),
  }) async {
    final line = await stdinLines.first.timeout(
      timeout,
      onTimeout: () => throw TimeoutException(
        'no bootstrap line on stdin after ${timeout.inSeconds}s',
      ),
    );
    return BootstrapConfig.parse(line);
  }

  /// Never let secrets reach a log line.
  @override
  String toString() =>
      'BootstrapConfig(userDataDir: $userDataDir, logLevel: $logLevel, '
      'sessionToken: <redacted>, masterKey: <redacted>)';
}
